// GENERATED by `sdp build` — the runnable registrar of spec:carrier.markdown-pack-authoring.spec-envelope-refused.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { specEnvelopeRefusedContract } from "../generated/contracts/carrier.markdown-pack-authoring.spec-envelope-refused.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.markdown-pack-authoring.spec-envelope-refused.contract.js";
import type {
  MarkdownPackAuthoringConditions,
  MarkdownPackAuthoringOutcome,
} from "../generated/contracts/carrier.markdown-pack-authoring.space.js";

export function registerSpecEnvelopeRefused<World>(
  adapters: RunnableExampleAdapters<
    World,
    MarkdownPackAuthoringConditions,
    MarkdownPackAuthoringOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    MarkdownPackAuthoringConditions,
    MarkdownPackAuthoringOutcome
  >;
  const bindings = {
    "an extraction root holding the pack carrier {carrierSource}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the extractor derives the graph": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names the refusal {findingId} and the graph holds no pack node": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names the refusal {findingId} and the graph holds no pack node",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    specEnvelopeRefusedContract,
    { carrierSource: "a Markdown pack manifest carrying kind: behavior" },
    ["carrierSource"],
    adapters,
    bindings,
  );
}
