// GENERATED by `sdp build` — the runnable registrar of spec:carrier.markdown-body-grammar.second-primary-owner-refused.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { secondPrimaryOwnerRefusedContract } from "../generated/contracts/carrier.markdown-body-grammar.second-primary-owner-refused.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.markdown-body-grammar.second-primary-owner-refused.contract.js";
import type {
  MarkdownBodyGrammarConditions,
  MarkdownBodyGrammarOutcome,
} from "../generated/contracts/carrier.markdown-body-grammar.space.js";

export function registerSecondPrimaryOwnerRefused<World>(
  adapters: RunnableExampleAdapters<
    World,
    MarkdownBodyGrammarConditions,
    MarkdownBodyGrammarOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    MarkdownBodyGrammarConditions,
    MarkdownBodyGrammarOutcome
  >;
  const bindings = {
    "a Markdown Spec carrier whose {owner} section holds {construct}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the extractor reifies the carrier": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the carrier is refused whole with the finding {findingId} whose message contains {reason}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the carrier is refused whole with the finding {findingId} whose message contains {reason}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    secondPrimaryOwnerRefusedContract,
    { owner: "Rule", construct: "a plain bullet after a Behavior section" },
    ["owner", "construct"],
    adapters,
    bindings,
  );
}
