// GENERATED by `sdp build` — the runnable registrar of spec:carrier.gherkin-authoring.example-space-extraction.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { exampleSpaceExtractionContract } from "../generated/contracts/carrier.gherkin-authoring.example-space-extraction.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.gherkin-authoring.example-space-extraction.contract.js";
import type {
  GherkinAuthoringConditions,
  GherkinAuthoringOutcome,
} from "../generated/contracts/carrier.gherkin-authoring.space.js";

export function registerExampleSpaceExtraction<World>(
  adapters: RunnableExampleAdapters<World, GherkinAuthoringConditions, GherkinAuthoringOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, GherkinAuthoringConditions, GherkinAuthoringOutcome>;
  const bindings = {
    "the Gherkin fixture corpus {probe}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the fixture corpus is extracted and validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "extraction reports {findingCount} findings": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "extraction reports {findingCount} findings",
        params,
      });
    },
    "the graph contains exactly {specCount} Specs": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph contains exactly {specCount} Specs",
        params,
      });
    },
    "the parent example space contains {spaceStep}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the parent example space contains {spaceStep}",
        params,
      });
    },
    "the graph omits the Spec {absentId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph omits the Spec {absentId}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    exampleSpaceExtractionContract,
    { probe: "example-space" },
    ["probe"],
    adapters,
    bindings,
  );
}
