// GENERATED by `sdp build` — the runnable registrar of spec:carrier.slot-notation.refused-guess.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { refusedGuessContract } from "../generated/contracts/carrier.slot-notation.refused-guess.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.slot-notation.refused-guess.contract.js";
import type {
  SlotNotationConditions,
  SlotNotationOutcome,
} from "../generated/contracts/carrier.slot-notation.space.js";

export function registerRefusedGuess<World>(
  adapters: RunnableExampleAdapters<World, SlotNotationConditions, SlotNotationOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, SlotNotationConditions, SlotNotationOutcome>;
  const bindings = {
    "the step text {stepText}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the notation parses the step text": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the notation finds {slotCount} slot groups": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the notation finds {slotCount} slot groups",
        params,
      });
    },
    "the first group has the form {form} and the name {slotName}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the first group has the form {form} and the name {slotName}",
        params,
      });
    },
    "the step skeleton is {skeleton}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the step skeleton is {skeleton}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    refusedGuessContract,
    { stepText: "a stray { then {n: maybe} line items" },
    ["stepText"],
    adapters,
    bindings,
  );
}
