// GENERATED by `sdp build` — the runnable registrar of spec:carrier.markdown-parser.bounded-parity.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { boundedParityContract } from "../generated/contracts/carrier.markdown-parser.bounded-parity.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.markdown-parser.bounded-parity.contract.js";
import type {
  MarkdownParserConditions,
  MarkdownParserOutcome,
} from "../generated/contracts/carrier.markdown-parser.space.js";

export function registerBoundedParity<World>(
  adapters: RunnableExampleAdapters<World, MarkdownParserConditions, MarkdownParserOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, MarkdownParserConditions, MarkdownParserOutcome>;
  const bindings = {
    "the paired carrier probes named {probe}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "both carriers reify their probe": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "both carriers report the finding class {findingId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "both carriers report the finding class {findingId}",
        params,
      });
    },
    "the TypeScript carrier reports severity {typeScriptSeverity} and extracts {typeScriptSpecs} specs":
      (execution, params) => {
        compareContractOutcome(execution, {
          kind: "then",
          text: "the TypeScript carrier reports severity {typeScriptSeverity} and extracts {typeScriptSpecs} specs",
          params,
        });
      },
    "the Markdown carrier reports severity {markdownSeverity} and extracts {markdownSpecs} specs": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the Markdown carrier reports severity {markdownSeverity} and extracts {markdownSpecs} specs",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    boundedParityContract,
    { probe: "unrecognized-property" },
    ["probe"],
    adapters,
    bindings,
  );
}
