// GENERATED by `sdp build` — the runnable registrar of spec:carrier.gherkin-authoring.malformed-relation-refused.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { malformedRelationRefusedContract } from "../generated/contracts/carrier.gherkin-authoring.malformed-relation-refused.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.gherkin-authoring.malformed-relation-refused.contract.js";
import type {
  GherkinAuthoringConditions,
  GherkinAuthoringOutcome,
} from "../generated/contracts/carrier.gherkin-authoring.space.js";

export function registerMalformedRelationRefused<World>(
  adapters: RunnableExampleAdapters<World, GherkinAuthoringConditions, GherkinAuthoringOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, GherkinAuthoringConditions, GherkinAuthoringOutcome>;
  const bindings = {
    "the Gherkin fixture corpus {probe}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the fixture corpus is extracted and validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "extraction reports {findingCount} findings": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "extraction reports {findingCount} findings",
        params,
      });
    },
    "the first finding is {findingId} at line {line}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the first finding is {findingId} at line {line}",
        params,
      });
    },
    "the graph omits the Spec {absentId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph omits the Spec {absentId}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    malformedRelationRefusedContract,
    { probe: "malformed-relation" },
    ["probe"],
    adapters,
    bindings,
  );
}
