// GENERATED by `sdp build` — the runnable registrar of spec:carrier.sdp-import.round-trip.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { roundTripContract } from "../generated/contracts/carrier.sdp-import.round-trip.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.sdp-import.round-trip.contract.js";
import type {
  SdpImportConditions,
  SdpImportOutcome,
} from "../generated/contracts/carrier.sdp-import.space.js";

export function registerRoundTrip<World>(
  adapters: RunnableExampleAdapters<World, SdpImportConditions, SdpImportOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, SdpImportConditions, SdpImportOutcome>;
  const bindings = {
    "a TS-carrier spec": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "importTypeScriptSpec runs": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the emitted Markdown re-parses to an equal graph": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the emitted Markdown re-parses to an equal graph",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(roundTripContract, {}, [], adapters, bindings);
}
