// GENERATED by `sdp build` — the runnable registrar of spec:carrier.gherkin-authoring.parent-child-extraction.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { parentChildExtractionContract } from "../generated/contracts/carrier.gherkin-authoring.parent-child-extraction.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.gherkin-authoring.parent-child-extraction.contract.js";
import type {
  GherkinAuthoringConditions,
  GherkinAuthoringOutcome,
} from "../generated/contracts/carrier.gherkin-authoring.space.js";

export function registerParentChildExtraction<World>(
  adapters: RunnableExampleAdapters<World, GherkinAuthoringConditions, GherkinAuthoringOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, GherkinAuthoringConditions, GherkinAuthoringOutcome>;
  const bindings = {
    "the Gherkin fixture corpus {probe}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the fixture corpus is extracted and validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "extraction reports {findingCount} findings": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "extraction reports {findingCount} findings",
        params,
      });
    },
    "the graph contains exactly {specCount} Specs": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph contains exactly {specCount} Specs",
        params,
      });
    },
    "the graph contains the Spec {specId} with kind {specKind}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph contains the Spec {specId} with kind {specKind}",
        params,
      });
    },
    "the graph contains the child Spec {childId} with kind {specKind}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph contains the child Spec {childId} with kind {specKind}",
        params,
      });
    },
    "the child Spec {childId} declares {relationType} to {relationTarget}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the child Spec {childId} declares {relationType} to {relationTarget}",
        params,
      });
    },
    "the child Spec {childId} declares the additional relation {relationType} to {relationTarget}":
      (execution, params) => {
        compareContractOutcome(execution, {
          kind: "then",
          text: "the child Spec {childId} declares the additional relation {relationType} to {relationTarget}",
          params,
        });
      },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    parentChildExtractionContract,
    { probe: "parent-child" },
    ["probe"],
    adapters,
    bindings,
  );
}
