// GENERATED by `sdp build` — the runnable registrar of spec:carrier.inline-code-spans.description.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { descriptionContract } from "../generated/contracts/carrier.inline-code-spans.description.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/carrier.inline-code-spans.description.contract.js";
import type {
  InlineCodeSpansConditions,
  InlineCodeSpansOutcome,
} from "../generated/contracts/carrier.inline-code-spans.space.js";

export function registerDescription<World>(
  adapters: RunnableExampleAdapters<World, InlineCodeSpansConditions, InlineCodeSpansOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, InlineCodeSpansConditions, InlineCodeSpansOutcome>;
  const bindings = {
    "the code-span matrix in {location}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the extractor reifies the probes": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "matched spans preserve {accepted} carriers and exposed HTML refuses {refused} carriers": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "matched spans preserve {accepted} carriers and exposed HTML refuses {refused} carriers",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    descriptionContract,
    { location: "description" },
    ["location"],
    adapters,
    bindings,
  );
}
