// GENERATED by `sdp build` — the runnable registrar of spec:consumers.binding-language-views.pack-member-table.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { packMemberTableContract } from "../generated/contracts/consumers.binding-language-views.pack-member-table.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/consumers.binding-language-views.pack-member-table.contract.js";
import type {
  BindingLanguageViewsConditions,
  BindingLanguageViewsOutcome,
} from "../generated/contracts/consumers.binding-language-views.space.js";

export function registerPackMemberTable<World>(
  adapters: RunnableExampleAdapters<
    World,
    BindingLanguageViewsConditions,
    BindingLanguageViewsOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    BindingLanguageViewsConditions,
    BindingLanguageViewsOutcome
  >;
  const bindings = {
    "the graph holds a spec {specId} bound by {bindings}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph holds a pack {packId} listing that spec beside an unbound member": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the Design Review renders the graph": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the pack member table repeats those binding values for the spec: {memberTableRepeats}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the pack member table repeats those binding values for the spec: {memberTableRepeats}",
        params,
      });
    },
    "the internal delivery-fact name {factName} appears as rendered label text: {factNameRendered}":
      (execution, params) => {
        compareContractOutcome(execution, {
          kind: "then",
          text: "the internal delivery-fact name {factName} appears as rendered label text: {factNameRendered}",
          params,
        });
      },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    packMemberTableContract,
    {
      specId: "spec:probe.bound-surface",
      bindings: "an implementing code anchor and a verifying test anchor",
      packId: "pack:probe.review-aggregate",
    },
    ["specId", "bindings", "packId"],
    adapters,
    bindings,
  );
}
