// GENERATED by `sdp build` — the runnable registrar of spec:consumers.derived-readiness-banner.dishonest-divergence.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { dishonestDivergenceContract } from "../generated/contracts/consumers.derived-readiness-banner.dishonest-divergence.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/consumers.derived-readiness-banner.dishonest-divergence.contract.js";
import type {
  DerivedReadinessBannerConditions,
  DerivedReadinessBannerOutcome,
} from "../generated/contracts/consumers.derived-readiness-banner.space.js";

export function registerDishonestDivergence<World>(
  adapters: RunnableExampleAdapters<
    World,
    DerivedReadinessBannerConditions,
    DerivedReadinessBannerOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    DerivedReadinessBannerConditions,
    DerivedReadinessBannerOutcome
  >;
  const bindings = {
    "the graph holds a rule spec {specId} whose stated readiness is {statedReadiness}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the spec {structure}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the Design Review renders the graph": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the spec page renders the floor reached {floorReached}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the spec page renders the floor reached {floorReached}",
        params,
      });
    },
    "the divergence banner is raised: {bannerRaised}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the divergence banner is raised: {bannerRaised}",
        params,
      });
    },
    "the banner names the first unmet clause {clauseId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the banner names the first unmet clause {clauseId}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    dishonestDivergenceContract,
    {
      specId: "spec:probe.overstated-rung",
      statedReadiness: "ready",
      structure: "records a blocking open question",
    },
    ["specId", "statedReadiness", "structure"],
    adapters,
    bindings,
  );
}
