// GENERATED by `sdp build` — the runnable registrar of spec:consumers.wholesale-view-rewrite.late-stale-page.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { lateStalePageContract } from "../generated/contracts/consumers.wholesale-view-rewrite.late-stale-page.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/consumers.wholesale-view-rewrite.late-stale-page.contract.js";
import type {
  WholesaleViewRewriteConditions,
  WholesaleViewRewriteOutcome,
} from "../generated/contracts/consumers.wholesale-view-rewrite.space.js";

export function registerLateStalePage<World>(
  adapters: RunnableExampleAdapters<
    World,
    WholesaleViewRewriteConditions,
    WholesaleViewRewriteOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    WholesaleViewRewriteConditions,
    WholesaleViewRewriteOutcome
  >;
  const bindings = {
    "an extraction root holding {corpus} and a stale view page {stalePage}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the stale page is planted {planted}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the {command} command runs at that root": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the run exits {exitCode}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the run exits {exitCode}",
        params,
      });
    },
    "the view directory survives: {viewSurvives}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the view directory survives: {viewSurvives}",
        params,
      });
    },
    "the view holds the current page {currentPage}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the view holds the current page {currentPage}",
        params,
      });
    },
    "the stale page survives: {staleSurvives}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the stale page survives: {staleSurvives}",
        params,
      });
    },
    "a temporary view sibling survives: {temporarySurvives}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "a temporary view sibling survives: {temporarySurvives}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    lateStalePageContract,
    {
      corpus: "one authored spec",
      stalePage: "spec/probe.departed.md",
      planted: "after the build has invalidated the view",
      command: "view",
    },
    ["corpus", "stalePage", "planted", "command"],
    adapters,
    bindings,
  );
}
