// GENERATED by `sdp build` — the runnable registrar of spec:consumers.design-review.pure-projection.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { pureProjectionContract } from "../generated/contracts/consumers.design-review.pure-projection.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/consumers.design-review.pure-projection.contract.js";
import type {
  DesignReviewConditions,
  DesignReviewOutcome,
} from "../generated/contracts/consumers.design-review.space.js";

export function registerPureProjection<World>(
  adapters: RunnableExampleAdapters<World, DesignReviewConditions, DesignReviewOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, DesignReviewConditions, DesignReviewOutcome>;
  const bindings = {
    "an extraction root holding a Pack, its member Specs, and one member the checks warn about":
      () => {
        // Given state is materialized by createWorld from the generated point.
      },
    "the Design Review renders the graph derived from that root": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the page set holds the index page {indexPage}, one page per Spec, and one page per Pack": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the page set holds the index page {indexPage}, one page per Spec, and one page per Pack",
        params,
      });
    },
    "the page {packPage} renders its members in context": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the page {packPage} renders its members in context",
        params,
      });
    },
    "the page {specPage} renders the finding {findingId} as data": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the page {specPage} renders the finding {findingId} as data",
        params,
      });
    },
    "a second render from a freshly derived graph is byte-identical: {byteIdentical}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "a second render from a freshly derived graph is byte-identical: {byteIdentical}",
        params,
      });
    },
    "the render leaves the extraction root byte-identical: {rootUntouched}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the render leaves the extraction root byte-identical: {rootUntouched}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(pureProjectionContract, {}, [], adapters, bindings);
}
