// GENERATED by `sdp build` — the runnable registrar of spec:extraction.example-runner.red-step-naming.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { redStepNamingContract } from "../generated/contracts/extraction.example-runner.red-step-naming.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/extraction.example-runner.red-step-naming.contract.js";
import type {
  ExampleRunnerConditions,
  ExampleRunnerOutcome,
} from "../generated/contracts/extraction.example-runner.space.js";

export function registerRedStepNaming<World>(
  adapters: RunnableExampleAdapters<World, ExampleRunnerConditions, ExampleRunnerOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, ExampleRunnerConditions, ExampleRunnerOutcome>;
  const bindings = {
    "a contract whose given step repeats {occurrences} times before one when step and one then step":
      () => {
        // Given state is materialized by createWorld from the generated point.
      },
    "the handler bound to the {failingPhase} step throws {thrown}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the bound plan runs against a fresh world": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the run {outcome}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the run {outcome}",
        params,
      });
    },
    "the failure names the step in the Spec's own words as {failureLabel}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the failure names the step in the Spec's own words as {failureLabel}",
        params,
      });
    },
    "the failure preserves the original detail {detail}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the failure preserves the original detail {detail}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    redStepNamingContract,
    { occurrences: 2, failingPhase: "when", thrown: "boom" },
    ["occurrences", "failingPhase", "thrown"],
    adapters,
    bindings,
  );
}
