// GENERATED by `sdp build` — the runnable registrar of spec:extraction.excludes.segment-boundary.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { segmentBoundaryContract } from "../generated/contracts/extraction.excludes.segment-boundary.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/extraction.excludes.segment-boundary.contract.js";
import type {
  ExcludesConditions,
  ExcludesOutcome,
} from "../generated/contracts/extraction.excludes.space.js";

export function registerSegmentBoundary<World>(
  adapters: RunnableExampleAdapters<World, ExcludesConditions, ExcludesOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, ExcludesConditions, ExcludesOutcome>;
  const bindings = {
    "the extraction root carries the tree {excludedTree} and the similar sibling {similarTree}":
      () => {
        // Given state is materialized by createWorld from the generated point.
      },
    "the consumer supplies the exclusion {exclusion}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the root is discovered": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the discovery attempt {outcome}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the discovery attempt {outcome}",
        params,
      });
    },
    "the surviving spec carrier is {specCarrier} and the surviving anchor candidate is {anchorCandidate}":
      (execution, params) => {
        compareContractOutcome(execution, {
          kind: "then",
          text: "the surviving spec carrier is {specCarrier} and the surviving anchor candidate is {anchorCandidate}",
          params,
        });
      },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    segmentBoundaryContract,
    { excludedTree: "foo", similarTree: "foobar", exclusion: "foo" },
    ["excludedTree", "similarTree", "exclusion"],
    adapters,
    bindings,
  );
}
