// GENERATED by `sdp build` — the runnable registrar of spec:extraction.pack-member-order.manifest-order-kept.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { manifestOrderKeptContract } from "../generated/contracts/extraction.pack-member-order.manifest-order-kept.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/extraction.pack-member-order.manifest-order-kept.contract.js";
import type {
  PackMemberOrderConditions,
  PackMemberOrderOutcome,
} from "../generated/contracts/extraction.pack-member-order.space.js";

export function registerManifestOrderKept<World>(
  adapters: RunnableExampleAdapters<World, PackMemberOrderConditions, PackMemberOrderOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, PackMemberOrderConditions, PackMemberOrderOutcome>;
  const bindings = {
    "a Markdown Pack manifest whose specs list reads {manifestOrder}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is derived and serialized": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the serialized Pack node lists the members {serializedMembers}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the serialized Pack node lists the members {serializedMembers}",
        params,
      });
    },
    "the serialized belongsTo edges run from {edgeSources}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the serialized belongsTo edges run from {edgeSources}",
        params,
      });
    },
    "the reader's Pack context lists the members {readerMembers}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the reader's Pack context lists the members {readerMembers}",
        params,
      });
    },
    "the payload declares the schema version {schemaVersion}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the payload declares the schema version {schemaVersion}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    manifestOrderKeptContract,
    { manifestOrder: "spec:probe.zeta, spec:probe.alpha, spec:probe.mid" },
    ["manifestOrder"],
    adapters,
    bindings,
  );
}
