// GENERATED by `sdp build` — the runnable registrar of spec:extraction.schema-versioning.declared-version.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { declaredVersionContract } from "../generated/contracts/extraction.schema-versioning.declared-version.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/extraction.schema-versioning.declared-version.contract.js";
import type {
  SchemaVersioningConditions,
  SchemaVersioningOutcome,
} from "../generated/contracts/extraction.schema-versioning.space.js";

export function registerDeclaredVersion<World>(
  adapters: RunnableExampleAdapters<World, SchemaVersioningConditions, SchemaVersioningOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, SchemaVersioningConditions, SchemaVersioningOutcome>;
  const bindings = {
    "a graph derived from the authored spec {specId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph payload is serialized": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the payload declares the schema version {schemaVersion}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the payload declares the schema version {schemaVersion}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    declaredVersionContract,
    { specId: "spec:probe.schema-versioning" },
    ["specId"],
    adapters,
    bindings,
  );
}
