// GENERATED by `sdp build` — the runnable registrar of spec:extraction.build-pipeline.same-invocation.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { sameInvocationContract } from "../generated/contracts/extraction.build-pipeline.same-invocation.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/extraction.build-pipeline.same-invocation.contract.js";
import type {
  BuildPipelineConditions,
  BuildPipelineOutcome,
} from "../generated/contracts/extraction.build-pipeline.space.js";

export function registerSameInvocation<World>(
  adapters: RunnableExampleAdapters<World, BuildPipelineConditions, BuildPipelineOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, BuildPipelineConditions, BuildPipelineOutcome>;
  const bindings = {
    "an extraction root containing the isolated spec {specId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "one query invocation reads the reader, raw graph, and validation report": async (
      execution,
    ) => {
      await invokeRunnableExample(execution);
    },
    "the query exits {exitCode}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the query exits {exitCode}",
        params,
      });
    },
    "both graph entrances return the spec {returnedSpecId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "both graph entrances return the spec {returnedSpecId}",
        params,
      });
    },
    "the validation report names the same subject {findingSubjectId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the validation report names the same subject {findingSubjectId}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    sameInvocationContract,
    { specId: "spec:probe.same-invocation" },
    ["specId"],
    adapters,
    bindings,
  );
}
