// GENERATED by `sdp build` — the runnable registrar of spec:model.stable-ids.malformed-refusal.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { malformedRefusalContract } from "../generated/contracts/model.stable-ids.malformed-refusal.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/model.stable-ids.malformed-refusal.contract.js";
import type {
  StableIdsConditions,
  StableIdsOutcome,
} from "../generated/contracts/model.stable-ids.space.js";

export function registerMalformedRefusal<World>(
  adapters: RunnableExampleAdapters<World, StableIdsConditions, StableIdsOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, StableIdsConditions, StableIdsOutcome>;
  const bindings = {
    "the authored identifier {identifier}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the identifier is parsed": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "parsing {outcome}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "parsing {outcome}",
        params,
      });
    },
    "the refusal names the reason {reason}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the refusal names the reason {reason}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    malformedRefusalContract,
    { identifier: "Spec:orders.create-order" },
    ["identifier"],
    adapters,
    bindings,
  );
}
