// GENERATED by `sdp build` — the runnable registrar of spec:model.anchors.lookalike-refusal.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { lookalikeRefusalContract } from "../generated/contracts/model.anchors.lookalike-refusal.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/model.anchors.lookalike-refusal.contract.js";
import type {
  AnchorsConditions,
  AnchorsOutcome,
} from "../generated/contracts/model.anchors.space.js";

export function registerLookalikeRefusal<World>(
  adapters: RunnableExampleAdapters<World, AnchorsConditions, AnchorsOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, AnchorsConditions, AnchorsOutcome>;
  const bindings = {
    "a repository whose one source file builds an anchor through {builderSource}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the repository is extracted": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the extraction mints {anchorCount} anchors": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the extraction mints {anchorCount} anchors",
        params,
      });
    },
    "the extraction reports {findingCount} findings": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the extraction reports {findingCount} findings",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    lookalikeRefusalContract,
    { builderSource: "a consumer-local lookalike module" },
    ["builderSource"],
    adapters,
    bindings,
  );
}
