// GENERATED by `sdp build` — the runnable registrar of spec:model.open-question-keys.keyed-question-resolves.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { keyedQuestionResolvesContract } from "../generated/contracts/model.open-question-keys.keyed-question-resolves.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/model.open-question-keys.keyed-question-resolves.contract.js";
import type {
  OpenQuestionKeysConditions,
  OpenQuestionKeysOutcome,
} from "../generated/contracts/model.open-question-keys.space.js";

export function registerKeyedQuestionResolves<World>(
  adapters: RunnableExampleAdapters<World, OpenQuestionKeysConditions, OpenQuestionKeysOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, OpenQuestionKeysConditions, OpenQuestionKeysOutcome>;
  const bindings = {
    "a Markdown Spec carrier {specId} whose open questions read {questions}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "a second Spec that names {address} in its narrative and declares dependsOn on the first":
      () => {
        // Given state is materialized by createWorld from the generated point.
      },
    "the extractor reifies both carriers and the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the first carrier is reified: {reified}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the first carrier is reified: {reified}",
        params,
      });
    },
    "the extraction findings name {extractMessage}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the extraction findings name {extractMessage}",
        params,
      });
    },
    "the graph holds the question keys {keys}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the graph holds the question keys {keys}",
        params,
      });
    },
    "the report holds {mentionErrors} prose-mention errors": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report holds {mentionErrors} prose-mention errors",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    keyedQuestionResolvesContract,
    {
      specId: "spec:probe.subject",
      questions: "- [blocking #aggregateReach] Does the owner widen the aggregate?; - [non-blocking] Is the name final?",
      address: "spec:probe.subject#question.aggregateReach",
    },
    ["specId", "questions", "address"],
    adapters,
    bindings,
  );
}
