import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { runBuild, type BuildHooks } from "../src/cli/build-command.js";
import { generateContracts } from "../src/codegen/contracts.js";
import { createCaptureOutput } from "./helpers/cli-capture.js";

function runRegistrarBuild(
  root: string,
  registrars: ReadonlyMap<string, string>,
  hooks: BuildHooks = {},
): { readonly exitCode: number; readonly stderr: string } {
  const capture = createCaptureOutput();
  const outcome = runBuild({ root, exclude: [], checkClean: false }, capture.output, "build", {
    ...hooks,
    generateContracts: (graph) => ({ ...generateContracts(graph), registrars }),
  });

  return { exitCode: outcome.exitCode, stderr: capture.readStderr() };
}

function directoryLink(target: string, path: string): void {
  symlinkSync(target, path, process.platform === "win32" ? "junction" : "dir");
}

describe("registrar path confinement", () => {
  it.each([
    "..\\outside.test.generated.ts",
    "/tmp/outside.test.generated.ts",
    "C:outside.test.generated.ts",
    "C:/outside.test.generated.ts",
    "C:\\outside.test.generated.ts",
    "\\\\server\\share\\outside.test.generated.ts",
    "//server/share/outside.test.generated.ts",
  ])("refuses non-POSIX or rooted generated path %j", (relativePath) => {
    const root = mkdtempSync(join(tmpdir(), "sdp-registrar-path-"));

    try {
      const result = runRegistrarBuild(root, new Map([[relativePath, "outside bytes\n"]]));

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("unsafe registrar sibling path");
      expect(existsSync(join(root, relativePath))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("refuses publication through an in-root parent symlink to outside", () => {
    const root = mkdtempSync(join(tmpdir(), "sdp-registrar-root-"));
    const outside = mkdtempSync(join(tmpdir(), "sdp-registrar-outside-"));
    const linkedParent = join(root, "test", "linked");
    const outsideRegistrar = join(outside, "probe.test.generated.ts");

    try {
      mkdirSync(join(root, "test"), { recursive: true });
      directoryLink(outside, linkedParent);

      const result = runRegistrarBuild(
        root,
        new Map([["test/linked/probe.test.generated.ts", "generated bytes\n"]]),
      );

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("unsafe registrar sibling path");
      expect(existsSync(outsideRegistrar)).toBe(false);
      expect(existsSync(`${outsideRegistrar}.tmp`)).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
      rmSync(outside, { recursive: true, force: true });
    }
  });

  it("does not delete a manifest-owned registrar through a parent symlink to outside", () => {
    const root = mkdtempSync(join(tmpdir(), "sdp-registrar-root-"));
    const outside = mkdtempSync(join(tmpdir(), "sdp-registrar-outside-"));
    const linkedParent = join(root, "test", "linked");
    const outsideRegistrar = join(outside, "stale.test.generated.ts");

    try {
      mkdirSync(join(root, "generated"), { recursive: true });
      mkdirSync(join(root, "test"), { recursive: true });
      directoryLink(outside, linkedParent);
      writeFileSync(outsideRegistrar, "outside sentinel\n", "utf8");
      writeFileSync(
        join(root, "generated", "registrars.json"),
        `${JSON.stringify(
          { version: 1, files: ["test/linked/stale.test.generated.ts"] },
          null,
          2,
        )}\n`,
        "utf8",
      );

      const result = runRegistrarBuild(root, new Map());

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("unsafe registrar sibling path");
      expect(readFileSync(outsideRegistrar, "utf8")).toBe("outside sentinel\n");
    } finally {
      rmSync(root, { recursive: true, force: true });
      rmSync(outside, { recursive: true, force: true });
    }
  });

  it("refuses publication after the registrar parent is swapped for an outside symlink", () => {
    const root = mkdtempSync(join(tmpdir(), "sdp-registrar-root-"));
    const outside = mkdtempSync(join(tmpdir(), "sdp-registrar-outside-"));
    const registrarParent = join(root, "test", "suite");
    const parkedParent = join(root, "test", "suite-parked");
    const outsideRegistrar = join(outside, "probe.test.generated.ts");

    try {
      mkdirSync(registrarParent, { recursive: true });
      writeFileSync(outsideRegistrar, "outside sentinel\n", "utf8");

      const result = runRegistrarBuild(
        root,
        new Map([["test/suite/probe.test.generated.ts", "generated bytes\n"]]),
        {
          writeFileSync: (path, data, options) => {
            writeFileSync(path, data, options);

            if (String(path).endsWith("probe.test.generated.ts.tmp")) {
              renameSync(registrarParent, parkedParent);
              directoryLink(outside, registrarParent);
            }
          },
        },
      );

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("unsafe registrar sibling path");
      expect(readFileSync(outsideRegistrar, "utf8")).toBe("outside sentinel\n");
      expect(existsSync(`${outsideRegistrar}.tmp`)).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
      rmSync(outside, { recursive: true, force: true });
    }
  });

  it("publishes valid POSIX registrar paths with sorted deterministic manifest ownership", () => {
    const root = mkdtempSync(join(tmpdir(), "sdp-registrar-valid-"));
    const registrars = new Map([
      ["test/z/z.test.generated.ts", "z bytes\n"],
      ["test/a/a.test.generated.ts", "a bytes\n"],
    ]);

    try {
      expect(runRegistrarBuild(root, registrars).exitCode).toBe(0);
      const manifestPath = join(root, "generated", "registrars.json");
      const firstManifest = readFileSync(manifestPath, "utf8");

      expect(JSON.parse(firstManifest)).toEqual({
        version: 1,
        files: ["test/a/a.test.generated.ts", "test/z/z.test.generated.ts"],
      });
      expect(readFileSync(join(root, "test/a/a.test.generated.ts"), "utf8")).toBe("a bytes\n");
      expect(readFileSync(join(root, "test/z/z.test.generated.ts"), "utf8")).toBe("z bytes\n");

      expect(runRegistrarBuild(root, registrars).exitCode).toBe(0);
      expect(readFileSync(manifestPath, "utf8")).toBe(firstManifest);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
