// GENERATED by `sdp build` — the runnable registrar of spec:validation.pack-coherence.incoherent-aggregate.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { incoherentAggregateContract } from "../generated/contracts/validation.pack-coherence.incoherent-aggregate.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.pack-coherence.incoherent-aggregate.contract.js";
import type {
  PackCoherenceConditions,
  PackCoherenceOutcome,
} from "../generated/contracts/validation.pack-coherence.space.js";

export function registerIncoherentAggregate<World>(
  adapters: RunnableExampleAdapters<World, PackCoherenceConditions, PackCoherenceOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, PackCoherenceConditions, PackCoherenceOutcome>;
  const bindings = {
    "a pack {packId} lists the spec {specId} {memberCount} times": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the pack also names that spec as a modelRef": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the report holds {findingCount} pack-coherence findings": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report holds {findingCount} pack-coherence findings",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    incoherentAggregateContract,
    { packId: "pack:probe.checkout", specId: "spec:probe.create-order", memberCount: 2 },
    ["packId", "specId", "memberCount"],
    adapters,
    bindings,
  );
}
