// GENERATED by `sdp build` — the runnable registrar of spec:validation.claim-separation.collapsed-edge-claim.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { collapsedEdgeClaimContract } from "../generated/contracts/validation.claim-separation.collapsed-edge-claim.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.claim-separation.collapsed-edge-claim.contract.js";
import type {
  ClaimSeparationConditions,
  ClaimSeparationOutcome,
} from "../generated/contracts/validation.claim-separation.space.js";

export function registerCollapsedEdgeClaim<World>(
  adapters: RunnableExampleAdapters<World, ClaimSeparationConditions, ClaimSeparationOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, ClaimSeparationConditions, ClaimSeparationOutcome>;
  const bindings = {
    "the graph holds a spec {specId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph carries an off-contract {element} spelled {value}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the finding message states {phrase}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the finding message states {phrase}",
        params,
      });
    },
    "the report holds {floorCount} readiness-floor findings": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report holds {floorCount} readiness-floor findings",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    collapsedEdgeClaimContract,
    { specId: "spec:probe.create-order", element: "edge claim", value: "declared" },
    ["specId", "element", "value"],
    adapters,
    bindings,
  );
}
