// GENERATED by `sdp build` — the runnable registrar of spec:validation.diagnostic-rendering.table-cell-location.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { tableCellLocationContract } from "../generated/contracts/validation.diagnostic-rendering.table-cell-location.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.diagnostic-rendering.table-cell-location.contract.js";
import type {
  DiagnosticRenderingConditions,
  DiagnosticRenderingOutcome,
} from "../generated/contracts/validation.diagnostic-rendering.space.js";

export function registerTableCellLocation<World>(
  adapters: RunnableExampleAdapters<
    World,
    DiagnosticRenderingConditions,
    DiagnosticRenderingOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    DiagnosticRenderingConditions,
    DiagnosticRenderingOutcome
  >;
  const bindings = {
    "a finding naming the validator {validatorId} at severity {severity} carrying the message {message}":
      () => {
        // Given state is materialized by createWorld from the generated point.
      },
    "the {renderer} renderer formats that finding once per location shape": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the findings row carrying the file {file} and the line {line} renders {locationRow}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the findings row carrying the file {file} and the line {line} renders {locationRow}",
        params,
      });
    },
    "the same row carrying the file alone renders {fileOnlyRow}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the same row carrying the file alone renders {fileOnlyRow}",
        params,
      });
    },
    "the same row carrying neither renders {absentRow}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the same row carrying neither renders {absentRow}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    tableCellLocationContract,
    {
      validatorId: "honesty/readiness-floor",
      severity: "error",
      message: "The stated rung is not earned | its floor refused it.",
      renderer: "Design Review",
    },
    ["validatorId", "severity", "message", "renderer"],
    adapters,
    bindings,
  );
}
