// GENERATED by `sdp build` — the runnable registrar of spec:validation.unbound-example-posture.lower-rungs.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { lowerRungsContract } from "../generated/contracts/validation.unbound-example-posture.lower-rungs.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.unbound-example-posture.lower-rungs.contract.js";
import type {
  UnboundExamplePostureConditions,
  UnboundExamplePostureOutcome,
} from "../generated/contracts/validation.unbound-example-posture.space.js";

export function registerLowerRungs<World>(
  adapters: RunnableExampleAdapters<
    World,
    UnboundExamplePostureConditions,
    UnboundExamplePostureOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    UnboundExamplePostureConditions,
    UnboundExamplePostureOutcome
  >;
  const bindings = {
    "the verification posture matrix {matrix}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the reader derives the verification signals": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the matrix reports {warnings} linkage warnings and {gaps} parent gaps and {oracleErrors} oracle errors":
      (execution, params) => {
        compareContractOutcome(execution, {
          kind: "then",
          text: "the matrix reports {warnings} linkage warnings and {gaps} parent gaps and {oracleErrors} oracle errors",
          params,
        });
      },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    lowerRungsContract,
    { matrix: "lower-rungs" },
    ["matrix"],
    adapters,
    bindings,
  );
}
