// GENERATED by `sdp build` — the runnable registrar of spec:validation.duplicate-ids.dual-carrier.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { dualCarrierContract } from "../generated/contracts/validation.duplicate-ids.dual-carrier.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.duplicate-ids.dual-carrier.contract.js";
import type {
  DuplicateIdsConditions,
  DuplicateIdsOutcome,
} from "../generated/contracts/validation.duplicate-ids.space.js";

export function registerDualCarrier<World>(
  adapters: RunnableExampleAdapters<World, DuplicateIdsConditions, DuplicateIdsOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, DuplicateIdsConditions, DuplicateIdsOutcome>;
  const bindings = {
    "a {firstCarrier} carrier declares {specId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "a {secondCarrier} carrier declares {specId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the extraction root is read": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "both sites report {findingId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "both sites report {findingId}",
        params,
      });
    },
    "no graph node is emitted for {specId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "no graph node is emitted for {specId}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    dualCarrierContract,
    { firstCarrier: "TypeScript", specId: "spec:fixture.duplicate", secondCarrier: "Markdown" },
    ["firstCarrier", "specId", "secondCarrier"],
    adapters,
    bindings,
  );
}
