// GENERATED by `sdp build` — the runnable registrar of spec:validation.next-rung-floor.blocking-question.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { blockingQuestionContract } from "../generated/contracts/validation.next-rung-floor.blocking-question.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.next-rung-floor.blocking-question.contract.js";
import type {
  NextRungFloorConditions,
  NextRungFloorOutcome,
} from "../generated/contracts/validation.next-rung-floor.space.js";

export function registerBlockingQuestion<World>(
  adapters: RunnableExampleAdapters<World, NextRungFloorConditions, NextRungFloorOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, NextRungFloorConditions, NextRungFloorOutcome>;
  const bindings = {
    "the graph holds a rule spec {specId} stating readiness {statedReadiness}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the spec {structure}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the reader builds the spec's context": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the floor reached is {floorReached} and the next rung is {nextRung}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the floor reached is {floorReached} and the next rung is {nextRung}",
        params,
      });
    },
    "the next rung's first unmet clause is {clauseId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the next rung's first unmet clause is {clauseId}",
        params,
      });
    },
    "that failure names the targets {targets}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "that failure names the targets {targets}",
        params,
      });
    },
    "the stated rung's floor failures number {currentFailures}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the stated rung's floor failures number {currentFailures}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    blockingQuestionContract,
    {
      specId: "spec:probe.held",
      statedReadiness: "scoped",
      structure: "records a blocking open question",
    },
    ["specId", "statedReadiness", "structure"],
    adapters,
    bindings,
  );
}
