// GENERATED by `sdp build` — the runnable registrar of spec:validation.authored-honesty.section-authored-fact.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { sectionAuthoredFactContract } from "../generated/contracts/validation.authored-honesty.section-authored-fact.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.authored-honesty.section-authored-fact.contract.js";
import type {
  AuthoredHonestyConditions,
  AuthoredHonestyOutcome,
} from "../generated/contracts/validation.authored-honesty.space.js";

export function registerSectionAuthoredFact<World>(
  adapters: RunnableExampleAdapters<World, AuthoredHonestyConditions, AuthoredHonestyOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, AuthoredHonestyConditions, AuthoredHonestyOutcome>;
  const bindings = {
    "the graph holds a spec {specId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the spec hand-authors the delivery fact {factName} at {site}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the finding names the fact {relatedId} and states {phrase}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the finding names the fact {relatedId} and states {phrase}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    sectionAuthoredFactContract,
    {
      specId: "spec:probe.smuggled-fact",
      factName: "implemented",
      site: "a behavior section carrier",
    },
    ["specId", "factName", "site"],
    adapters,
    bindings,
  );
}
