// GENERATED by `sdp build` — the runnable registrar of spec:validation.kind-evidence.empty-promoted-child.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { emptyPromotedChildContract } from "../generated/contracts/validation.kind-evidence.empty-promoted-child.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.kind-evidence.empty-promoted-child.contract.js";
import type {
  KindEvidenceConditions,
  KindEvidenceOutcome,
} from "../generated/contracts/validation.kind-evidence.space.js";

export function registerEmptyPromotedChild<World>(
  adapters: RunnableExampleAdapters<World, KindEvidenceConditions, KindEvidenceOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, KindEvidenceConditions, KindEvidenceOutcome>;
  const bindings = {
    "the graph holds a {kind} spec {specId} stating readiness {readiness}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "its only evidence is {evidence}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the finding names the unmet floor clause {clauseId}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the finding names the unmet floor clause {clauseId}",
        params,
      });
    },
    "the report holds {errorCount} errors": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report holds {errorCount} errors",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    emptyPromotedChildContract,
    {
      kind: "behavior",
      specId: "spec:probe.empty-promotion",
      readiness: "scoped",
      evidence: "an empty promoted rule child",
    },
    ["kind", "specId", "readiness", "evidence"],
    adapters,
    bindings,
  );
}
