// GENERATED by `sdp build` — the runnable registrar of spec:validation.two-check-families.split-report.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { splitReportContract } from "../generated/contracts/validation.two-check-families.split-report.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.two-check-families.split-report.contract.js";
import type {
  TwoCheckFamiliesConditions,
  TwoCheckFamiliesOutcome,
} from "../generated/contracts/validation.two-check-families.space.js";

export function registerSplitReport<World>(
  adapters: RunnableExampleAdapters<World, TwoCheckFamiliesConditions, TwoCheckFamiliesOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, TwoCheckFamiliesConditions, TwoCheckFamiliesOutcome>;
  const bindings = {
    "the graph holds a spec {specId} at readiness {readiness}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the spec declares a dependsOn relation to the absent target {targetId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the aggregate report states no family of its own": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the aggregate report states no family of its own",
        params,
      });
    },
    "the conformance family reports {conformanceId} at severity {conformanceSeverity}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the conformance family reports {conformanceId} at severity {conformanceSeverity}",
        params,
      });
    },
    "the honesty family reports {honestyId} at severity {honestySeverity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the honesty family reports {honestyId} at severity {honestySeverity}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    splitReportContract,
    {
      specId: "spec:probe.two-check-families",
      readiness: "ready",
      targetId: "spec:probe.absent-dependency",
    },
    ["specId", "readiness", "targetId"],
    adapters,
    bindings,
  );
}
