// GENERATED by `sdp build` — the runnable registrar of spec:validation.typed-dependency-floor.missing-targets.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { missingTargetsContract } from "../generated/contracts/validation.typed-dependency-floor.missing-targets.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.typed-dependency-floor.missing-targets.contract.js";
import type {
  TypedDependencyFloorConditions,
  TypedDependencyFloorOutcome,
} from "../generated/contracts/validation.typed-dependency-floor.space.js";

export function registerMissingTargets<World>(
  adapters: RunnableExampleAdapters<
    World,
    TypedDependencyFloorConditions,
    TypedDependencyFloorOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    TypedDependencyFloorConditions,
    TypedDependencyFloorOutcome
  >;
  const bindings = {
    "the typed dependency matrix {matrix}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the reader checks the readiness floor": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the matrix reports {targetFailures} target failures and {resolutionFailures} resolution failures and {questionFailures} blocking question failures":
      (execution, params) => {
        compareContractOutcome(execution, {
          kind: "then",
          text: "the matrix reports {targetFailures} target failures and {resolutionFailures} resolution failures and {questionFailures} blocking question failures",
          params,
        });
      },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    missingTargetsContract,
    { matrix: "missing-targets" },
    ["matrix"],
    adapters,
    bindings,
  );
}
