// GENERATED by `sdp build` — the runnable registrar of spec:validation.warn-level-signals.ready-gap-signal.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { readyGapSignalContract } from "../generated/contracts/validation.warn-level-signals.ready-gap-signal.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.warn-level-signals.ready-gap-signal.contract.js";
import type {
  WarnLevelSignalsConditions,
  WarnLevelSignalsOutcome,
} from "../generated/contracts/validation.warn-level-signals.space.js";

export function registerReadyGapSignal<World>(
  adapters: RunnableExampleAdapters<World, WarnLevelSignalsConditions, WarnLevelSignalsOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, WarnLevelSignalsConditions, WarnLevelSignalsOutcome>;
  const bindings = {
    "the graph holds a spec {specId} at readiness {readiness}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the spec declares {relations}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the report holds {errorCount} errors": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report holds {errorCount} errors",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    readyGapSignalContract,
    { specId: "spec:probe.gap-signal", readiness: "ready", relations: "a decidedBy decision" },
    ["specId", "readiness", "relations"],
    adapters,
    bindings,
  );
}
