// GENERATED by `sdp build` — the runnable registrar of spec:validation.verification-linkage.unresolved-oracle.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { unresolvedOracleContract } from "../generated/contracts/validation.verification-linkage.unresolved-oracle.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.verification-linkage.unresolved-oracle.contract.js";
import type {
  VerificationLinkageConditions,
  VerificationLinkageOutcome,
} from "../generated/contracts/validation.verification-linkage.space.js";

export function registerUnresolvedOracle<World>(
  adapters: RunnableExampleAdapters<
    World,
    VerificationLinkageConditions,
    VerificationLinkageOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    VerificationLinkageConditions,
    VerificationLinkageOutcome
  >;
  const bindings = {
    "the graph holds a parent spec {parentId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "a non-resolving {verifierKind} named {verifierId} points at it": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the parent earns the delivery fact has-verifier: {conferred}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the parent earns the delivery fact has-verifier: {conferred}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    unresolvedOracleContract,
    {
      parentId: "spec:probe.order-policy",
      verifierKind: "oracle anchor",
      verifierId: "oracle:probe.order-policy",
    },
    ["parentId", "verifierKind", "verifierId"],
    adapters,
    bindings,
  );
}
