// GENERATED by `sdp build` — the runnable registrar of spec:validation.oracle-target-eligibility.missing-space-refused.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { missingSpaceRefusedContract } from "../generated/contracts/validation.oracle-target-eligibility.missing-space-refused.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.oracle-target-eligibility.missing-space-refused.contract.js";
import type {
  OracleTargetEligibilityConditions,
  OracleTargetEligibilityOutcome,
} from "../generated/contracts/validation.oracle-target-eligibility.space.js";

export function registerMissingSpaceRefused<World>(
  adapters: RunnableExampleAdapters<
    World,
    OracleTargetEligibilityConditions,
    OracleTargetEligibilityOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    OracleTargetEligibilityConditions,
    OracleTargetEligibilityOutcome
  >;
  const bindings = {
    "the oracle targets a {targetKind} spec": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the target owns an example space: {ownsExampleSpace}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "oracle linkage is resolved": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "oracle linkage reports {findingCount} findings and resolving presence {oraclePresent}": (
      execution,
      params,
    ) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "oracle linkage reports {findingCount} findings and resolving presence {oraclePresent}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    missingSpaceRefusedContract,
    { targetKind: "behavior", ownsExampleSpace: false },
    ["targetKind", "ownsExampleSpace"],
    adapters,
    bindings,
  );
}
