// GENERATED by `sdp build` — the runnable registrar of spec:validation.referential-integrity.did-you-mean.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { didYouMeanContract } from "../generated/contracts/validation.referential-integrity.did-you-mean.contract.js";
import type {
  Step,
  StepParams,
} from "../generated/contracts/validation.referential-integrity.did-you-mean.contract.js";
import type {
  ReferentialIntegrityConditions,
  ReferentialIntegrityOutcome,
} from "../generated/contracts/validation.referential-integrity.space.js";

export function registerDidYouMean<World>(
  adapters: RunnableExampleAdapters<
    World,
    ReferentialIntegrityConditions,
    ReferentialIntegrityOutcome
  >,
): void {
  type Execution = RunnableExampleWorld<
    World,
    ReferentialIntegrityConditions,
    ReferentialIntegrityOutcome
  >;
  const bindings = {
    "the graph holds one spec {presentId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the spec declares a dependsOn relation to {targetId}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the graph is validated": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "the report names {findingId} at severity {severity}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the report names {findingId} at severity {severity}",
        params,
      });
    },
    "the finding offers the nearest-id suggestion: {suggested}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the finding offers the nearest-id suggestion: {suggested}",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    didYouMeanContract,
    { presentId: "spec:probe.create-order", targetId: "spec:probe.create-ordr" },
    ["presentId", "targetId"],
    adapters,
    bindings,
  );
}
