// GENERATED by `sdp build` — the runnable registrar of spec:orders.create-order.valid-cart.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { StepBindings } from "@libar-dev/software-delivery-protocol/runner";
import {
  compareContractOutcome,
  invokeRunnableExample,
  registerRunnableExample,
} from "@libar-dev/software-delivery-protocol/testing";
import type {
  RunnableExampleAdapters,
  RunnableExampleWorld,
} from "@libar-dev/software-delivery-protocol/testing";
import { validCartContract } from "../../generated/contracts/orders.create-order.valid-cart.contract.js";
import type {
  Step,
  StepParams,
} from "../../generated/contracts/orders.create-order.valid-cart.contract.js";
import type {
  CreateOrderConditions,
  CreateOrderOutcome,
} from "../../generated/contracts/orders.create-order.space.js";

export function registerValidCart<World>(
  adapters: RunnableExampleAdapters<World, CreateOrderConditions, CreateOrderOutcome>,
): void {
  type Execution = RunnableExampleWorld<World, CreateOrderConditions, CreateOrderOutcome>;
  const bindings = {
    "a customer has a cart with {n} line items": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "every line item has quantity {q} and unit price {price}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "every cart item is {availability}": () => {
      // Given state is materialized by createWorld from the generated point.
    },
    "the customer submits the cart for order creation": async (execution) => {
      await invokeRunnableExample(execution);
    },
    "an order is created with total {total}": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "an order is created with total {total}",
        params,
      });
    },
    "the order contains the original cart lines": (execution, params) => {
      compareContractOutcome(execution, {
        kind: "then",
        text: "the order contains the original cart lines",
        params,
      });
    },
  } satisfies StepBindings<Execution, Step, StepParams>;

  registerRunnableExample(
    validCartContract,
    { n: 2, q: 1, price: 50, availability: "in stock" },
    ["n", "q", "price", "availability"],
    adapters,
    bindings,
  );
}
