import type { GraphSchema, PrimitiveNode } from "../graph/schema.js";
import { parseSlots, stepSkeleton } from "../notation/slots.js";
import type { SlotDeclaredType, SlotScalar } from "../notation/slots.js";
import type { Finding } from "../validate/contracts.js";

/**
 * The contracts codegen stage of `sdp build` (plan 13 §2.1) — the A2 mechanism: per-example
 * **step contracts** (the literal-union module a test binds against) and per-parent **space
 * contracts** (typed dimensions of the example space · every child's bound point · the Outcome
 * union derived from the parent's Then vocabulary), each a pure function of the extracted graph.
 *
 * Legal status (JS-B2.6's generated-union pattern): derived, regenerable, keyed by spec ID,
 * importable *because* it is a projection — a test that imports a contract imports the graph's
 * truth, never the authored spec module (JS-B2.3 holds; MD-14: the reified truth, not the
 * evaluated value).
 *
 * What refuses to generate is as designed as what generates:
 * - a prose-only example, or one with an unbound slot in a used step (the concreteness law),
 *   is not the `defined`-rung bindable form — it gets no step contract; refusing is the honest
 *   behavior, not a degraded run.
 * - an outcome variant's `kind` is the Then step's own **skeleton text** — the no-guessing rule:
 *   naming an outcome IS naming an authored Then step, so "the oracle may never claim more than
 *   the specs state" stays a `tsc` error with zero derived slugs (prettier names are the grammar
 *   session's, sugar over this identity).
 *
 * Diagnostics degrade loudly, never silently (L2/L3): a bound slot the parent never declares, a
 * value outside a declared closed union, and a conflicting re-binding each warn and drop that
 * one slot — the generated artifact always compiles, and the drift is named at build time.
 */

export const contractsFindingIds = {
  /** A child binds a slot name its parent's example space never declares. */
  undeclaredSlot: "contracts/undeclared-slot",
  /** A bound value does not fit the slot's declared type (off a closed union, wrong scalar). */
  offDimensionValue: "contracts/off-dimension-value",
  /** One example binds the same step skeleton twice with different values — first wins. */
  conflictingBinding: "contracts/conflicting-binding",
  /** Two vocabulary steps declare the same slot name at different types — first wins. */
  conflictingDimension: "contracts/conflicting-dimension",
} as const;

export interface GeneratedContracts {
  /** POSIX path under `generated/contracts/` → file content, sorted by path. */
  readonly files: ReadonlyMap<string, string>;
  readonly findings: readonly Finding[];
}

/** The one import specifier generated modules use — resolved by consumers exactly like any
 *  package import (tsconfig paths / bundler alias in-repo, the published package outside). */
const RUNNER_SPECIFIER = "@libar-dev/software-delivery-protocol/runner";

const GENERATED_HEADER = (subject: string): string =>
  `// GENERATED by \`sdp build\` — ${subject}.\n` +
  `// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:\n` +
  `// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —\n` +
  `// never the authored spec module (JS-B2.3: no spec↔code import edges).\n`;

/* ----- defensive access over reified section content (value data, never typed instances) ----- */

function asRecord(value: unknown): Record<string, unknown> | undefined {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return undefined;
}

function asStringArray(value: unknown): readonly string[] {
  return Array.isArray(value)
    ? value.filter((entry): entry is string => typeof entry === "string")
    : [];
}

const STEP_PHASES = ["given", "when", "then"] as const;
type StepPhase = (typeof STEP_PHASES)[number];

interface StructuredEntry {
  readonly given: readonly string[];
  readonly when: readonly string[];
  readonly then: readonly string[];
}

function structuredEntriesOf(node: PrimitiveNode): readonly StructuredEntry[] {
  const behavior = asRecord(node.sections?.behavior);
  const entries = Array.isArray(behavior?.examples) ? behavior.examples : [];
  const structured: StructuredEntry[] = [];

  for (const entry of entries) {
    const record = asRecord(entry);

    if (record === undefined) {
      continue;
    }

    structured.push({
      given: asStringArray(record.given),
      when: asStringArray(record.when),
      then: asStringArray(record.then),
    });
  }

  return structured;
}

interface VocabularyEntry {
  readonly phase: StepPhase;
  readonly skeleton: string;
  /** Slot name → declared type, authored order (typed slots only — a bare or value-form group
   *  in a vocabulary declares nothing and reads as prose). */
  readonly slots: ReadonlyMap<string, SlotDeclaredType>;
}

function vocabularyOf(node: PrimitiveNode): readonly VocabularyEntry[] | undefined {
  const behavior = asRecord(node.sections?.behavior);
  const space = asRecord(behavior?.exampleSpace);

  if (space === undefined) {
    return undefined;
  }

  const entries: VocabularyEntry[] = [];

  for (const phase of STEP_PHASES) {
    for (const text of asStringArray(space[phase])) {
      const slots = new Map<string, SlotDeclaredType>();

      for (const slot of parseSlots(text)) {
        if (slot.form === "typed" && !slots.has(slot.name)) {
          slots.set(slot.name, slot.type);
        }
      }

      entries.push({ phase, skeleton: stepSkeleton(text), slots });
    }
  }

  return entries;
}

/* ----- naming (deterministic, from the spec id's last path segment) ----- */

function idPath(specId: string): string {
  const colonIndex = specId.indexOf(":");

  return colonIndex === -1 ? specId : specId.slice(colonIndex + 1);
}

function nameParts(specId: string): readonly string[] {
  const segments = idPath(specId).split(".");
  const last = segments[segments.length - 1] ?? idPath(specId);

  return last.split(/[^A-Za-z0-9]+/u).filter((part) => part.length > 0);
}

function pascalCase(specId: string): string {
  const joined = nameParts(specId)
    .map((part) => (part[0] ?? "").toUpperCase() + part.slice(1))
    .join("");

  return /^[0-9]/u.test(joined) ? `X${joined}` : joined;
}

function camelCase(specId: string): string {
  const pascal = pascalCase(specId);

  return (pascal[0] ?? "").toLowerCase() + pascal.slice(1);
}

/* ----- type/value rendering ----- */

function typeExpression(type: SlotDeclaredType): string {
  return type.kind === "enum"
    ? type.values.map((value) => JSON.stringify(value)).join(" | ")
    : type.kind;
}

function valueExpression(value: SlotScalar): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

function scalarKind(value: SlotScalar): "number" | "string" | "boolean" {
  return typeof value === "number" ? "number" : typeof value === "string" ? "string" : "boolean";
}

function valueFitsType(value: SlotScalar, type: SlotDeclaredType): boolean {
  if (type.kind === "enum") {
    return typeof value === "string" && type.values.includes(value);
  }

  return scalarKind(value) === type.kind;
}

function sameType(left: SlotDeclaredType, right: SlotDeclaredType): boolean {
  return typeExpression(left) === typeExpression(right);
}

/* ----- findings ----- */

function contractsFinding(
  validatorId: string,
  message: string,
  node: PrimitiveNode,
  path: string,
): Finding {
  return {
    validatorId,
    family: "conformance",
    severity: "warning",
    message,
    subjectId: node.id,
    path,
    file: node.file,
  };
}

/* ----- the space contract ----- */

interface Dimension {
  readonly name: string;
  readonly type: SlotDeclaredType;
  /** The skeleton of the first vocabulary step declaring the slot — the deterministic label. */
  readonly label: string;
}

interface SpaceModel {
  readonly parent: PrimitiveNode;
  readonly dimensions: readonly Dimension[];
  /** Skeleton → vocabulary entry (first per skeleton, given → when → then). */
  readonly bySkeleton: ReadonlyMap<string, VocabularyEntry>;
  readonly thenEntries: readonly VocabularyEntry[];
}

function buildSpaceModel(
  parent: PrimitiveNode,
  vocabulary: readonly VocabularyEntry[],
  findings: Finding[],
): SpaceModel {
  const dimensions: Dimension[] = [];
  const byName = new Map<string, Dimension>();
  const bySkeleton = new Map<string, VocabularyEntry>();

  for (const entry of vocabulary) {
    if (!bySkeleton.has(entry.skeleton)) {
      bySkeleton.set(entry.skeleton, entry);
    }

    if (entry.phase === "then") {
      continue;
    }

    for (const [name, type] of entry.slots) {
      const existing = byName.get(name);

      if (existing === undefined) {
        const dimension = { name, type, label: entry.skeleton };
        byName.set(name, dimension);
        dimensions.push(dimension);
        continue;
      }

      if (!sameType(existing.type, type)) {
        findings.push(
          contractsFinding(
            contractsFindingIds.conflictingDimension,
            `slot "{${name}}" is declared at type ${typeExpression(type)} in "${entry.skeleton}" but already at ${typeExpression(existing.type)} in "${existing.label}" — the first declaration wins (ambiguity is loud, L2)`,
            parent,
            "behavior.exampleSpace",
          ),
        );
      }
    }
  }

  return {
    parent,
    dimensions,
    bySkeleton,
    thenEntries: vocabulary.filter((entry) => entry.phase === "then"),
  };
}

interface ExamplePointModel {
  readonly spec: string;
  /** Dimension name → bound value, in dimension order. */
  readonly point: ReadonlyMap<string, SlotScalar>;
}

/**
 * A child's bound point: the first binding per slot name across its structured entries, filtered
 * to the parent's declared dimensions — an undeclared or off-type binding warns and drops (the
 * generated artifact always compiles; the drift is named here instead).
 */
function bindPoint(
  space: SpaceModel,
  child: PrimitiveNode,
  findings: Finding[],
): ExamplePointModel {
  const bound = new Map<string, SlotScalar>();
  const flagged = new Set<string>();
  const dimensionByName = new Map(space.dimensions.map((dimension) => [dimension.name, dimension]));

  for (const entry of structuredEntriesOf(child)) {
    for (const phase of STEP_PHASES) {
      for (const text of entry[phase]) {
        for (const slot of parseSlots(text)) {
          if (slot.form !== "bound" || flagged.has(slot.name)) {
            continue;
          }

          const dimension = dimensionByName.get(slot.name);

          if (dimension === undefined) {
            // Then-vocabulary slots are outcome payload, not dimensions — a binding for one is
            // ordinary (the outcome point), so only names foreign to the whole vocabulary warn.
            if (!vocabularyDeclaresSlot(space, slot.name)) {
              findings.push(
                contractsFinding(
                  contractsFindingIds.undeclaredSlot,
                  `bound slot "{${slot.name}}" is not declared in the parent's example space ("${space.parent.id}") — the binding is dropped from the point`,
                  child,
                  "behavior.examples",
                ),
              );
              flagged.add(slot.name);
            }
            continue;
          }

          const existing = bound.get(slot.name);

          if (existing !== undefined) {
            if (existing !== slot.value) {
              findings.push(
                contractsFinding(
                  contractsFindingIds.conflictingBinding,
                  `slot "{${slot.name}}" is bound to ${valueExpression(slot.value)} after ${valueExpression(existing)} in the same example — the first binding wins (an example is one point, MD-17)`,
                  child,
                  "behavior.examples",
                ),
              );
              flagged.add(slot.name);
            }
            continue;
          }

          if (!valueFitsType(slot.value, dimension.type)) {
            findings.push(
              contractsFinding(
                contractsFindingIds.offDimensionValue,
                `slot "{${slot.name}}" binds ${valueExpression(slot.value)}, outside its declared type ${typeExpression(dimension.type)} — the binding is dropped from the point`,
                child,
                "behavior.examples",
              ),
            );
            flagged.add(slot.name);
            continue;
          }

          bound.set(slot.name, slot.value);
        }
      }
    }
  }

  const point = new Map<string, SlotScalar>();

  for (const dimension of space.dimensions) {
    const value = bound.get(dimension.name);

    if (value !== undefined) {
      point.set(dimension.name, value);
    }
  }

  return { spec: child.id, point };
}

function vocabularyDeclaresSlot(space: SpaceModel, name: string): boolean {
  for (const entry of space.bySkeleton.values()) {
    if (entry.slots.has(name)) {
      return true;
    }
  }

  return false;
}

function renderSpaceContract(space: SpaceModel, points: readonly ExamplePointModel[]): string {
  const pascal = pascalCase(space.parent.id);
  const camel = camelCase(space.parent.id);
  const lines: string[] = [];

  lines.push(GENERATED_HEADER(`the example space of ${space.parent.id}`));
  lines.push(`import type { UnspecifiedOutcome } from "${RUNNER_SPECIFIER}";`);
  lines.push("");
  lines.push(
    `/** The Outcome union — one variant per Then-vocabulary step, its \`kind\` the step's own`,
  );
  lines.push(
    ` *  skeleton text (naming an outcome IS naming an authored Then step); \`unspecified\` is`,
  );
  lines.push(` *  contributed by the runner core — the one outcome no spec ever states. */`);
  lines.push(`export type ${pascal}Outcome =`);

  for (const entry of space.thenEntries) {
    const payload = [...entry.slots]
      .map(([name, type]) => `; readonly ${name}: ${typeExpression(type)}`)
      .join("");
    lines.push(`  | { readonly kind: ${JSON.stringify(entry.skeleton)}${payload} }`);
  }

  lines.push(`  | UnspecifiedOutcome;`);
  lines.push("");
  lines.push(`/** One value per input dimension (Given/When slots) — what the oracle consumes. */`);

  if (space.dimensions.length === 0) {
    lines.push(`export type ${pascal}Conditions = Record<string, never>;`);
  } else {
    lines.push(`export interface ${pascal}Conditions {`);

    for (const dimension of space.dimensions) {
      lines.push(`  readonly ${dimension.name}: ${typeExpression(dimension.type)};`);
    }

    lines.push(`}`);
  }

  lines.push("");
  lines.push(`export interface ${pascal}Dimension {`);
  lines.push(`  readonly name: string;`);
  lines.push(`  readonly type: "number" | "string" | "boolean" | "enum";`);
  lines.push(`  readonly values?: readonly string[];`);
  lines.push(`  /** The skeleton of the vocabulary step declaring the slot. */`);
  lines.push(`  readonly label: string;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`export interface ${pascal}ExamplePoint {`);
  lines.push(`  readonly spec: string;`);
  lines.push(
    `  /** An example binds a point — possibly partial (an unused step binds nothing). */`,
  );
  lines.push(`  readonly point: Partial<${pascal}Conditions>;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`export const ${camel}Space = {`);
  lines.push(`  spec: ${JSON.stringify(space.parent.id)},`);
  lines.push(`  dimensions: [`);

  for (const dimension of space.dimensions) {
    const values =
      dimension.type.kind === "enum"
        ? `, values: [${dimension.type.values.map((value) => JSON.stringify(value)).join(", ")}]`
        : "";
    lines.push(
      `    { name: ${JSON.stringify(dimension.name)}, type: ${JSON.stringify(
        dimension.type.kind,
      )}${values}, label: ${JSON.stringify(dimension.label)} },`,
    );
  }

  lines.push(`  ] as const satisfies readonly ${pascal}Dimension[],`);
  lines.push(`  examples: [`);

  for (const example of points) {
    const entries = [...example.point]
      .map(([name, value]) => `${name}: ${valueExpression(value)}`)
      .join(", ");
    lines.push(
      `    { spec: ${JSON.stringify(example.spec)}, point: {${entries.length > 0 ? ` ${entries} ` : ""}} },`,
    );
  }

  lines.push(`  ] as const satisfies readonly ${pascal}ExamplePoint[],`);
  lines.push(`};`);

  return lines.join("\n") + "\n";
}

/* ----- the step contract ----- */

interface ContractStepModel {
  readonly kind: StepPhase;
  readonly skeleton: string;
  readonly params: ReadonlyMap<string, SlotScalar>;
}

/**
 * Bindable = the `defined`-rung executable form: at least one structured entry, every used step
 * fully bound (the concreteness law, mirrored from the floor's example/defined cell). The
 * contract derives from the **first** structured entry — an example is one point (MD-17); a
 * sibling case is a sibling example.
 */
function bindableScenario(node: PrimitiveNode): StructuredEntry | undefined {
  const entries = structuredEntriesOf(node);
  const [first] = entries;

  if (
    first === undefined ||
    first.given.length === 0 ||
    first.when.length === 0 ||
    first.then.length === 0
  ) {
    return undefined;
  }

  for (const entry of entries) {
    for (const phase of STEP_PHASES) {
      for (const text of entry[phase]) {
        if (parseSlots(text).some((slot) => slot.form !== "bound")) {
          return undefined;
        }
      }
    }
  }

  return first;
}

function buildContractSteps(
  node: PrimitiveNode,
  scenario: StructuredEntry,
  spacesByParent: ReadonlyMap<string, SpaceModel>,
  parentIds: readonly string[],
  findings: Finding[],
): readonly ContractStepModel[] {
  const steps: ContractStepModel[] = [];
  const firstParamsBySkeleton = new Map<string, ReadonlyMap<string, SlotScalar>>();

  for (const phase of STEP_PHASES) {
    for (const text of scenario[phase]) {
      const skeleton = stepSkeleton(text);
      const params = new Map<string, SlotScalar>();

      for (const slot of parseSlots(text)) {
        if (slot.form === "bound" && !params.has(slot.name)) {
          params.set(slot.name, slot.value);
        }
      }

      const first = firstParamsBySkeleton.get(skeleton);

      if (first === undefined) {
        firstParamsBySkeleton.set(skeleton, params);
        steps.push({ kind: phase, skeleton, params });
        continue;
      }

      if (!sameParams(first, params)) {
        findings.push(
          contractsFinding(
            contractsFindingIds.conflictingBinding,
            `step "${skeleton}" recurs with different bound values in one example — the first binding wins ("same words, same meaning")`,
            node,
            "behavior.examples",
          ),
        );
      }

      // Duplicate text dedupes to one handler and one params shape; every occurrence still runs.
      steps.push({ kind: phase, skeleton, params: first });
    }
  }

  // Param types come from the parent vocabulary where the skeleton matches (drift stays a tsc
  // error at the declared type); a value outside the declared type widens to its scalar kind so
  // the generated module always compiles — the off-dimension finding named the drift already.
  for (const step of steps) {
    const vocabularyEntry = resolveVocabularyEntry(step.skeleton, spacesByParent, parentIds);

    if (vocabularyEntry === undefined) {
      continue;
    }

    for (const [name, value] of step.params) {
      const declared = vocabularyEntry.slots.get(name);

      if (declared !== undefined && !valueFitsType(value, declared)) {
        findings.push(
          contractsFinding(
            contractsFindingIds.offDimensionValue,
            `step "${step.skeleton}" binds "{${name}}" to ${valueExpression(value)}, outside its declared type ${typeExpression(declared)} — the contract widens the slot to ${scalarKind(value)}`,
            node,
            "behavior.examples",
          ),
        );
      }
    }
  }

  return steps;
}

function sameParams(
  left: ReadonlyMap<string, SlotScalar>,
  right: ReadonlyMap<string, SlotScalar>,
): boolean {
  if (left.size !== right.size) {
    return false;
  }

  for (const [name, value] of left) {
    if (right.get(name) !== value) {
      return false;
    }
  }

  return true;
}

function resolveVocabularyEntry(
  skeleton: string,
  spacesByParent: ReadonlyMap<string, SpaceModel>,
  parentIds: readonly string[],
): VocabularyEntry | undefined {
  for (const parentId of parentIds) {
    const entry = spacesByParent.get(parentId)?.bySkeleton.get(skeleton);

    if (entry !== undefined) {
      return entry;
    }
  }

  return undefined;
}

function paramTypeExpression(
  step: ContractStepModel,
  vocabularyEntry: VocabularyEntry | undefined,
): string {
  if (step.params.size === 0) {
    return "Record<string, never>";
  }

  const fields = [...step.params]
    .map(([name, value]) => {
      const declared = vocabularyEntry?.slots.get(name);
      const type =
        declared !== undefined && valueFitsType(value, declared)
          ? typeExpression(declared)
          : scalarKind(value);

      return `readonly ${name}: ${type}`;
    })
    .join("; ");

  return `{ ${fields} }`;
}

function renderStepContract(
  node: PrimitiveNode,
  steps: readonly ContractStepModel[],
  spacesByParent: ReadonlyMap<string, SpaceModel>,
  parentIds: readonly string[],
): string {
  const camel = camelCase(node.id);
  const uniqueSkeletons: string[] = [];
  const seen = new Set<string>();

  for (const step of steps) {
    if (!seen.has(step.skeleton)) {
      seen.add(step.skeleton);
      uniqueSkeletons.push(step.skeleton);
    }
  }

  const paramsBySkeleton = new Map<string, ContractStepModel>();

  for (const step of steps) {
    if (!paramsBySkeleton.has(step.skeleton)) {
      paramsBySkeleton.set(step.skeleton, step);
    }
  }

  const lines: string[] = [];
  lines.push(GENERATED_HEADER(`the step contract of ${node.id}`));
  lines.push(`import type { ExampleContract } from "${RUNNER_SPECIFIER}";`);
  lines.push("");
  lines.push(
    `export type Step =\n${uniqueSkeletons.map((skeleton) => `  | ${JSON.stringify(skeleton)}`).join("\n")};`,
  );
  lines.push("");
  lines.push(`export type StepParams = {`);

  for (const skeleton of uniqueSkeletons) {
    const step = paramsBySkeleton.get(skeleton);

    if (step === undefined) {
      continue;
    }

    const vocabularyEntry = resolveVocabularyEntry(skeleton, spacesByParent, parentIds);
    lines.push(
      `  readonly ${JSON.stringify(skeleton)}: ${paramTypeExpression(step, vocabularyEntry)};`,
    );
  }

  lines.push(`};`);
  lines.push("");
  lines.push(`export const ${camel}Contract: ExampleContract<Step, StepParams> = {`);
  lines.push(`  spec: ${JSON.stringify(node.id)},`);
  lines.push(`  title: ${JSON.stringify(node.title ?? node.id)},`);
  lines.push(`  steps: [`);

  for (const step of steps) {
    const params = [...step.params]
      .map(([name, value]) => `${name}: ${valueExpression(value)}`)
      .join(", ");
    lines.push(
      `    { kind: ${JSON.stringify(step.kind)}, text: ${JSON.stringify(step.skeleton)}, params: {${
        params.length > 0 ? ` ${params} ` : ""
      }} },`,
    );
  }

  lines.push(`  ],`);
  lines.push(`};`);

  return lines.join("\n") + "\n";
}

/* ----- the stage ----- */

export function generateContracts(graph: GraphSchema): GeneratedContracts {
  const findings: Finding[] = [];
  const primitives = new Map<string, PrimitiveNode>();

  for (const node of graph.nodes) {
    if (node.nodeType === "Primitive" && !primitives.has(node.id)) {
      primitives.set(node.id, node);
    }
  }

  // Declared refines edges, both directions: children resolve their vocabulary through them,
  // spaces collect their children's points through them.
  const parentsByChild = new Map<string, string[]>();
  const childrenByParent = new Map<string, string[]>();

  for (const edge of graph.edges) {
    if (edge.type !== "refines" || edge.claim !== "declared") {
      continue;
    }

    if (primitives.has(edge.from) && primitives.has(edge.to)) {
      parentsByChild.set(edge.from, [...(parentsByChild.get(edge.from) ?? []), edge.to]);
      childrenByParent.set(edge.to, [...(childrenByParent.get(edge.to) ?? []), edge.from]);
    }
  }

  const sortedIds = [...primitives.keys()].sort((left, right) =>
    left < right ? -1 : left > right ? 1 : 0,
  );
  const spacesByParent = new Map<string, SpaceModel>();

  for (const id of sortedIds) {
    const node = primitives.get(id);

    if (node === undefined) {
      continue;
    }

    const vocabulary = vocabularyOf(node);

    if (vocabulary !== undefined) {
      spacesByParent.set(id, buildSpaceModel(node, vocabulary, findings));
    }
  }

  const files = new Map<string, string>();

  for (const [parentId, space] of spacesByParent) {
    const childIds = [...(childrenByParent.get(parentId) ?? [])].sort((left, right) =>
      left < right ? -1 : left > right ? 1 : 0,
    );
    const points: ExamplePointModel[] = [];

    for (const childId of childIds) {
      const child = primitives.get(childId);

      if (child?.specKind === "example" && structuredEntriesOf(child).length > 0) {
        points.push(bindPoint(space, child, findings));
      }
    }

    files.set(`${idPath(parentId)}.space.ts`, renderSpaceContract(space, points));
  }

  for (const id of sortedIds) {
    const node = primitives.get(id);

    if (node?.specKind !== "example") {
      continue;
    }

    const scenario = bindableScenario(node);

    if (scenario === undefined) {
      continue;
    }

    const parentIds = [...(parentsByChild.get(id) ?? [])].sort((left, right) =>
      left < right ? -1 : left > right ? 1 : 0,
    );
    const steps = buildContractSteps(node, scenario, spacesByParent, parentIds, findings);
    files.set(
      `${idPath(id)}.contract.ts`,
      renderStepContract(node, steps, spacesByParent, parentIds),
    );
  }

  const sortedFiles = new Map(
    [...files.entries()].sort(([left], [right]) => (left < right ? -1 : 1)),
  );

  return { files: sortedFiles, findings };
}
