// The authored anchor nodes, independent of their zero-to-many binding edges.
// `constant` names a constant-form declaration; its absence selects the comment block. `site`
// names the code it binds, so the
// suite can resolve both lines in the real file rather than trusting a transcribed line number.
// A site written as a bare `register<Example>(` call marks an adopted generated registrar: the
// suite resolves it as an executable top-level call through the TypeScript AST, so a comment or
// string literal can never satisfy the locality invariant.

export interface ExpectedAnchor {
  readonly id: string;
  readonly nodeType: "Anchor" | "CodeNode";
  readonly label: string;
  readonly file: string;
  readonly constant?: string;
  readonly site: string;
  readonly role?: string;
  readonly layer?: string;
  readonly context?: string;
}

// re-measured under plan 40
export const expectedAnchors: readonly ExpectedAnchor[] = [
  {
    id: "test:protocol.open-section-order",
    nodeType: "Anchor",
    label: "verifies serialized authored entry order",
    file: "test/graph-schema.test.ts",
    constant: "openSectionOrderTestAnchor",
    site: 'it("serializes authored entry order',
  },
  {
    id: "impl:protocol.open-section-order",
    nodeType: "CodeNode",
    label: "preserves authored open-section and model-term order",
    file: "src/extract/serialize.ts",
    constant: "openSectionOrderAnchor",
    site: "function canonicalDynamicSection",
    role: "codec",
  },
  {
    id: "component:protocol.model",
    nodeType: "CodeNode",
    label: "Protocol model seam",
    file: "src/model/anchors.ts",
    constant: "modelComponentAnchor",
    site: "const anchorModelAnchor",
    layer: "domain",
    context: "protocol",
  },
  {
    id: "component:protocol.extract",
    nodeType: "CodeNode",
    label: "Protocol extraction seam",
    file: "src/extract/index.ts",
    constant: "extractComponentAnchor",
    site: "export const extractAnchor",
    layer: "application",
    context: "protocol",
  },
  {
    id: "component:protocol.graph",
    nodeType: "CodeNode",
    label: "Protocol graph seam",
    file: "src/graph/schema.ts",
    constant: "graphComponentAnchor",
    site: "const graphClaimsAnchor",
    layer: "domain",
    context: "protocol",
  },
  {
    id: "component:protocol.validate",
    nodeType: "CodeNode",
    label: "Protocol validation seam",
    file: "src/validate/validators.ts",
    constant: "validateComponentAnchor",
    site: "const validationFamiliesAnchor",
    layer: "domain",
    context: "protocol",
  },
  {
    id: "component:protocol.reader",
    nodeType: "CodeNode",
    label: "Protocol reader seam",
    file: "src/reader/reader.ts",
    site: "export function createReader",
    layer: "application",
    context: "protocol",
  },
  {
    id: "component:protocol.projections",
    nodeType: "CodeNode",
    label: "Protocol projections seam",
    file: "src/projections/design-review.ts",
    site: "export function renderDesignReview",
    layer: "edge",
    context: "protocol",
  },
  {
    id: "component:protocol.cli",
    nodeType: "CodeNode",
    label: "Protocol CLI seam",
    file: "src/cli/build-command.ts",
    constant: "cliComponentAnchor",
    site: "export interface BuildHooks",
    layer: "edge",
    context: "protocol",
  },
  {
    id: "component:protocol.runner",
    nodeType: "CodeNode",
    label: "Protocol example runner seam",
    file: "src/runner/index.ts",
    constant: "runnerComponentAnchor",
    site: "const exampleRunnerAnchor",
    layer: "application",
    context: "protocol",
  },
  {
    id: "component:protocol.codegen",
    nodeType: "CodeNode",
    label: "Protocol runnable code generation seam",
    file: "src/codegen/contracts.ts",
    constant: "codegenComponentAnchor",
    site: "const runnableModulesAnchor",
    layer: "application",
    context: "protocol",
  },
  {
    id: "component:protocol.notation",
    nodeType: "CodeNode",
    label: "Protocol slot notation seam",
    file: "src/notation/slots.ts",
    constant: "notationComponentAnchor",
    site: "const slotNotationAnchor",
    layer: "domain",
    context: "protocol",
  },
  {
    id: "component:protocol.adapters",
    nodeType: "CodeNode",
    label: "Protocol Vitest adapter seam",
    file: "src/adapters/vitest.ts",
    constant: "adaptersComponentAnchor",
    site: "const exampleRunnerAdapterAnchor",
    layer: "adapter",
    context: "protocol",
  },
  {
    id: "component:protocol.import",
    nodeType: "CodeNode",
    label: "Protocol import seam",
    file: "src/import/import.ts",
    constant: "importComponentAnchor",
    site: "const sdpImportCoreAnchor",
    layer: "application",
    context: "protocol",
  },
  {
    id: "component:protocol.testing",
    nodeType: "CodeNode",
    label: "Protocol testing seam",
    file: "src/testing/index.ts",
    constant: "testingComponentAnchor",
    site: "const exampleTestingHelpersAnchor",
    layer: "adapter",
    context: "protocol",
  },
  {
    id: "impl:protocol.extract",
    nodeType: "CodeNode",
    label: "extracts authored carriers and bindings into one graph",
    file: "src/extract/index.ts",
    constant: "extractAnchor",
    site: "export function extract",
    role: "extractor",
  },
  {
    id: "impl:protocol.derive-graph",
    nodeType: "CodeNode",
    label: "derives the graph from reified carriers and bindings",
    file: "src/extract/derive.ts",
    constant: "deriveGraphAnchor",
    site: "export function deriveGraph",
    role: "extractor",
  },
  {
    id: "test:protocol.extract",
    nodeType: "Anchor",
    label: "extraction contracts verify graph derivation",
    file: "test/extract.test.ts",
    constant: "extractContractTestAnchor",
    site: 'describe("anchor extraction corpora",',
  },
  {
    id: "test:protocol.delivery-facts",
    nodeType: "Anchor",
    label: "verifies the delivery-fact conferral ladder and fail-closed posture",
    file: "test/extract.test.ts",
    constant: "deliveryFactsTestAnchor",
    site: 'it("anchored-binding: the full ladder',
  },
  {
    id: "test:protocol.structural-self-binding",
    nodeType: "Anchor",
    label: "verifies the accepted significant-unit set carries its declared membership",
    file: "test/self-hosting-graph.test.ts",
    constant: "structuralSelfBindingTestAnchor",
    site: "void structuralSelfBindingTestAnchor",
  },
  {
    id: "test:protocol.extraction-determinism",
    nodeType: "Anchor",
    label: "clean-repo pipeline determinism verifies byte-identical output",
    file: "test/cli.test.ts",
    constant: "cleanRepoDeterminismTestAnchor",
    site: 'it("clean-repo determinism: the full pipeline at a different absolute path is byte-identical"',
  },
  {
    id: "test:protocol.build-pipeline.same-invocation",
    nodeType: "Anchor",
    label: "the same-invocation point verifies the query extraction and validation seam",
    file: "test/self-hosting-extraction.test.ts",
    constant: "buildPipelineSameInvocationTestAnchor",
    site: "registerSameInvocation(",
  },
  {
    id: "impl:protocol.authoring-on-ramp",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped graph-first authoring skill document",
    file: "test/skills.test.ts",
    constant: "authoringOnRampImplementationAnchor",
    site: "function readSkill",
  },
  {
    id: "impl:protocol.delivery-session-on-ramp",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped advisory delivery-session skill document",
    file: "test/skills.test.ts",
    constant: "deliverySessionOnRampImplementationAnchor",
    site: "function readSkill",
  },
  {
    id: "impl:protocol.authoring-recipes",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped authoring recipe catalog",
    file: "test/skills.test.ts",
    constant: "authoringRecipesImplementationAnchor",
    site: "function documentedCommands",
  },
  {
    id: "test:protocol.authoring-on-ramp",
    nodeType: "Anchor",
    label: "skill-asset checks verify the authoring on-ramp",
    file: "test/skills.test.ts",
    constant: "authoringOnRampTestAnchor",
    site: 'describe("Protocol skill assets"',
  },
  {
    id: "test:protocol.delivery-session-on-ramp",
    nodeType: "Anchor",
    label: "skill-asset checks verify advisory delivery-session routing",
    file: "test/skills.test.ts",
    constant: "deliverySessionOnRampTestAnchor",
    site: 'describe("Protocol skill assets"',
  },
  {
    id: "test:protocol.authoring-recipes",
    nodeType: "Anchor",
    label: "skill-asset checks verify the authoring recipes",
    file: "test/skills.test.ts",
    constant: "authoringRecipesTestAnchor",
    site: 'describe("Protocol skill assets"',
  },
  {
    id: "impl:protocol.readiness-floor",
    nodeType: "CodeNode",
    label: "evaluates the stated readiness floor against the graph",
    file: "src/validate/readiness-floor.ts",
    constant: "readinessFloorAnchor",
    site: "export function evaluateReadinessFloor",
    role: "validator",
  },
  {
    id: "test:protocol.readiness-floor",
    nodeType: "Anchor",
    label: "readiness-floor contracts verify stated maturity",
    file: "test/readiness.test.ts",
    constant: "readinessFloorTestAnchor",
    site: 'describe("readiness and validation contracts",',
  },
  {
    id: "impl:protocol.markdown-authoring",
    nodeType: "CodeNode",
    label: "reifies Markdown authoring into the one carrier path",
    file: "src/extract/markdown.ts",
    constant: "markdownAuthoringAnchor",
    site: "export function reifyMarkdownCarrier",
    role: "extractor",
  },
  {
    id: "impl:protocol.gherkin-authoring",
    nodeType: "CodeNode",
    label: "reifies Gherkin behavior and example authoring into the one carrier path",
    file: "src/extract/gherkin.ts",
    constant: "gherkinAuthoringAnchor",
    site: "export function reifyGherkinCarrier",
    role: "extractor",
  },
  {
    id: "impl:protocol.markdown-parser",
    nodeType: "CodeNode",
    label: "reifies the ruled Markdown parser input",
    file: "src/extract/markdown.ts",
    constant: "markdownParserAnchor",
    site: "export function reifyMarkdownCarrier",
    role: "extractor",
  },
  {
    id: "test:protocol.markdown-parser",
    nodeType: "Anchor",
    label: "Markdown reifier tests verify the ruled parser",
    file: "test/markdown-reifier.test.ts",
    constant: "markdownParserTestAnchor",
    site: 'describe("Markdown frontmatter reifier",',
  },
  {
    id: "impl:protocol.envelope-contract",
    nodeType: "CodeNode",
    label: "parses the bounded Markdown frontmatter envelope",
    file: "src/extract/markdown.ts",
    constant: "envelopeContractAnchor",
    site: "export function parseMarkdownFrontmatter",
    role: "codec",
  },
  {
    id: "test:protocol.envelope-contract",
    nodeType: "Anchor",
    label: "frontmatter contract tests verify the Markdown envelope",
    file: "test/markdown-reifier.test.ts",
    constant: "envelopeContractTestAnchor",
    site: 'describe("Markdown frontmatter reifier",',
  },
  {
    id: "impl:protocol.prose-ownership",
    nodeType: "CodeNode",
    label: "reads Markdown body content through its prose owners",
    file: "src/extract/markdown.ts",
    constant: "proseOwnershipAnchor",
    site: "export function readMarkdownBody",
    role: "codec",
  },
  {
    id: "test:protocol.prose-ownership",
    nodeType: "Anchor",
    label: "Markdown reifier tests verify prose ownership",
    file: "test/markdown-reifier.test.ts",
    constant: "proseOwnershipTestAnchor",
    site: 'describe("Markdown frontmatter reifier",',
  },
  {
    id: "impl:protocol.duplicate-id-exclusion",
    nodeType: "CodeNode",
    label: "excludes duplicated carrier ids from the graph",
    file: "src/extract/index.ts",
    constant: "duplicateIdExclusionAnchor",
    site: "function findDuplicatedIds",
    role: "validator",
  },
  {
    id: "test:protocol.duplicate-ids.dual-carrier",
    nodeType: "Anchor",
    label: "dual-carrier duplicate-ID contract verifies carrier exclusion",
    file: "test/self-hosting-duplicate-ids.test.ts",
    constant: "dualCarrierDuplicateTestAnchor",
    site: "registerDualCarrier(",
  },
  {
    id: "test:protocol.warn-level-signals.orphan-signal",
    nodeType: "Anchor",
    label: "the orphan point verifies the disconnected-spec warning",
    file: "test/self-hosting-validators.test.ts",
    constant: "warnLevelOrphanTestAnchor",
    site: "registerOrphanSignal(",
  },
  {
    id: "test:protocol.warn-level-signals.ready-gap-signal",
    nodeType: "Anchor",
    label: "the gap point verifies the unverified-ready warning",
    file: "test/self-hosting-validators.test.ts",
    constant: "warnLevelGapTestAnchor",
    site: "registerReadyGapSignal(",
  },
  {
    id: "test:protocol.readiness-floor.unrelated-scoped-spec",
    nodeType: "Anchor",
    label: "the unrelated-scoped point verifies the relation clause of the scoped rung",
    file: "test/self-hosting-validators.test.ts",
    constant: "unrelatedScopedSpecTestAnchor",
    site: "registerUnrelatedScopedSpec(",
  },
  {
    id: "test:protocol.readiness-floor.blocking-open-question",
    nodeType: "Anchor",
    label: "the blocked-question point verifies the open-questions clause of the defined rung",
    file: "test/self-hosting-validators.test.ts",
    constant: "blockingOpenQuestionTestAnchor",
    site: "registerBlockingOpenQuestion(",
  },
  {
    id: "test:protocol.kind-evidence.constraints-alone",
    nodeType: "Anchor",
    label: "the constraints-alone point verifies the behavior-family complete cell",
    file: "test/self-hosting-validators.test.ts",
    constant: "constraintsAloneTestAnchor",
    site: "registerConstraintsAlone(",
  },
  {
    id: "test:protocol.kind-evidence.untargeted-constraint",
    nodeType: "Anchor",
    label: "the untargeted-constraint point verifies the constraint row's target requirement",
    file: "test/self-hosting-validators.test.ts",
    constant: "untargetedConstraintTestAnchor",
    site: "registerUntargetedConstraint(",
  },
  {
    id: "test:protocol.kind-evidence.empty-promoted-child",
    nodeType: "Anchor",
    label: "the empty-promotion point verifies the promoted-evidence honesty bound",
    file: "test/self-hosting-validators.test.ts",
    constant: "emptyPromotedChildTestAnchor",
    site: "registerEmptyPromotedChild(",
  },
  {
    id: "test:protocol.referential-integrity.dangling-target",
    nodeType: "Anchor",
    label: "the dangling-target point verifies the unresolved-reference error",
    file: "test/self-hosting-validators.test.ts",
    constant: "danglingTargetTestAnchor",
    site: "registerDanglingTarget(",
  },
  {
    id: "test:protocol.referential-integrity.did-you-mean",
    nodeType: "Anchor",
    label: "the near-miss point verifies the unique did-you-mean suggestion",
    file: "test/self-hosting-validators.test.ts",
    constant: "didYouMeanTestAnchor",
    site: "registerDidYouMean(",
  },
  {
    id: "test:protocol.authored-honesty.section-authored-fact",
    nodeType: "Anchor",
    label: "the section point verifies the authoring-shape refusal",
    file: "test/self-hosting-validators.test.ts",
    constant: "sectionAuthoredFactTestAnchor",
    site: "registerSectionAuthoredFact(",
  },
  {
    id: "test:protocol.authored-honesty.unearned-stated-fact",
    nodeType: "Anchor",
    label: "the stated-fact point verifies the delivery-fact refusal",
    file: "test/self-hosting-validators.test.ts",
    constant: "unearnedStatedFactTestAnchor",
    site: "registerUnearnedStatedFact(",
  },
  {
    id: "test:protocol.claim-separation.collapsed-edge-claim",
    nodeType: "Anchor",
    label: "the collapsed-claim point verifies the binding-edge contract row",
    file: "test/self-hosting-validators.test.ts",
    constant: "collapsedEdgeClaimTestAnchor",
    site: "registerCollapsedEdgeClaim(",
  },
  {
    id: "test:protocol.claim-separation.unratified-descriptor",
    nodeType: "Anchor",
    label: "the unratified-kind point verifies the fail-closed descriptor law",
    file: "test/self-hosting-validators.test.ts",
    constant: "unratifiedDescriptorTestAnchor",
    site: "registerUnratifiedDescriptor(",
  },
  {
    id: "test:protocol.verification-linkage.unbound-example",
    nodeType: "Anchor",
    label: "the unbound-example point verifies the incomplete spec-to-test trace",
    file: "test/self-hosting-validators.test.ts",
    constant: "unboundExampleTestAnchor",
    site: "registerUnboundExample(",
  },
  {
    id: "test:protocol.verification-linkage.unresolved-oracle",
    nodeType: "Anchor",
    label: "the unresolved-oracle point verifies the oracle binding refusal",
    file: "test/self-hosting-validators.test.ts",
    constant: "unresolvedOracleTestAnchor",
    site: "registerUnresolvedOracle(",
  },
  {
    id: "test:protocol.pack-coherence.incoherent-aggregate",
    nodeType: "Anchor",
    label: "the incoherent-aggregate point verifies both halves of the pack law",
    file: "test/self-hosting-validators.test.ts",
    constant: "incoherentAggregateTestAnchor",
    site: "registerIncoherentAggregate(",
  },
  {
    id: "test:protocol.excludes.segment-boundary",
    nodeType: "Anchor",
    label: "the segment-boundary point verifies the exact-prefix exclusion rule",
    file: "test/self-hosting-extraction.test.ts",
    constant: "excludesSegmentBoundaryTestAnchor",
    site: "registerSegmentBoundary(",
  },
  {
    id: "test:protocol.excludes.refused-path",
    nodeType: "Anchor",
    label: "the refused-path point verifies the malformed-exclusion refusal",
    file: "test/self-hosting-extraction.test.ts",
    constant: "excludesRefusedPathTestAnchor",
    site: "registerRefusedPath(",
  },
  {
    id: "test:protocol.schema-versioning.declared-version",
    nodeType: "Anchor",
    label: "the declared-version point verifies the readable payload version",
    file: "test/self-hosting-extraction.test.ts",
    constant: "schemaVersioningTestAnchor",
    site: "registerDeclaredVersion(",
  },
  {
    id: "test:protocol.stable-ids.namespaced-round-trip",
    nodeType: "Anchor",
    label: "the round-trip point verifies the namespaced dotted-path grammar",
    file: "test/self-hosting-model.test.ts",
    constant: "namespacedRoundTripTestAnchor",
    site: "registerNamespacedRoundTrip(",
  },
  {
    id: "test:protocol.stable-ids.malformed-refusal",
    nodeType: "Anchor",
    label: "the malformed point verifies the lowercase-namespace refusal",
    file: "test/self-hosting-model.test.ts",
    constant: "malformedRefusalTestAnchor",
    site: "registerMalformedRefusal(",
  },
  {
    id: "test:protocol.stable-ids.unsectioned-address-refused",
    nodeType: "Anchor",
    label: "the unsectioned point verifies the entry-address section refusal",
    file: "test/self-hosting-model.test.ts",
    constant: "unsectionedAddressRefusedTestAnchor",
    site: "registerUnsectionedAddressRefused(",
  },
  {
    id: "test:protocol.markdown-parser.bounded-parity",
    nodeType: "Anchor",
    label: "the bounded-parity point verifies one shared finding class and its split outcomes",
    file: "test/self-hosting-carrier.test.ts",
    constant: "boundedParityTestAnchor",
    site: "registerBoundedParity(",
  },
  {
    id: "test:protocol.gherkin-authoring.authored-fact-refused",
    nodeType: "Anchor",
    label: "the authored-fact-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "authoredFactRefusedAnchor",
    site: "registerAuthoredFactRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.contract-parity",
    nodeType: "Anchor",
    label: "the contract-parity point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "contractParityAnchor",
    site: "bindExample(contractParityContract",
  },
  {
    id: "test:protocol.gherkin-authoring.duplicate-surface-refused",
    nodeType: "Anchor",
    label: "the duplicate-surface-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "duplicateSurfaceRefusedAnchor",
    site: "registerDuplicateSurfaceRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.example-space-extraction",
    nodeType: "Anchor",
    label: "the example-space-extraction point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "exampleSpaceExtractionAnchor",
    site: "registerExampleSpaceExtraction(",
  },
  {
    id: "test:protocol.gherkin-authoring.malformed-relation-refused",
    nodeType: "Anchor",
    label: "the malformed-relation-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "malformedRelationRefusedAnchor",
    site: "registerMalformedRelationRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.missing-id-refused",
    nodeType: "Anchor",
    label: "the missing-id-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "missingIdRefusedAnchor",
    site: "registerMissingIdRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.parent-child-extraction",
    nodeType: "Anchor",
    label: "the parent-child-extraction point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "parentChildExtractionAnchor",
    site: "registerParentChildExtraction(",
  },
  {
    id: "test:protocol.gherkin-authoring.unbound-ready-refused",
    nodeType: "Anchor",
    label: "the unbound-ready-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "unboundReadyRefusedAnchor",
    site: "bindExample(unboundReadyRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.unknown-tag-refused",
    nodeType: "Anchor",
    label: "the unknown-tag-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "unknownTagRefusedAnchor",
    site: "registerUnknownTagRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.unsupported-construct-refused",
    nodeType: "Anchor",
    label: "the unsupported-construct-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "unsupportedConstructRefusedAnchor",
    site: "registerUnsupportedConstructRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.description-location-refused",
    nodeType: "Anchor",
    label: "the description-location-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "descriptionLocationRefusedAnchor",
    site: "registerDescriptionLocationRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.step-less-scenario-refused",
    nodeType: "Anchor",
    label: "the step-less-scenario-refused point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "stepLessScenarioRefusedAnchor",
    site: "registerStepLessScenarioRefused(",
  },
  {
    id: "test:protocol.gherkin-authoring.multi-finding-bounded",
    nodeType: "Anchor",
    label: "the multi-finding-bounded point verifies the Gherkin carrier contract",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "multiFindingBoundedAnchor",
    site: "registerMultiFindingBounded(",
  },
  {
    id: "test:protocol.sdp-import.round-trip",
    nodeType: "Anchor",
    label: "TypeScript import round-trip contract preserves authored data",
    file: "test/self-hosting-sdp-import.test.ts",
    constant: "sdpImportRoundTripTestAnchor",
    site: "registerRoundTrip(",
  },
  {
    id: "impl:protocol.anchor-extraction",
    nodeType: "CodeNode",
    label: "anchor reification seam: the constant form and the comment form",
    file: "src/extract/anchors.ts",
    constant: "anchorExtractionAnchor",
    site: "export interface ReifiedAnchor",
    role: "extractor",
  },
  {
    id: "impl:protocol.anchor-model",
    nodeType: "CodeNode",
    label: "binding-only anchor model builders",
    file: "src/model/anchors.ts",
    constant: "anchorModelAnchor",
    site: "export function specTest",
    role: "contract",
  },
  {
    id: "impl:protocol.pack-aggregate",
    nodeType: "CodeNode",
    label: "Pack aggregate and model references",
    file: "src/model/pack.ts",
    constant: "packAggregateAnchor",
    site: "export function pack",
    role: "contract",
  },
  {
    id: "impl:protocol.spec-descriptors",
    nodeType: "CodeNode",
    label: "Spec kind, altitude, and readiness coordinates",
    file: "src/model/descriptors.ts",
    constant: "specDescriptorsAnchor",
    site: "export const SPEC_KIND_DISPLAY_LABELS",
    role: "contract",
  },
  {
    id: "impl:protocol.spec-primitive",
    nodeType: "CodeNode",
    label: "Spec envelope and enrich-in-place shape",
    file: "src/model/spec.ts",
    constant: "specPrimitiveAnchor",
    site: "export function spec",
    role: "contract",
  },
  {
    id: "impl:protocol.spec-relations",
    nodeType: "CodeNode",
    label: "declared Spec relation builders",
    file: "src/model/relations.ts",
    constant: "specRelationsAnchor",
    site: "export function supersedes",
    role: "contract",
  },
  {
    id: "impl:protocol.spec-sections",
    nodeType: "CodeNode",
    label: "typed Spec section shapes",
    file: "src/model/sections.ts",
    constant: "specSectionsAnchor",
    site: "export interface SpecSections",
    role: "contract",
  },
  {
    id: "impl:protocol.stable-ids",
    nodeType: "CodeNode",
    label: "stable ID grammar parser",
    file: "src/ids.ts",
    constant: "stableIdsAnchor",
    site: "export function parseId",
    role: "codec",
  },
  {
    id: "impl:protocol.verifier-semantics",
    nodeType: "CodeNode",
    label: "readiness clauses over direct verification bindings",
    file: "src/validate/readiness-floor.ts",
    constant: "verifierSemanticsAnchor",
    site: "export function evaluateReadinessFloor",
    role: "validator",
  },
  {
    id: "impl:protocol.validation-families",
    nodeType: "CodeNode",
    label: "conformance and honesty validator registry",
    file: "src/validate/validators.ts",
    constant: "validationFamiliesAnchor",
    site: "export const graphValidatorIds",
    role: "contract",
  },
  {
    id: "impl:protocol.projections-model",
    nodeType: "CodeNode",
    label: "pure generated projection page contract",
    file: "src/projections/design-review.ts",
    site: "export interface DesignReviewPage",
    role: "contract",
  },
  {
    id: "impl:protocol.agent-surface",
    nodeType: "CodeNode",
    label: "typed graph reader and agent entry adapters",
    file: "src/reader/reader.ts",
    site: "export function createReader",
    role: "reader",
  },
  {
    id: "impl:protocol.reader-impact",
    nodeType: "CodeNode",
    label: "file-level reader blast-radius contract",
    file: "src/reader/reader.ts",
    site: "export interface BlastRadius",
    role: "contract",
  },
  {
    id: "impl:protocol.reader",
    nodeType: "CodeNode",
    label: "thin typed graph reader construction",
    file: "src/reader/reader.ts",
    site: "export function createReader",
    role: "reader",
  },
  {
    id: "impl:protocol.design-review",
    nodeType: "CodeNode",
    label: "renders the contextual Design Review projection",
    file: "src/projections/design-review.ts",
    site: "export function renderDesignReview",
    role: "projection",
  },
  {
    id: "impl:protocol.census-page",
    nodeType: "CodeNode",
    label: "renders the derived census and runtime taxonomy projection",
    file: "src/projections/census.ts",
    site: "function compareCodeUnits",
    role: "projection",
  },
  {
    id: "impl:protocol.mermaid-view",
    nodeType: "CodeNode",
    label: "renders bounded Spec one-hop and Pack membership diagrams",
    file: "src/projections/mermaid.ts",
    site: "function compareCodeUnits",
    role: "projection",
  },
  {
    id: "impl:protocol.gherkin-view",
    nodeType: "CodeNode",
    label: "renders a generated Gherkin-shaped READ projection of any Spec",
    file: "src/projections/gherkin-view.ts",
    site: "const CANONICAL_KINDS",
    role: "projection",
  },
  {
    id: "test:protocol.gherkin-view",
    nodeType: "Anchor",
    label: "verifies the generated Gherkin-shaped READ projection",
    file: "test/gherkin-view.test.ts",
    constant: "gherkinViewTestAnchor",
    site: "const checkoutRoot",
  },
  {
    id: "impl:protocol.exclusion-surface",
    nodeType: "CodeNode",
    label: "strict root-relative exclusion input for both extraction surfaces",
    file: "src/extract/index.ts",
    constant: "exclusionSurfaceAnchor",
    site: "export interface ExtractOptions",
    role: "contract",
  },
  {
    id: "impl:protocol.graph-claims",
    nodeType: "CodeNode",
    label: "declares the graph claim taxonomy",
    file: "src/graph/schema.ts",
    constant: "graphClaimsAnchor",
    site: "export const graphClaims",
    role: "contract",
  },
  {
    id: "impl:protocol.regenerability",
    nodeType: "CodeNode",
    label: "repeats graph and contract producers for deterministic regeneration",
    file: "src/cli/build-command.ts",
    constant: "regenerabilityAnchor",
    site: "export function runBuild",
    role: "service",
  },
  {
    id: "impl:protocol.schema-version",
    nodeType: "CodeNode",
    label: "declares the graph schema version",
    file: "src/graph/schema.ts",
    constant: "schemaVersionAnchor",
    site: "export const schemaVersion",
    role: "contract",
  },
  {
    id: "impl:protocol.executable-contracts",
    nodeType: "CodeNode",
    label: "derives step and example-space contracts from the graph",
    file: "src/codegen/contracts.ts",
    constant: "executableContractsAnchor",
    site: "export function generateContracts",
    role: "projection",
  },
  {
    id: "impl:protocol.example-runner",
    nodeType: "CodeNode",
    label: "plans and executes a bound example against the caller's world",
    file: "src/runner/index.ts",
    constant: "exampleRunnerAnchor",
    site: "export function planExample",
    role: "service",
  },
  {
    id: "impl:protocol.slot-notation",
    nodeType: "CodeNode",
    label: "parses slot groups and normalizes a step to its skeleton",
    file: "src/notation/slots.ts",
    constant: "slotNotationAnchor",
    site: "export function parseSlots",
    role: "codec",
  },
  {
    id: "test:protocol.executable-contracts.concreteness-refusal",
    nodeType: "Anchor",
    label: "the concreteness point verifies the unbound-slot refusal",
    file: "test/self-hosting-extraction.test.ts",
    constant: "concretenessRefusalTestAnchor",
    site: "bindExample(concretenessRefusalContract",
  },
  {
    id: "test:protocol.executable-contracts.multi-entry-example",
    nodeType: "Anchor",
    label: "the multi-entry point verifies the named second entry",
    file: "test/self-hosting-extraction.test.ts",
    constant: "multiEntryExampleTestAnchor",
    site: "bindExample(multiEntryExampleContract",
  },
  {
    id: "test:protocol.executable-contracts.case-colliding-path",
    nodeType: "Anchor",
    label: "the collision point verifies the all-or-nothing withholding",
    file: "test/self-hosting-extraction.test.ts",
    constant: "caseCollidingPathTestAnchor",
    site: "bindExample(caseCollidingPathContract",
  },
  {
    id: "test:protocol.example-runner.step-order",
    nodeType: "Anchor",
    label: "the step-order point verifies contract order and the one handler per step",
    file: "test/self-hosting-extraction.test.ts",
    constant: "exampleRunnerStepOrderTestAnchor",
    site: "bindExample(stepOrderContract",
  },
  {
    id: "test:protocol.example-runner.red-step-naming",
    nodeType: "Anchor",
    label: "the red-step point verifies the self-naming failure law",
    file: "test/self-hosting-extraction.test.ts",
    constant: "exampleRunnerRedStepTestAnchor",
    site: "registerRedStepNaming(",
  },
  {
    id: "test:protocol.slot-notation.typed-declaration",
    nodeType: "Anchor",
    label: "the declaration point verifies the typed form and its skeleton",
    file: "test/self-hosting-carrier.test.ts",
    constant: "slotNotationTypedTestAnchor",
    site: "registerTypedDeclaration(",
  },
  {
    id: "test:protocol.slot-notation.refused-guess",
    nodeType: "Anchor",
    label: "the refusal point verifies prose braces and the unusable slot",
    file: "test/self-hosting-carrier.test.ts",
    constant: "slotNotationRefusedTestAnchor",
    site: "registerRefusedGuess(",
  },
  {
    id: "test:protocol.anchors.lookalike-refusal",
    nodeType: "Anchor",
    label: "the lookalike point verifies that a consumer-local builder mints nothing",
    file: "test/self-hosting-model.test.ts",
    constant: "lookalikeRefusalTestAnchor",
    site: "registerLookalikeRefusal(",
  },
  {
    id: "test:protocol.anchors.physical-identity",
    nodeType: "Anchor",
    label: "the physical-identity point verifies the resolved relative builder import",
    file: "test/self-hosting-model.test.ts",
    constant: "physicalIdentityTestAnchor",
    site: "registerPhysicalIdentity(",
  },
  {
    id: "test:protocol.two-check-families.split-report",
    nodeType: "Anchor",
    label: "the split-report point verifies both families in one aggregate report",
    file: "test/self-hosting-validators.test.ts",
    constant: "splitReportTestAnchor",
    site: "registerSplitReport(",
  },
  {
    id: "test:protocol.derived-readiness-banner.dishonest-divergence",
    nodeType: "Anchor",
    label: "the overstated-rung point verifies the banner and its first unmet clause",
    file: "test/self-hosting-projections.test.ts",
    constant: "dishonestDivergenceTestAnchor",
    site: "registerDishonestDivergence(",
  },
  {
    id: "test:protocol.derived-readiness-banner.honest-headroom",
    nodeType: "Anchor",
    label: "the understated-rung point verifies the one-direction bound on the banner",
    file: "test/self-hosting-projections.test.ts",
    constant: "honestHeadroomTestAnchor",
    site: "registerHonestHeadroom(",
  },
  {
    id: "test:protocol.binding-language-views.bound-spec-page",
    nodeType: "Anchor",
    label: "the bound-surface point verifies the rendered binding vocabulary",
    file: "test/self-hosting-projections.test.ts",
    constant: "boundSpecPageTestAnchor",
    site: "bindExample(boundSpecPageContract",
  },
  {
    id: "test:protocol.binding-language-views.pack-member-table",
    nodeType: "Anchor",
    label: "the pack-member point verifies the aggregate half of the rendered binding vocabulary",
    file: "test/self-hosting-projections.test.ts",
    constant: "packMemberTableTestAnchor",
    site: "registerPackMemberTable(",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.stale-page-removed",
    nodeType: "Anchor",
    label: "the stale-page point verifies the wholesale rewrite of the view directory",
    file: "test/self-hosting-projections.test.ts",
    constant: "stalePageRemovedTestAnchor",
    site: "registerStalePageRemoved(",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.late-stale-page",
    nodeType: "Anchor",
    label: "the late-page point verifies that the swap itself evicts what invalidation missed",
    file: "test/self-hosting-projections.test.ts",
    constant: "lateStalePageTestAnchor",
    site: "registerLateStalePage(",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.failed-run-view-removed",
    nodeType: "Anchor",
    label: "the failed-run point verifies that an uncertifiable view is removed, not left readable",
    file: "test/self-hosting-projections.test.ts",
    constant: "failedRunViewRemovedTestAnchor",
    site: "registerFailedRunViewRemoved(",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.build-invalidates-view",
    nodeType: "Anchor",
    label: "the build point verifies the up-front invalidation on a command that renders no view",
    file: "test/self-hosting-projections.test.ts",
    constant: "buildInvalidatesViewTestAnchor",
    site: "registerBuildInvalidatesView(",
  },
  {
    id: "test:protocol.diagnostic-rendering.composed-location",
    nodeType: "Anchor",
    label: "the composed-location point verifies the one rendering rule and both degradations",
    file: "test/self-hosting-projections.test.ts",
    constant: "composedLocationTestAnchor",
    site: "registerComposedLocation(",
  },
  {
    id: "test:protocol.diagnostic-rendering.table-cell-location",
    nodeType: "Anchor",
    label: "the table-cell point verifies the same composition rule on the Design Review's twin",
    file: "test/self-hosting-projections.test.ts",
    constant: "tableCellLocationTestAnchor",
    site: "registerTableCellLocation(",
  },
  {
    id: "test:protocol.design-review.pure-projection",
    nodeType: "Anchor",
    label: "the pure-projection point verifies the view's own law over a whole-pipeline root",
    file: "test/self-hosting-projections.test.ts",
    constant: "pureProjectionTestAnchor",
    site: "registerPureProjection(",
  },
  {
    id: "test:protocol.agent-surface.scripted-context-body",
    nodeType: "Anchor",
    label: "the scripted-body point verifies the front door's claim-decoded, pre-shaped return",
    file: "test/self-hosting-consumers.test.ts",
    constant: "scriptedContextBodyTestAnchor",
    site: "bindExample(scriptedContextBodyContract",
  },
  {
    id: "test:protocol.agent-surface.demand-map-entries",
    nodeType: "Anchor",
    label: "the demand-map point verifies the three entry points and the absent symbol entry",
    file: "test/self-hosting-consumers.test.ts",
    constant: "demandMapEntriesTestAnchor",
    site: "bindExample(demandMapEntriesContract",
  },
  {
    id: "test:protocol.reader.concept-entry",
    nodeType: "Anchor",
    label: "the concept-entry point verifies the string bridge and the field it names",
    file: "test/self-hosting-consumers.test.ts",
    constant: "conceptEntryTestAnchor",
    site: "bindExample(conceptEntryContract",
  },
  {
    id: "test:protocol.reader.file-entry",
    nodeType: "Anchor",
    label: "the file-entry point verifies both halves of the file bridge",
    file: "test/self-hosting-consumers.test.ts",
    constant: "fileEntryTestAnchor",
    site: "bindExample(fileEntryContract",
  },
  {
    id: "test:protocol.reader.changeset-entry",
    nodeType: "Anchor",
    label: "the changeset-entry point verifies impact reasons, at-risk edges, and coverage-unknown",
    file: "test/self-hosting-consumers.test.ts",
    constant: "changesetEntryTestAnchor",
    site: "bindExample(changesetEntryContract",
  },
  {
    id: "impl:protocol.sdp-import",
    nodeType: "CodeNode",
    label: "plans, refuses, and publishes TypeScript-to-Markdown Spec imports",
    file: "src/cli/import-command.ts",
    constant: "sdpImportAnchor",
    site: "export function runImport",
    role: "service",
  },
  {
    id: "impl:protocol.extraction-determinism",
    nodeType: "CodeNode",
    label: "repeats and byte-compares graph and contract generation under --check-clean",
    file: "src/cli/build-command.ts",
    constant: "determinismAnchor",
    site: "export function runBuild",
    role: "service",
  },
  {
    id: "impl:protocol.wholesale-view-build-invalidation",
    nodeType: "CodeNode",
    label: "invalidates the prior Design Review before every build attempt",
    file: "src/cli/build-command.ts",
    constant: "wholesaleViewBuildInvalidationAnchor",
    site: "export function runBuild",
    role: "service",
  },
  {
    id: "impl:protocol.wholesale-view-rewrite",
    nodeType: "CodeNode",
    label: "publishes each Design Review as one wholesale temporary-directory replacement",
    file: "src/cli/validate-view-command.ts",
    constant: "wholesaleViewRewriteAnchor",
    site: "export function runView",
    role: "publisher",
  },
  {
    id: "impl:protocol.derived-readiness-banner",
    nodeType: "CodeNode",
    label: "renders stated readiness beside the structural floor and dishonest divergence",
    file: "src/projections/design-review-context.ts",
    site: "export function renderReadiness",
    role: "renderer",
  },
  {
    id: "impl:protocol.binding-language-spec-page",
    nodeType: "CodeNode",
    label: "renders implementation, verifier, oracle, and observation binding language",
    file: "src/projections/design-review-context.ts",
    site: "export function renderBindings",
    role: "renderer",
  },
  {
    id: "impl:protocol.diagnostic-rendering-design-review",
    nodeType: "CodeNode",
    label: "renders structured finding locations in the Design Review table",
    file: "src/projections/design-review-context.ts",
    site: "export function renderFindings",
    role: "renderer",
  },
  {
    id: "impl:protocol.binding-language-pack-table",
    nodeType: "CodeNode",
    label: "renders Pack member implementation and verifier bindings as present or none",
    file: "src/projections/design-review-pages.ts",
    site: "export function renderPackPage",
    role: "renderer",
  },
  {
    id: "impl:protocol.binding-language-index-table",
    nodeType: "CodeNode",
    label: "renders index implementation and verifier bindings as present or none",
    file: "src/projections/design-review-pages.ts",
    site: "export function renderIndexPage",
    role: "renderer",
  },
  {
    id: "impl:protocol.diagnostic-rendering-cli",
    nodeType: "CodeNode",
    label: "composes structured finding fields into the one command-line diagnostic form",
    file: "src/cli/output.ts",
    constant: "diagnosticCliAnchor",
    site: "export function formatFinding",
    role: "renderer",
  },
  {
    id: "impl:protocol.kind-evidence",
    nodeType: "CodeNode",
    label: "defines the code-level per-kind evidence rows for readiness floors",
    file: "src/validate/readiness-floor.ts",
    constant: "kindEvidenceAnchor",
    site: "export const kindEvidence",
    role: "contract",
  },
  {
    id: "impl:protocol.referential-integrity",
    nodeType: "CodeNode",
    label: "checks every graph edge endpoint and Pack model reference resolves",
    file: "src/validate/validators.ts",
    constant: "referentialIntegrityAnchor",
    site: "function checkEdgeReferentialIntegrity",
    role: "validator",
  },
  {
    id: "impl:protocol.claim-separation",
    nodeType: "CodeNode",
    label: "checks graph claims, descriptors, node shapes, and relation endpoint contracts",
    file: "src/validate/validators.ts",
    constant: "claimSeparationAnchor",
    site: "function checkClaimSeparation",
    role: "validator",
  },
  {
    id: "impl:protocol.verifies-linkage",
    nodeType: "CodeNode",
    label: "resolves declared example verification through enabled test bindings",
    file: "src/validate/validators.ts",
    constant: "verifiesLinkageAnchor",
    site: "function checkVerifiesLinkage",
    role: "validator",
  },
  {
    id: "impl:protocol.oracle-linkage",
    nodeType: "CodeNode",
    label: "resolves and de-duplicates expected-outcome oracle bindings",
    file: "src/validate/validators.ts",
    constant: "oracleLinkageAnchor",
    site: "function checkOracleLinkage",
    role: "validator",
  },
  {
    id: "impl:protocol.pack-coherence",
    nodeType: "CodeNode",
    label: "checks Pack membership uniqueness and model-reference kinds",
    file: "src/validate/validators.ts",
    constant: "packCoherenceAnchor",
    site: "function checkPackCoherence",
    role: "validator",
  },
  {
    id: "impl:protocol.orphan-signal",
    nodeType: "CodeNode",
    label: "surfaces relationless Specs as informative orphan warnings",
    file: "src/validate/validators.ts",
    constant: "orphanSignalAnchor",
    site: "function checkOrphans",
    role: "validator",
  },
  {
    id: "impl:protocol.authored-honesty-shape",
    nodeType: "CodeNode",
    label: "refuses delivery facts smuggled through authored section carriers",
    file: "src/validate/validators.ts",
    constant: "authoringShapeAnchor",
    site: "function checkAuthoringShape",
    role: "validator",
  },
  {
    id: "impl:protocol.authored-honesty-delivery-facts",
    nodeType: "CodeNode",
    label: "checks stated delivery facts equal the one recomputed derivation",
    file: "src/validate/validators.ts",
    constant: "deliveryFactsHonestyAnchor",
    site: "function checkDeliveryFacts",
    role: "validator",
  },
  {
    id: "impl:protocol.verifier-gap-signal",
    nodeType: "CodeNode",
    label: "surfaces ready Specs without recomputed verifier bindings as informative gaps",
    file: "src/validate/validators.ts",
    constant: "gapSignalAnchor",
    site: "function checkGaps",
    role: "validator",
  },
  {
    id: "oracle:protocol.reader-entry-map",
    nodeType: "Anchor",
    label: "expected reader outcome for each graph entry mode",
    file: "test/self-hosting-consumers.oracle.ts",
    constant: "readerEntryMapOracle",
    site: "export function expectedReaderOutcome",
  },
  {
    id: "impl:protocol.oracle-target-eligibility",
    nodeType: "CodeNode",
    label: "resolves oracle targets by example-space ownership across Spec kinds",
    file: "src/graph/oracle-bindings.ts",
    constant: "oracleTargetEligibilityAnchor",
    site: "export function isResolvingOracleModel",
    role: "decider",
  },
  {
    id: "test:protocol.oracle-target-eligibility.rule-space-accepted",
    nodeType: "Anchor",
    label: "the rule-space point verifies kind-neutral oracle resolution",
    file: "test/self-hosting-validators.test.ts",
    constant: "ruleSpaceAcceptedTestAnchor",
    site: "registerRuleSpaceAccepted(",
  },
  {
    id: "test:protocol.mermaid-view",
    nodeType: "Anchor",
    label: "verifies bounded deterministic Mermaid projection and publication",
    file: "test/mermaid-render.test.ts",
    constant: "mermaidTestAnchor",
    site: "const checkoutRoot",
  },
  {
    id: "test:protocol.oracle-target-eligibility.missing-space-refused",
    nodeType: "Anchor",
    label: "the missing-space point verifies fail-closed oracle resolution",
    file: "test/self-hosting-validators.test.ts",
    constant: "missingSpaceRefusedTestAnchor",
    site: "registerMissingSpaceRefused(",
  },
  {
    id: "oracle:protocol.oracle-target-eligibility",
    nodeType: "Anchor",
    label: "expected oracle-linkage result by example-space ownership",
    file: "test/self-hosting-validators.oracle.ts",
    constant: "oracleTargetEligibilityOracle",
    site: "export function expectedOracleTargetEligibilityOutcome",
  },
  {
    id: "impl:protocol.markdown-pack-authoring",
    nodeType: "CodeNode",
    label: "reifies the Markdown Pack manifest into the one carrier path",
    file: "src/extract/markdown-pack.ts",
    constant: "markdownPackAuthoringAnchor",
    site: "export function reifyMarkdownPack(",
    role: "extractor",
  },
  {
    id: "test:protocol.markdown-pack-authoring.markdown-ts-parity",
    nodeType: "Anchor",
    label: "the parity point verifies equal Markdown and TypeScript Pack derivation",
    file: "test/self-hosting-pack-markdown.test.ts",
    constant: "parityTestAnchor",
    site: "registerMarkdownTsParity(",
  },
  {
    id: "test:protocol.markdown-pack-authoring.spec-envelope-refused",
    nodeType: "Anchor",
    label: "the refusal point verifies the Markdown Pack closed envelope",
    file: "test/self-hosting-pack-markdown.test.ts",
    constant: "refusalTestAnchor",
    site: "registerSpecEnvelopeRefused(",
  },
  {
    id: "impl:protocol.build-pipeline-query",
    nodeType: "CodeNode",
    label:
      "one query invocation derives the graph once and serves reader, raw graph, and report from that one derivation",
    file: "src/cli/q-command.ts",
    constant: "buildPipelineQueryAnchor",
    site: "export async function runQuery",
    role: "service",
  },
  {
    id: "impl:protocol.build-pipeline-emit",
    nodeType: "CodeNode",
    label: "the build command owns the ordered flow through artifact emission",
    file: "src/cli/build-command.ts",
    constant: "buildPipelineEmitAnchor",
    site: "export function runBuild",
    role: "service",
  },
  {
    id: "impl:protocol.example-runner-adapter",
    nodeType: "CodeNode",
    label: "registers one test per example and owns the fresh world lifecycle",
    file: "src/adapters/vitest.ts",
    constant: "exampleRunnerAdapterAnchor",
    site: "export function bindExample",
    role: "adapter",
  },
  {
    id: "impl:protocol.runnable-modules",
    nodeType: "CodeNode",
    label: "derives and publishes runnable registrar modules from the graph",
    file: "src/codegen/contracts.ts",
    constant: "runnableModulesAnchor",
    site: "export function generateContracts",
    role: "projection",
  },
  {
    id: "test:protocol.census-page",
    nodeType: "Anchor",
    label: "verifies census taxonomy, findings, and structural-binding projection",
    file: "test/census.test.ts",
    constant: "censusTestAnchor",
    site: 'describe("the derived census/taxonomy projection"',
  },
  {
    id: "test:protocol.runnable-modules",
    nodeType: "Anchor",
    label: "verifies generated runnable-module registration and runtime semantics",
    file: "test/testing.test.ts",
    constant: "runnableModulesTestAnchor",
    site: 'describe("generated registrar testing runtime"',
  },
  {
    id: "impl:protocol.sdp-import-core",
    nodeType: "CodeNode",
    label: "converts a TypeScript-carrier Spec into an idiomatic Markdown twin",
    file: "src/import/import.ts",
    constant: "sdpImportCoreAnchor",
    site: "export function importTypeScriptSpec",
    role: "service",
  },
  {
    id: "impl:protocol.sdp-import-markdown-emit",
    nodeType: "CodeNode",
    label: "emits the Markdown document twin for an imported Spec",
    file: "src/import/emit-markdown.ts",
    constant: "sdpImportMarkdownEmitAnchor",
    site: "export function emitMarkdownSpec",
    role: "codec",
  },
  {
    id: "impl:protocol.example-testing-helpers",
    nodeType: "CodeNode",
    label: "adapter-lifecycle and oracle-comparison helpers for bound examples",
    file: "src/testing/index.ts",
    constant: "exampleTestingHelpersAnchor",
    site: "export function createRunnableExample",
    role: "utility",
  },
  {
    id: "impl:protocol.discover-files",
    nodeType: "CodeNode",
    label: "realizes exclusion-aware discovery (normalizeExcludes / discoverFiles)",
    file: "src/extract/discover.ts",
    constant: "discoverFilesAnchor",
    site: "export function normalizeExcludes",
    role: "extractor",
  },
  {
    id: "impl:protocol.protocol-bindings",
    nodeType: "CodeNode",
    label: "Protocol builder-import trust (protocolBindingScopeFor / collectProtocolBindings)",
    file: "src/extract/protocol-bindings.ts",
    constant: "protocolBindingsAnchor",
    site: "export function protocolBindingScopeFor",
    role: "extractor",
  },
  {
    id: "impl:protocol.static-reification",
    nodeType: "CodeNode",
    label: "reifies authored carriers from the AST and never evaluates them",
    file: "src/extract/reify.ts",
    constant: "staticReificationAnchor",
    site: "export function reifySourceFile",
    role: "extractor",
  },
  {
    id: "impl:protocol.carrier-reification",
    nodeType: "CodeNode",
    label: "reifies each canonical carrier surface into specs, packs, and findings",
    file: "src/extract/carrier.ts",
    constant: "carrierReificationAnchor",
    site: "export function reifyTypeScriptCarrier",
    role: "extractor",
  },
  {
    id: "impl:protocol.spec-scaffolder",
    nodeType: "CodeNode",
    label: "scaffolds an honest idea-rung Markdown Spec through `sdp new spec`",
    file: "src/cli/new-spec-command.ts",
    constant: "specScaffolderAnchor",
    site: "export function runNewSpec",
    role: "service",
  },
  {
    id: "impl:protocol.delivery-facts",
    nodeType: "CodeNode",
    label: "computes delivery facts from resolving binding edges",
    file: "src/graph/delivery-facts.ts",
    constant: "deliveryFactsAnchor",
    site: "export function computeDeliveryFacts",
    role: "decider",
  },
  {
    id: "impl:protocol.example-space",
    nodeType: "CodeNode",
    label: "resolves example-space vocabulary for contracts and floors",
    file: "src/graph/example-space.ts",
    constant: "exampleSpaceAnchor",
    site: "export function resolveExampleVocabulary",
    role: "decider",
  },
  {
    id: "impl:protocol.graph-index",
    nodeType: "CodeNode",
    label: "builds the one-graph index validators and the reader share",
    file: "src/validate/graph-index.ts",
    constant: "graphIndexAnchor",
    site: "export function buildGraphIndex",
    role: "utility",
  },
  {
    id: "impl:protocol.validation-contracts",
    nodeType: "CodeNode",
    label: "conformance/honesty family currency and finding shapes",
    file: "src/validate/contracts.ts",
    constant: "validationContractsAnchor",
    site: "export const validatorFamilies",
    role: "contract",
  },
  {
    id: "impl:protocol.agent-surface-cli",
    nodeType: "CodeNode",
    label: "CLI verb dispatcher and agent-surface front of the package CLI",
    file: "src/cli/sdp.ts",
    site: "export function runSdpCli",
    role: "service",
  },
  {
    id: "impl:protocol.census-page-cli",
    nodeType: "CodeNode",
    label: "publishes the census through the explicit `sdp census` surface",
    file: "src/cli/census-command.ts",
    constant: "censusPageCliAnchor",
    site: "export function runCensus",
    role: "publisher",
  },
  {
    id: "impl:protocol.mermaid-view-cli",
    nodeType: "CodeNode",
    label: "publishes Mermaid through the explicit `sdp mermaid` surface",
    file: "src/cli/mermaid-command.ts",
    constant: "mermaidViewCliAnchor",
    site: "export function runMermaid",
    role: "publisher",
  },
  {
    id: "impl:protocol.gherkin-view-cli",
    nodeType: "CodeNode",
    label: "publishes the Gherkin view through the explicit `sdp gherkin` surface",
    file: "src/cli/gherkin-command.ts",
    constant: "gherkinViewCliAnchor",
    site: "export function runGherkinView",
    role: "publisher",
  },
  {
    id: "test:protocol.markdown-body-grammar.table-refused",
    nodeType: "Anchor",
    label: "the table point verifies the block-structure refusal",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "tableRefusedTestAnchor",
    site: "registerTableRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.continuation-line-refused",
    nodeType: "Anchor",
    label: "the continuation-line point verifies the one-line entry rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "continuationLineRefusedTestAnchor",
    site: "registerContinuationLineRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.ordered-list-refused",
    nodeType: "Anchor",
    label: "the ordered-list point verifies the list-entry rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "orderedListRefusedTestAnchor",
    site: "registerOrderedListRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.foreign-fence-refused",
    nodeType: "Anchor",
    label: "the foreign-fence point verifies the closed fence set",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "foreignFenceRefusedTestAnchor",
    site: "registerForeignFenceRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.h3-refused",
    nodeType: "Anchor",
    label: "the H3 point verifies the single-H3 rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "h3RefusedTestAnchor",
    site: "registerH3Refused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.plain-bullet-refused",
    nodeType: "Anchor",
    label: "the plain-bullet point verifies the open-section key rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "plainBulletRefusedTestAnchor",
    site: "registerPlainBulletRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.keyed-bullet-refused",
    nodeType: "Anchor",
    label: "the keyed-bullet point verifies the keyed-bullet rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "keyedBulletRefusedTestAnchor",
    site: "registerKeyedBulletRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.trailing-prose-refused",
    nodeType: "Anchor",
    label: "the trailing-prose point verifies the prose-ownership rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "trailingProseRefusedTestAnchor",
    site: "registerTrailingProseRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.repeated-field-refused",
    nodeType: "Anchor",
    label: "the repeated-field point verifies the at-most-once rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "repeatedFieldRefusedTestAnchor",
    site: "registerRepeatedFieldRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.unrecognized-heading-refused",
    nodeType: "Anchor",
    label: "the unrecognized-heading point verifies the closed owner set",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "unrecognizedHeadingRefusedTestAnchor",
    site: "registerUnrecognizedHeadingRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.second-primary-owner-refused",
    nodeType: "Anchor",
    label: "the second-primary-owner point verifies the one-primary-owner rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "secondPrimaryOwnerRefusedTestAnchor",
    site: "registerSecondPrimaryOwnerRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.raw-html-refused",
    nodeType: "Anchor",
    label: "the raw-HTML point verifies the raw-HTML refusal outside code spans",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "rawHtmlRefusedTestAnchor",
    site: "registerRawHtmlRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.shared-description-refused",
    nodeType: "Anchor",
    label: "the shared-description point verifies the one-description-owner rule",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "sharedDescriptionRefusedTestAnchor",
    site: "registerSharedDescriptionRefused(",
  },
  {
    id: "test:protocol.markdown-body-grammar.integer-term-refused",
    nodeType: "Anchor",
    label: "the integer-term point verifies the integer-like Model term refusal",
    file: "test/self-hosting-markdown-grammar.test.ts",
    constant: "integerTermRefusedTestAnchor",
    site: "registerIntegerTermRefused(",
  },
  {
    id: "impl:protocol.markdown-body-grammar",
    nodeType: "CodeNode",
    label: "enforces the closed Markdown body grammar",
    file: "src/extract/markdown-body.ts",
    constant: "markdownBodyGrammarAnchor",
    site: "export function parseMarkdownBody",
    role: "codec",
  },
  {
    id: "impl:protocol.inline-code-spans",
    nodeType: "CodeNode",
    label: "scans raw HTML outside matched code spans",
    file: "src/extract/markdown-inline-code.ts",
    constant: "inlineCodeSpansAnchor",
    site: "export function hasRawHtmlOutsideCodeSpans",
    role: "codec",
  },
  {
    id: "oracle:protocol.inline-code-spans",
    nodeType: "Anchor",
    label: "expected inline code outcome by authored location",
    file: "test/self-hosting-inline-code.test.ts",
    constant: "inlineCodeOracleAnchor",
    site: "function expectedInlineCodeOutcome",
  },
  {
    id: "test:protocol.inline-code-spans.narrative",
    nodeType: "Anchor",
    label: "verifies inline code in Spec narrative",
    file: "test/self-hosting-inline-code.test.ts",
    constant: "narrativeTestAnchor",
    site: "registerNarrative(",
  },
  {
    id: "test:protocol.inline-code-spans.description",
    nodeType: "Anchor",
    label: "verifies inline code in section descriptions",
    file: "test/self-hosting-inline-code.test.ts",
    constant: "descriptionTestAnchor",
    site: "registerDescription(",
  },
  {
    id: "test:protocol.inline-code-spans.list",
    nodeType: "Anchor",
    label: "verifies inline code in list entries",
    file: "test/self-hosting-inline-code.test.ts",
    constant: "listTestAnchor",
    site: "registerList(",
  },
  {
    id: "test:protocol.inline-code-spans.pack",
    nodeType: "Anchor",
    label: "verifies inline code in Pack framing",
    file: "test/self-hosting-inline-code.test.ts",
    constant: "packTestAnchor",
    site: "registerPack(",
  },
  {
    id: "impl:protocol.unbound-example-posture",
    nodeType: "CodeNode",
    label: "limits unbound example warnings to stated ready",
    file: "src/validate/validators.ts",
    constant: "unboundExamplePostureAnchor",
    site: "function checkVerifiesLinkage",
    role: "validator",
  },
  {
    id: "oracle:protocol.unbound-example-posture",
    nodeType: "Anchor",
    label: "expected verification signals by posture matrix",
    file: "test/self-hosting-unbound-example.test.ts",
    constant: "unboundPostureOracleAnchor",
    site: "function expectedPosture",
  },
  {
    id: "test:protocol.unbound-example-posture.lower-rungs",
    nodeType: "Anchor",
    label: "verifies declared-only examples below ready",
    file: "test/self-hosting-unbound-example.test.ts",
    constant: "lowerRungsTestAnchor",
    site: "registerLowerRungs(",
  },
  {
    id: "test:protocol.unbound-example-posture.warning-cases",
    nodeType: "Anchor",
    label: "verifies ready and wrong-kind linkage warnings",
    file: "test/self-hosting-unbound-example.test.ts",
    constant: "warningCasesTestAnchor",
    site: "registerWarningCases(",
  },
  {
    id: "test:protocol.unbound-example-posture.parent-traces",
    nodeType: "Anchor",
    label: "verifies parent gaps and unchanged oracle signals",
    file: "test/self-hosting-unbound-example.test.ts",
    constant: "parentTracesTestAnchor",
    site: "registerParentTraces(",
  },
  {
    id: "impl:protocol.typed-dependency-floor",
    nodeType: "CodeNode",
    label: "checks stated readiness across all four typed dependencies",
    file: "src/validate/readiness-floor.ts",
    constant: "typedDependencyFloorAnchor",
    site: "function typedDependencyTargetsAreDefined",
    role: "validator",
  },
  {
    id: "oracle:protocol.typed-dependency-floor",
    nodeType: "Anchor",
    label: "expected readiness failures by typed dependency matrix",
    file: "test/self-hosting-typed-dependency.test.ts",
    constant: "typedDependencyOracleAnchor",
    site: "function expectedFloor",
  },
  {
    id: "test:protocol.typed-dependency-floor.relation-rungs",
    nodeType: "Anchor",
    label: "verifies six relations across four target rungs",
    file: "test/self-hosting-typed-dependency.test.ts",
    constant: "relationRungsTestAnchor",
    site: "registerRelationRungs(",
  },
  {
    id: "test:protocol.typed-dependency-floor.missing-targets",
    nodeType: "Anchor",
    label: "verifies unresolved targets fail resolution once",
    file: "test/self-hosting-typed-dependency.test.ts",
    constant: "missingTargetsTestAnchor",
    site: "registerMissingTargets(",
  },
  {
    id: "test:protocol.typed-dependency-floor.unsettled-fact",
    nodeType: "Anchor",
    label: "verifies blocking questions and bounded readiness",
    file: "test/self-hosting-typed-dependency.test.ts",
    constant: "unsettledFactTestAnchor",
    site: "registerUnsettledFact(",
  },
  {
    id: "test:protocol.typed-dependency-floor.stated-readiness",
    nodeType: "Anchor",
    label: "verifies stated target readiness and kind blindness",
    file: "test/self-hosting-typed-dependency.test.ts",
    constant: "statedReadinessTestAnchor",
    site: "registerStatedReadiness(",
  },
  {
    id: "impl:protocol.register-recipes",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped register recipes",
    file: "test/recipes.test.ts",
    constant: "registerRecipesImplementationAnchor",
    site: 'describe("the agent-surface recipe corpus",',
  },
  {
    id: "test:protocol.register-recipes",
    nodeType: "Anchor",
    label: "recipe checks verify the register recipes",
    file: "test/recipes.test.ts",
    constant: "registerRecipesTestAnchor",
    site: 'describe("the agent-surface recipe corpus",',
  },
  {
    id: "impl:protocol.adopter-on-ramp",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped adopter teaching in the authoring skill",
    file: "test/skills.test.ts",
    constant: "adopterOnRampImplementationAnchor",
    site: 'describe("adopter teaching",',
  },
  {
    id: "test:protocol.adopter-on-ramp",
    nodeType: "Anchor",
    label: "skill-asset checks verify the adopter on-ramp",
    file: "test/skills.test.ts",
    constant: "adopterOnRampTestAnchor",
    site: 'describe("adopter teaching",',
  },
  {
    id: "impl:protocol.shipped-protocol-corpus",
    nodeType: "CodeNode",
    label: "asserts the published package ships the Protocol corpus",
    file: "test/package-smoke.test.ts",
    constant: "shippedProtocolCorpusImplementationAnchor",
    site: 'describe("published package surface",',
  },
  {
    id: "test:protocol.shipped-protocol-corpus",
    nodeType: "Anchor",
    label: "package smoke checks verify the shipped corpus",
    file: "test/package-smoke.test.ts",
    constant: "shippedProtocolCorpusTestAnchor",
    site: 'describe("published package surface",',
  },
  {
    id: "impl:protocol.prose-mentions",
    nodeType: "CodeNode",
    label: "checks that prose mentions resolve and warns once per unbacked Spec pair",
    file: "src/validate/validators.ts",
    constant: "proseMentionsAnchor",
    site: "function checkProseMentions",
    role: "validator",
  },
  {
    id: "test:protocol.prose-mentions",
    nodeType: "Anchor",
    label: "verifies prose-mention resolution and the unbacked-pair warning",
    file: "test/validators.test.ts",
    constant: "proseMentionsTestAnchor",
    site: 'describe("conformance/prose-mentions',
  },
  {
    id: "impl:protocol.pack-member-order",
    nodeType: "CodeNode",
    label: "keeps manifest member order on the Pack node",
    file: "src/extract/derive.ts",
    constant: "packMemberOrderAnchor",
    site: "function derivePackNode",
    role: "extractor",
  },
  {
    id: "impl:protocol.open-question-keys",
    nodeType: "CodeNode",
    label:
      "reads an open question's optional key from its Markdown marker and refuses a bad or repeated key",
    file: "src/extract/markdown-body-owner-behavior.ts",
    constant: "openQuestionKeysAnchor",
    site: "const OPEN_QUESTION_MARKER",
    role: "codec",
  },
  {
    id: "impl:protocol.next-rung-floor",
    nodeType: "CodeNode",
    label: "evaluates the floor for a target rung and names the targets that break a dependency",
    file: "src/validate/readiness-floor.ts",
    constant: "nextRungFloorAnchor",
    site: "export function evaluateReadinessFloor",
    role: "validator",
  },
  {
    id: "impl:protocol.address-and-cycle-recipes",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped address resolution and dependency cycle recipes",
    file: "test/recipes.test.ts",
    constant: "addressAndCycleRecipesImplementationAnchor",
    site: 'describe("the agent-surface recipe corpus"',
  },
  {
    id: "test:protocol.address-and-cycle-recipes",
    nodeType: "Anchor",
    label: "recipe checks verify the address resolution and dependency cycle recipes",
    file: "test/recipes.test.ts",
    constant: "addressAndCycleRecipesTestAnchor",
    site: 'describe("the agent-surface recipe corpus"',
  },
  {
    id: "oracle:protocol.next-rung-floor",
    nodeType: "Anchor",
    label: "expected next-rung clause and targets by structure",
    file: "test/self-hosting-next-rung-floor.test.ts",
    constant: "nextRungOracleAnchor",
    site: "function answerFor",
  },
  {
    id: "test:protocol.next-rung-floor.typed-dependency-targets",
    nodeType: "Anchor",
    label: "verifies the next rung's failure names the dependency stated below defined",
    file: "test/self-hosting-next-rung-floor.test.ts",
    constant: "typedDependencyTargetsTestAnchor",
    site: "registerTypedDependencyTargets(",
  },
  {
    id: "test:protocol.next-rung-floor.blocking-question",
    nodeType: "Anchor",
    label: "verifies the next rung's failure names a blocking question and no target",
    file: "test/self-hosting-next-rung-floor.test.ts",
    constant: "blockingQuestionTestAnchor",
    site: "registerBlockingQuestion(",
  },
  {
    id: "oracle:protocol.open-question-keys",
    nodeType: "Anchor",
    label: "expected reification, question keys and mention errors by the key rules",
    file: "test/self-hosting-open-question-keys.test.ts",
    constant: "openQuestionKeysOracleAnchor",
    site: "function answerFor",
  },
  {
    id: "test:protocol.open-question-keys.keyed-question-resolves",
    nodeType: "Anchor",
    label: "verifies a keyed question is reified and its question address resolves",
    file: "test/self-hosting-open-question-keys.test.ts",
    constant: "keyedQuestionResolvesTestAnchor",
    site: "registerKeyedQuestionResolves(",
  },
  {
    id: "test:protocol.open-question-keys.renamed-key-breaks",
    nodeType: "Anchor",
    label: "verifies a renamed question key fails the mention of its old address",
    file: "test/self-hosting-open-question-keys.test.ts",
    constant: "renamedKeyBreaksTestAnchor",
    site: "registerRenamedKeyBreaks(",
  },
  {
    id: "test:protocol.open-question-keys.repeated-key-refused",
    nodeType: "Anchor",
    label: "verifies a repeated question key refuses its carrier whole",
    file: "test/self-hosting-open-question-keys.test.ts",
    constant: "repeatedKeyRefusedTestAnchor",
    site: "registerRepeatedKeyRefused(",
  },
  {
    id: "test:protocol.pack-member-order",
    nodeType: "Anchor",
    label: "verifies manifest order in the graph, reader and Pack page",
    file: "test/self-hosting-pack-member-order.test.ts",
    constant: "packMemberOrderTestAnchor",
    site: "registerManifestOrderKept(",
  },
] as const;

// re-measured under plan 40
export const expectedBindingEdges = [
  ["test:protocol.open-section-order", "verifies", "spec:extraction.open-section-order"],
  ["impl:protocol.open-section-order", "satisfies", "spec:extraction.open-section-order"],
  ["component:protocol.model", "satisfies", "spec:model.core-model"],
  ["component:protocol.extract", "satisfies", "spec:extraction.derive-graph"],
  ["component:protocol.graph", "satisfies", "spec:extraction.claim-taxonomy"],
  ["component:protocol.validate", "satisfies", "spec:validation.two-check-families"],
  ["component:protocol.reader", "satisfies", "spec:consumers.reader"],
  ["component:protocol.projections", "satisfies", "spec:consumers.projections-model"],
  ["component:protocol.cli", "satisfies", "spec:extraction.build-pipeline"],
  ["component:protocol.runner", "satisfies", "spec:extraction.example-runner"],
  ["component:protocol.codegen", "satisfies", "spec:extraction.runnable-modules"],
  ["component:protocol.notation", "satisfies", "spec:carrier.slot-notation"],
  ["component:protocol.adapters", "satisfies", "spec:extraction.example-runner"],
  ["component:protocol.import", "satisfies", "spec:carrier.sdp-import"],
  ["component:protocol.testing", "satisfies", "spec:extraction.example-runner"],
  ["impl:protocol.extract", "satisfies", "spec:extraction.derive-graph"],
  ["impl:protocol.derive-graph", "satisfies", "spec:extraction.derive-graph"],
  ["test:protocol.extract", "verifies", "spec:extraction.derive-graph"],
  ["test:protocol.delivery-facts", "verifies", "spec:extraction.delivery-facts"],
  ["test:protocol.structural-self-binding", "verifies", "spec:protocol.structural-self-binding"],
  ["test:protocol.extraction-determinism", "verifies", "spec:extraction.determinism"],
  [
    "test:protocol.build-pipeline.same-invocation",
    "verifies",
    "spec:extraction.build-pipeline.same-invocation",
  ],
  ["impl:protocol.authoring-on-ramp", "satisfies", "spec:consumers.authoring-on-ramp"],
  [
    "impl:protocol.delivery-session-on-ramp",
    "satisfies",
    "spec:consumers.delivery-session-on-ramp",
  ],
  [
    "impl:protocol.authoring-recipes",
    "satisfies",
    "spec:consumers.agent-surface.authoring-recipes",
  ],
  ["test:protocol.authoring-on-ramp", "verifies", "spec:consumers.authoring-on-ramp"],
  ["test:protocol.delivery-session-on-ramp", "verifies", "spec:consumers.delivery-session-on-ramp"],
  ["test:protocol.authoring-recipes", "verifies", "spec:consumers.agent-surface.authoring-recipes"],
  ["impl:protocol.readiness-floor", "satisfies", "spec:validation.readiness-floor"],
  ["test:protocol.readiness-floor", "verifies", "spec:validation.readiness-floor"],
  ["impl:protocol.markdown-authoring", "satisfies", "spec:carrier.markdown-authoring"],
  ["impl:protocol.gherkin-authoring", "satisfies", "spec:carrier.gherkin-authoring"],
  ["impl:protocol.markdown-parser", "satisfies", "spec:carrier.markdown-parser"],
  ["test:protocol.markdown-parser", "verifies", "spec:carrier.markdown-parser"],
  ["impl:protocol.envelope-contract", "satisfies", "spec:carrier.envelope-contract"],
  ["test:protocol.envelope-contract", "verifies", "spec:carrier.envelope-contract"],
  ["impl:protocol.prose-ownership", "satisfies", "spec:carrier.prose-ownership-rule"],
  ["test:protocol.prose-ownership", "verifies", "spec:carrier.prose-ownership-rule"],
  ["impl:protocol.duplicate-id-exclusion", "satisfies", "spec:validation.duplicate-ids"],
  [
    "test:protocol.duplicate-ids.dual-carrier",
    "verifies",
    "spec:validation.duplicate-ids.dual-carrier",
  ],
  [
    "test:protocol.warn-level-signals.orphan-signal",
    "verifies",
    "spec:validation.warn-level-signals.orphan-signal",
  ],
  [
    "test:protocol.warn-level-signals.ready-gap-signal",
    "verifies",
    "spec:validation.warn-level-signals.ready-gap-signal",
  ],
  [
    "test:protocol.readiness-floor.unrelated-scoped-spec",
    "verifies",
    "spec:validation.readiness-floor.unrelated-scoped-spec",
  ],
  [
    "test:protocol.readiness-floor.blocking-open-question",
    "verifies",
    "spec:validation.readiness-floor.blocking-open-question",
  ],
  [
    "test:protocol.kind-evidence.constraints-alone",
    "verifies",
    "spec:validation.kind-evidence.constraints-alone",
  ],
  [
    "test:protocol.kind-evidence.untargeted-constraint",
    "verifies",
    "spec:validation.kind-evidence.untargeted-constraint",
  ],
  [
    "test:protocol.kind-evidence.empty-promoted-child",
    "verifies",
    "spec:validation.kind-evidence.empty-promoted-child",
  ],
  [
    "test:protocol.referential-integrity.dangling-target",
    "verifies",
    "spec:validation.referential-integrity.dangling-target",
  ],
  [
    "test:protocol.referential-integrity.did-you-mean",
    "verifies",
    "spec:validation.referential-integrity.did-you-mean",
  ],
  [
    "test:protocol.authored-honesty.section-authored-fact",
    "verifies",
    "spec:validation.authored-honesty.section-authored-fact",
  ],
  [
    "test:protocol.authored-honesty.unearned-stated-fact",
    "verifies",
    "spec:validation.authored-honesty.unearned-stated-fact",
  ],
  [
    "test:protocol.claim-separation.collapsed-edge-claim",
    "verifies",
    "spec:validation.claim-separation.collapsed-edge-claim",
  ],
  [
    "test:protocol.claim-separation.unratified-descriptor",
    "verifies",
    "spec:validation.claim-separation.unratified-descriptor",
  ],
  [
    "test:protocol.verification-linkage.unbound-example",
    "verifies",
    "spec:validation.verification-linkage.unbound-example",
  ],
  [
    "test:protocol.verification-linkage.unresolved-oracle",
    "verifies",
    "spec:validation.verification-linkage.unresolved-oracle",
  ],
  [
    "test:protocol.pack-coherence.incoherent-aggregate",
    "verifies",
    "spec:validation.pack-coherence.incoherent-aggregate",
  ],
  [
    "test:protocol.excludes.segment-boundary",
    "verifies",
    "spec:extraction.excludes.segment-boundary",
  ],
  ["test:protocol.excludes.refused-path", "verifies", "spec:extraction.excludes.refused-path"],
  [
    "test:protocol.schema-versioning.declared-version",
    "verifies",
    "spec:extraction.schema-versioning.declared-version",
  ],
  [
    "test:protocol.stable-ids.namespaced-round-trip",
    "verifies",
    "spec:model.stable-ids.namespaced-round-trip",
  ],
  [
    "test:protocol.stable-ids.malformed-refusal",
    "verifies",
    "spec:model.stable-ids.malformed-refusal",
  ],
  [
    "test:protocol.stable-ids.unsectioned-address-refused",
    "verifies",
    "spec:model.stable-ids.unsectioned-address-refused",
  ],
  [
    "test:protocol.markdown-parser.bounded-parity",
    "verifies",
    "spec:carrier.markdown-parser.bounded-parity",
  ],
  [
    "test:protocol.gherkin-authoring.authored-fact-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.authored-fact-refused",
  ],
  [
    "test:protocol.gherkin-authoring.contract-parity",
    "verifies",
    "spec:carrier.gherkin-authoring.contract-parity",
  ],
  [
    "test:protocol.gherkin-authoring.duplicate-surface-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.duplicate-surface-refused",
  ],
  [
    "test:protocol.gherkin-authoring.example-space-extraction",
    "verifies",
    "spec:carrier.gherkin-authoring.example-space-extraction",
  ],
  [
    "test:protocol.gherkin-authoring.malformed-relation-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.malformed-relation-refused",
  ],
  [
    "test:protocol.gherkin-authoring.missing-id-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.missing-id-refused",
  ],
  [
    "test:protocol.gherkin-authoring.parent-child-extraction",
    "verifies",
    "spec:carrier.gherkin-authoring.parent-child-extraction",
  ],
  [
    "test:protocol.gherkin-authoring.unbound-ready-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.unbound-ready-refused",
  ],
  [
    "test:protocol.gherkin-authoring.unknown-tag-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.unknown-tag-refused",
  ],
  [
    "test:protocol.gherkin-authoring.unsupported-construct-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.unsupported-construct-refused",
  ],
  [
    "test:protocol.gherkin-authoring.description-location-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.description-location-refused",
  ],
  [
    "test:protocol.gherkin-authoring.step-less-scenario-refused",
    "verifies",
    "spec:carrier.gherkin-authoring.step-less-scenario-refused",
  ],
  [
    "test:protocol.gherkin-authoring.multi-finding-bounded",
    "verifies",
    "spec:carrier.gherkin-authoring.multi-finding-bounded",
  ],
  ["test:protocol.sdp-import.round-trip", "verifies", "spec:carrier.sdp-import.round-trip"],
  ["impl:protocol.anchor-extraction", "satisfies", "spec:model.anchors"],
  ["impl:protocol.anchor-model", "satisfies", "spec:model.anchors"],
  ["impl:protocol.pack-aggregate", "satisfies", "spec:model.pack-aggregate"],
  ["impl:protocol.spec-descriptors", "satisfies", "spec:model.core-model"],
  ["impl:protocol.spec-primitive", "satisfies", "spec:model.core-model"],
  ["impl:protocol.spec-relations", "satisfies", "spec:model.relations"],
  ["impl:protocol.spec-sections", "satisfies", "spec:model.spec-sections"],
  ["impl:protocol.stable-ids", "satisfies", "spec:model.stable-ids"],
  ["impl:protocol.verifier-semantics", "satisfies", "spec:model.spec-sections"],
  ["impl:protocol.validation-families", "satisfies", "spec:validation.two-check-families"],
  ["impl:protocol.projections-model", "satisfies", "spec:consumers.projections-model"],
  ["impl:protocol.agent-surface", "satisfies", "spec:consumers.agent-surface"],
  ["impl:protocol.reader-impact", "satisfies", "spec:consumers.reader"],
  ["impl:protocol.reader", "satisfies", "spec:consumers.reader"],
  ["impl:protocol.design-review", "satisfies", "spec:consumers.design-review"],
  ["impl:protocol.census-page", "satisfies", "spec:consumers.census-page"],
  ["impl:protocol.mermaid-view", "satisfies", "spec:consumers.mermaid-view"],
  ["impl:protocol.gherkin-view", "satisfies", "spec:consumers.gherkin-view"],
  ["test:protocol.gherkin-view", "verifies", "spec:consumers.gherkin-view"],
  ["impl:protocol.exclusion-surface", "satisfies", "spec:extraction.excludes"],
  ["impl:protocol.graph-claims", "satisfies", "spec:extraction.claim-taxonomy"],
  ["impl:protocol.regenerability", "satisfies", "spec:extraction.regenerability"],
  ["impl:protocol.schema-version", "satisfies", "spec:extraction.schema-versioning"],
  ["impl:protocol.executable-contracts", "satisfies", "spec:extraction.executable-contracts"],
  ["impl:protocol.example-runner", "satisfies", "spec:extraction.example-runner"],
  ["impl:protocol.slot-notation", "satisfies", "spec:carrier.slot-notation"],
  [
    "test:protocol.executable-contracts.concreteness-refusal",
    "verifies",
    "spec:extraction.executable-contracts.concreteness-refusal",
  ],
  [
    "test:protocol.executable-contracts.multi-entry-example",
    "verifies",
    "spec:extraction.executable-contracts.multi-entry-example",
  ],
  [
    "test:protocol.executable-contracts.case-colliding-path",
    "verifies",
    "spec:extraction.executable-contracts.case-colliding-path",
  ],
  [
    "test:protocol.example-runner.step-order",
    "verifies",
    "spec:extraction.example-runner.step-order",
  ],
  [
    "test:protocol.example-runner.red-step-naming",
    "verifies",
    "spec:extraction.example-runner.red-step-naming",
  ],
  [
    "test:protocol.slot-notation.typed-declaration",
    "verifies",
    "spec:carrier.slot-notation.typed-declaration",
  ],
  [
    "test:protocol.slot-notation.refused-guess",
    "verifies",
    "spec:carrier.slot-notation.refused-guess",
  ],
  ["test:protocol.anchors.lookalike-refusal", "verifies", "spec:model.anchors.lookalike-refusal"],
  ["test:protocol.anchors.physical-identity", "verifies", "spec:model.anchors.physical-identity"],
  [
    "test:protocol.two-check-families.split-report",
    "verifies",
    "spec:validation.two-check-families.split-report",
  ],
  [
    "test:protocol.derived-readiness-banner.dishonest-divergence",
    "verifies",
    "spec:consumers.derived-readiness-banner.dishonest-divergence",
  ],
  [
    "test:protocol.derived-readiness-banner.honest-headroom",
    "verifies",
    "spec:consumers.derived-readiness-banner.honest-headroom",
  ],
  [
    "test:protocol.binding-language-views.bound-spec-page",
    "verifies",
    "spec:consumers.binding-language-views.bound-spec-page",
  ],
  [
    "test:protocol.binding-language-views.pack-member-table",
    "verifies",
    "spec:consumers.binding-language-views.pack-member-table",
  ],
  [
    "test:protocol.wholesale-view-rewrite.stale-page-removed",
    "verifies",
    "spec:consumers.wholesale-view-rewrite.stale-page-removed",
  ],
  [
    "test:protocol.wholesale-view-rewrite.late-stale-page",
    "verifies",
    "spec:consumers.wholesale-view-rewrite.late-stale-page",
  ],
  [
    "test:protocol.wholesale-view-rewrite.failed-run-view-removed",
    "verifies",
    "spec:consumers.wholesale-view-rewrite.failed-run-view-removed",
  ],
  [
    "test:protocol.wholesale-view-rewrite.build-invalidates-view",
    "verifies",
    "spec:consumers.wholesale-view-rewrite.build-invalidates-view",
  ],
  [
    "test:protocol.diagnostic-rendering.composed-location",
    "verifies",
    "spec:validation.diagnostic-rendering.composed-location",
  ],
  [
    "test:protocol.diagnostic-rendering.table-cell-location",
    "verifies",
    "spec:validation.diagnostic-rendering.table-cell-location",
  ],
  [
    "test:protocol.design-review.pure-projection",
    "verifies",
    "spec:consumers.design-review.pure-projection",
  ],
  [
    "test:protocol.agent-surface.scripted-context-body",
    "verifies",
    "spec:consumers.agent-surface.scripted-context-body",
  ],
  [
    "test:protocol.agent-surface.demand-map-entries",
    "verifies",
    "spec:consumers.agent-surface.demand-map-entries",
  ],
  ["test:protocol.reader.concept-entry", "verifies", "spec:consumers.reader.concept-entry"],
  ["test:protocol.reader.file-entry", "verifies", "spec:consumers.reader.file-entry"],
  ["test:protocol.reader.changeset-entry", "verifies", "spec:consumers.reader.changeset-entry"],
  ["impl:protocol.sdp-import", "satisfies", "spec:carrier.sdp-import"],
  ["impl:protocol.extraction-determinism", "satisfies", "spec:extraction.determinism"],
  [
    "impl:protocol.wholesale-view-build-invalidation",
    "satisfies",
    "spec:consumers.wholesale-view-rewrite",
  ],
  ["impl:protocol.wholesale-view-rewrite", "satisfies", "spec:consumers.wholesale-view-rewrite"],
  [
    "impl:protocol.derived-readiness-banner",
    "satisfies",
    "spec:consumers.derived-readiness-banner",
  ],
  [
    "impl:protocol.binding-language-spec-page",
    "satisfies",
    "spec:consumers.binding-language-views",
  ],
  [
    "impl:protocol.diagnostic-rendering-design-review",
    "satisfies",
    "spec:validation.diagnostic-rendering",
  ],
  [
    "impl:protocol.binding-language-pack-table",
    "satisfies",
    "spec:consumers.binding-language-views",
  ],
  [
    "impl:protocol.binding-language-index-table",
    "satisfies",
    "spec:consumers.binding-language-views",
  ],
  ["impl:protocol.diagnostic-rendering-cli", "satisfies", "spec:validation.diagnostic-rendering"],
  ["impl:protocol.kind-evidence", "satisfies", "spec:validation.kind-evidence"],
  ["impl:protocol.referential-integrity", "satisfies", "spec:validation.referential-integrity"],
  ["impl:protocol.claim-separation", "satisfies", "spec:validation.claim-separation"],
  ["impl:protocol.verifies-linkage", "satisfies", "spec:validation.verification-linkage"],
  ["impl:protocol.oracle-linkage", "satisfies", "spec:validation.verification-linkage"],
  ["impl:protocol.pack-coherence", "satisfies", "spec:validation.pack-coherence"],
  ["impl:protocol.orphan-signal", "satisfies", "spec:validation.warn-level-signals"],
  ["impl:protocol.authored-honesty-shape", "satisfies", "spec:validation.authored-honesty"],
  [
    "impl:protocol.authored-honesty-delivery-facts",
    "satisfies",
    "spec:validation.authored-honesty",
  ],
  ["impl:protocol.verifier-gap-signal", "satisfies", "spec:validation.warn-level-signals"],
  ["oracle:protocol.reader-entry-map", "models", "spec:consumers.reader"],
  [
    "impl:protocol.oracle-target-eligibility",
    "satisfies",
    "spec:validation.oracle-target-eligibility",
  ],
  [
    "test:protocol.oracle-target-eligibility.rule-space-accepted",
    "verifies",
    "spec:validation.oracle-target-eligibility.rule-space-accepted",
  ],
  ["test:protocol.mermaid-view", "verifies", "spec:consumers.mermaid-view"],
  [
    "test:protocol.oracle-target-eligibility.missing-space-refused",
    "verifies",
    "spec:validation.oracle-target-eligibility.missing-space-refused",
  ],
  [
    "oracle:protocol.oracle-target-eligibility",
    "models",
    "spec:validation.oracle-target-eligibility",
  ],
  ["impl:protocol.markdown-pack-authoring", "satisfies", "spec:carrier.markdown-pack-authoring"],
  [
    "test:protocol.markdown-pack-authoring.markdown-ts-parity",
    "verifies",
    "spec:carrier.markdown-pack-authoring.markdown-ts-parity",
  ],
  [
    "test:protocol.markdown-pack-authoring.spec-envelope-refused",
    "verifies",
    "spec:carrier.markdown-pack-authoring.spec-envelope-refused",
  ],
  ["impl:protocol.build-pipeline-query", "satisfies", "spec:extraction.build-pipeline"],
  ["impl:protocol.build-pipeline-emit", "satisfies", "spec:extraction.build-pipeline"],
  ["impl:protocol.example-runner-adapter", "satisfies", "spec:extraction.example-runner"],
  ["impl:protocol.runnable-modules", "satisfies", "spec:extraction.runnable-modules"],
  ["test:protocol.census-page", "verifies", "spec:consumers.census-page"],
  ["test:protocol.runnable-modules", "verifies", "spec:extraction.runnable-modules"],
  ["impl:protocol.sdp-import-core", "satisfies", "spec:carrier.sdp-import"],
  ["impl:protocol.sdp-import-markdown-emit", "satisfies", "spec:carrier.sdp-import"],
  ["impl:protocol.example-testing-helpers", "satisfies", "spec:extraction.example-runner"],
  ["impl:protocol.discover-files", "satisfies", "spec:extraction.excludes"],
  ["impl:protocol.protocol-bindings", "satisfies", "spec:model.anchors"],
  ["impl:protocol.static-reification", "satisfies", "spec:extraction.determinism"],
  ["impl:protocol.carrier-reification", "satisfies", "spec:extraction.derive-graph"],
  ["impl:protocol.spec-scaffolder", "satisfies", "spec:consumers.authoring-on-ramp"],
  ["impl:protocol.delivery-facts", "satisfies", "spec:extraction.delivery-facts"],
  ["impl:protocol.example-space", "satisfies", "spec:extraction.executable-contracts"],
  ["impl:protocol.graph-index", "satisfies", "spec:validation.two-check-families"],
  ["impl:protocol.validation-contracts", "satisfies", "spec:validation.two-check-families"],
  ["impl:protocol.agent-surface-cli", "satisfies", "spec:consumers.agent-surface"],
  ["impl:protocol.census-page-cli", "satisfies", "spec:consumers.census-page"],
  ["impl:protocol.mermaid-view-cli", "satisfies", "spec:consumers.mermaid-view"],
  ["impl:protocol.gherkin-view-cli", "satisfies", "spec:consumers.gherkin-view"],
  [
    "test:protocol.markdown-body-grammar.table-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.table-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.continuation-line-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.continuation-line-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.ordered-list-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.ordered-list-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.foreign-fence-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.foreign-fence-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.h3-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.h3-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.plain-bullet-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.plain-bullet-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.keyed-bullet-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.keyed-bullet-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.trailing-prose-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.trailing-prose-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.repeated-field-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.repeated-field-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.unrecognized-heading-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.unrecognized-heading-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.second-primary-owner-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.second-primary-owner-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.raw-html-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.raw-html-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.shared-description-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.shared-description-refused",
  ],
  [
    "test:protocol.markdown-body-grammar.integer-term-refused",
    "verifies",
    "spec:carrier.markdown-body-grammar.integer-term-refused",
  ],
  ["impl:protocol.markdown-body-grammar", "satisfies", "spec:carrier.markdown-body-grammar"],
  ["impl:protocol.inline-code-spans", "satisfies", "spec:carrier.inline-code-spans"],
  ["oracle:protocol.inline-code-spans", "models", "spec:carrier.inline-code-spans"],
  [
    "test:protocol.inline-code-spans.narrative",
    "verifies",
    "spec:carrier.inline-code-spans.narrative",
  ],
  [
    "test:protocol.inline-code-spans.description",
    "verifies",
    "spec:carrier.inline-code-spans.description",
  ],
  ["test:protocol.inline-code-spans.list", "verifies", "spec:carrier.inline-code-spans.list"],
  ["test:protocol.inline-code-spans.pack", "verifies", "spec:carrier.inline-code-spans.pack"],
  ["impl:protocol.unbound-example-posture", "satisfies", "spec:validation.unbound-example-posture"],
  ["oracle:protocol.unbound-example-posture", "models", "spec:validation.unbound-example-posture"],
  [
    "test:protocol.unbound-example-posture.lower-rungs",
    "verifies",
    "spec:validation.unbound-example-posture.lower-rungs",
  ],
  [
    "test:protocol.unbound-example-posture.warning-cases",
    "verifies",
    "spec:validation.unbound-example-posture.warning-cases",
  ],
  [
    "test:protocol.unbound-example-posture.parent-traces",
    "verifies",
    "spec:validation.unbound-example-posture.parent-traces",
  ],
  ["impl:protocol.typed-dependency-floor", "satisfies", "spec:validation.typed-dependency-floor"],
  ["oracle:protocol.typed-dependency-floor", "models", "spec:validation.typed-dependency-floor"],
  [
    "test:protocol.typed-dependency-floor.relation-rungs",
    "verifies",
    "spec:validation.typed-dependency-floor.relation-rungs",
  ],
  [
    "test:protocol.typed-dependency-floor.missing-targets",
    "verifies",
    "spec:validation.typed-dependency-floor.missing-targets",
  ],
  [
    "test:protocol.typed-dependency-floor.unsettled-fact",
    "verifies",
    "spec:validation.typed-dependency-floor.unsettled-fact",
  ],
  [
    "test:protocol.typed-dependency-floor.stated-readiness",
    "verifies",
    "spec:validation.typed-dependency-floor.stated-readiness",
  ],
  ["impl:protocol.register-recipes", "satisfies", "spec:consumers.agent-surface.register-recipes"],
  ["test:protocol.register-recipes", "verifies", "spec:consumers.agent-surface.register-recipes"],
  ["impl:protocol.adopter-on-ramp", "satisfies", "spec:consumers.adopter-on-ramp"],
  ["test:protocol.adopter-on-ramp", "verifies", "spec:consumers.adopter-on-ramp"],
  ["impl:protocol.shipped-protocol-corpus", "satisfies", "spec:consumers.shipped-protocol-corpus"],
  ["test:protocol.shipped-protocol-corpus", "verifies", "spec:consumers.shipped-protocol-corpus"],
  ["impl:protocol.prose-mentions", "satisfies", "spec:validation.prose-mentions"],
  ["test:protocol.prose-mentions", "verifies", "spec:validation.prose-mentions"],
  ["impl:protocol.pack-member-order", "satisfies", "spec:extraction.pack-member-order"],
  ["impl:protocol.open-question-keys", "satisfies", "spec:model.open-question-keys"],
  ["impl:protocol.next-rung-floor", "satisfies", "spec:validation.next-rung-floor"],
  [
    "impl:protocol.address-and-cycle-recipes",
    "satisfies",
    "spec:consumers.agent-surface.address-and-cycle-recipes",
  ],
  [
    "test:protocol.address-and-cycle-recipes",
    "verifies",
    "spec:consumers.agent-surface.address-and-cycle-recipes",
  ],
  ["oracle:protocol.next-rung-floor", "models", "spec:validation.next-rung-floor"],
  [
    "test:protocol.next-rung-floor.typed-dependency-targets",
    "verifies",
    "spec:validation.next-rung-floor.typed-dependency-targets",
  ],
  [
    "test:protocol.next-rung-floor.blocking-question",
    "verifies",
    "spec:validation.next-rung-floor.blocking-question",
  ],
  ["oracle:protocol.open-question-keys", "models", "spec:model.open-question-keys"],
  [
    "test:protocol.open-question-keys.keyed-question-resolves",
    "verifies",
    "spec:model.open-question-keys.keyed-question-resolves",
  ],
  [
    "test:protocol.open-question-keys.renamed-key-breaks",
    "verifies",
    "spec:model.open-question-keys.renamed-key-breaks",
  ],
  [
    "test:protocol.open-question-keys.repeated-key-refused",
    "verifies",
    "spec:model.open-question-keys.repeated-key-refused",
  ],
  [
    "test:protocol.pack-member-order",
    "verifies",
    "spec:extraction.pack-member-order.manifest-order-kept",
  ],
  ["impl:protocol.reader", "references", "spec:consumers.spec-studio.data"],
  ["impl:protocol.reader", "references", "spec:consumers.spec-studio"],
  ["impl:protocol.agent-surface", "references", "spec:consumers.spec-studio.shell"],
  ["impl:protocol.projections-model", "references", "spec:consumers.spec-studio"],
  ["impl:protocol.design-review", "references", "spec:decisions.studio-html-surface"],
  ["impl:protocol.derived-readiness-banner", "references", "spec:consumers.spec-studio.spec-page"],
  [
    "impl:protocol.binding-language-spec-page",
    "references",
    "spec:consumers.spec-studio.spec-page",
  ],
  [
    "impl:protocol.binding-language-spec-page",
    "references",
    "spec:consumers.spec-studio.verification-panels",
  ],
  [
    "impl:protocol.diagnostic-rendering-design-review",
    "references",
    "spec:consumers.spec-studio.components",
  ],
  ["impl:protocol.binding-language-pack-table", "references", "spec:consumers.spec-studio.lenses"],
  ["impl:protocol.binding-language-index-table", "references", "spec:consumers.spec-studio.lenses"],
  ["impl:protocol.census-page", "references", "spec:consumers.spec-studio.lenses"],
  ["impl:protocol.mermaid-view", "references", "spec:consumers.spec-studio.components"],
  ["impl:protocol.wholesale-view-rewrite", "references", "spec:consumers.spec-studio"],
] as const;

// re-measured under plan 40
export const expectedCommentAnchorIds = [
  "impl:protocol.reader-impact",
  "component:protocol.reader",
  "impl:protocol.agent-surface",
  "impl:protocol.reader",
  "impl:protocol.census-page",
  "impl:protocol.derived-readiness-banner",
  "impl:protocol.binding-language-spec-page",
  "impl:protocol.diagnostic-rendering-design-review",
  "impl:protocol.binding-language-pack-table",
  "impl:protocol.binding-language-index-table",
  "component:protocol.projections",
  "impl:protocol.projections-model",
  "impl:protocol.design-review",
  "impl:protocol.gherkin-view",
  "impl:protocol.mermaid-view",
  "impl:protocol.agent-surface-cli",
] as const;
