// The authored anchors of the self-hosting corpus — a binding assertion each, identity only and
// never intent. `constant` names the anchor declaration and `site` the code it binds, so the
// suite can resolve both lines in the real file rather than trusting a transcribed line number.

export const expectedAnchors = [
  {
    id: "impl:protocol.extract",
    nodeType: "CodeNode",
    label: "extracts authored carriers and bindings into one graph",
    type: "satisfies",
    target: "spec:extraction.derive-graph",
    file: "src/extract/index.ts",
    constant: "extractAnchor",
    site: "export function extract",
  },
  {
    id: "impl:protocol.derive-graph",
    nodeType: "CodeNode",
    label: "derives the graph from reified carriers and bindings",
    type: "satisfies",
    target: "spec:extraction.derive-graph",
    file: "src/extract/derive.ts",
    constant: "deriveGraphAnchor",
    site: "export function deriveGraph",
  },
  {
    id: "test:protocol.extract",
    nodeType: "Anchor",
    label: "extraction contracts verify graph derivation",
    type: "verifies",
    target: "spec:extraction.derive-graph",
    file: "test/extract.test.ts",
    constant: "extractContractTestAnchor",
    site: 'describe("anchor extraction corpora",',
  },
  {
    id: "test:protocol.extraction-determinism",
    nodeType: "Anchor",
    label: "clean-repo pipeline determinism verifies byte-identical output",
    type: "verifies",
    target: "spec:extraction.determinism",
    file: "test/cli.test.ts",
    constant: "cleanRepoDeterminismTestAnchor",
    site: 'it("clean-repo determinism: the full pipeline at a different absolute path is byte-identical"',
  },
  {
    id: "test:protocol.build-pipeline.same-invocation",
    nodeType: "Anchor",
    label: "the same-invocation point verifies the query extraction and validation seam",
    type: "verifies",
    target: "spec:extraction.build-pipeline.same-invocation",
    file: "test/self-hosting-extraction.test.ts",
    constant: "buildPipelineSameInvocationTestAnchor",
    site: "bindExample(sameInvocationContract",
  },
  {
    id: "impl:protocol.authoring-on-ramp",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped graph-first authoring skill document",
    type: "satisfies",
    target: "spec:consumers.authoring-on-ramp",
    file: "test/skills.test.ts",
    constant: "authoringOnRampImplementationAnchor",
    site: "function readSkill",
  },
  {
    id: "impl:protocol.delivery-session-on-ramp",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped advisory delivery-session skill document",
    type: "satisfies",
    target: "spec:consumers.delivery-session-on-ramp",
    file: "test/skills.test.ts",
    constant: "deliverySessionOnRampImplementationAnchor",
    site: "function readSkill",
  },
  {
    id: "impl:protocol.authoring-recipes",
    nodeType: "CodeNode",
    label: "asserts realization of the shipped authoring recipe catalog",
    type: "satisfies",
    target: "spec:consumers.agent-surface.authoring-recipes",
    file: "test/skills.test.ts",
    constant: "authoringRecipesImplementationAnchor",
    site: "function documentedCommands",
  },
  {
    id: "test:protocol.authoring-on-ramp",
    nodeType: "Anchor",
    label: "skill-asset checks verify the authoring on-ramp",
    type: "verifies",
    target: "spec:consumers.authoring-on-ramp",
    file: "test/skills.test.ts",
    constant: "authoringOnRampTestAnchor",
    site: 'describe("Protocol skill assets"',
  },
  {
    id: "test:protocol.delivery-session-on-ramp",
    nodeType: "Anchor",
    label: "skill-asset checks verify advisory delivery-session routing",
    type: "verifies",
    target: "spec:consumers.delivery-session-on-ramp",
    file: "test/skills.test.ts",
    constant: "deliverySessionOnRampTestAnchor",
    site: 'describe("Protocol skill assets"',
  },
  {
    id: "test:protocol.authoring-recipes",
    nodeType: "Anchor",
    label: "skill-asset checks verify the authoring recipes",
    type: "verifies",
    target: "spec:consumers.agent-surface.authoring-recipes",
    file: "test/skills.test.ts",
    constant: "authoringRecipesTestAnchor",
    site: 'describe("Protocol skill assets"',
  },
  {
    id: "impl:protocol.readiness-floor",
    nodeType: "CodeNode",
    label: "evaluates the stated readiness floor against the graph",
    type: "satisfies",
    target: "spec:validation.readiness-floor",
    file: "src/validate/readiness-floor.ts",
    constant: "readinessFloorAnchor",
    site: "export function evaluateReadinessFloor",
  },
  {
    id: "test:protocol.readiness-floor",
    nodeType: "Anchor",
    label: "readiness-floor contracts verify stated maturity",
    type: "verifies",
    target: "spec:validation.readiness-floor",
    file: "test/readiness.test.ts",
    constant: "readinessFloorTestAnchor",
    site: 'describe("readiness and validation contracts",',
  },
  {
    id: "impl:protocol.markdown-authoring",
    nodeType: "CodeNode",
    label: "reifies Markdown authoring into the one carrier path",
    type: "satisfies",
    target: "spec:carrier.markdown-authoring",
    file: "src/extract/markdown.ts",
    constant: "markdownAuthoringAnchor",
    site: "export function reifyMarkdownCarrier",
  },
  {
    id: "impl:protocol.gherkin-authoring",
    nodeType: "CodeNode",
    label: "reifies Gherkin behavior and example authoring into the one carrier path",
    type: "satisfies",
    target: "spec:carrier.gherkin-authoring",
    file: "src/extract/gherkin.ts",
    constant: "gherkinAuthoringAnchor",
    site: "export function reifyGherkinCarrier",
  },
  {
    id: "impl:protocol.markdown-parser",
    nodeType: "CodeNode",
    label: "reifies the ruled Markdown parser input",
    type: "satisfies",
    target: "spec:carrier.markdown-parser",
    file: "src/extract/markdown.ts",
    constant: "markdownParserAnchor",
    site: "export function reifyMarkdownCarrier",
  },
  {
    id: "test:protocol.markdown-parser",
    nodeType: "Anchor",
    label: "Markdown reifier tests verify the ruled parser",
    type: "verifies",
    target: "spec:carrier.markdown-parser",
    file: "test/markdown-reifier.test.ts",
    constant: "markdownParserTestAnchor",
    site: 'describe("Markdown frontmatter reifier",',
  },
  {
    id: "impl:protocol.envelope-contract",
    nodeType: "CodeNode",
    label: "parses the bounded Markdown frontmatter envelope",
    type: "satisfies",
    target: "spec:carrier.envelope-contract",
    file: "src/extract/markdown.ts",
    constant: "envelopeContractAnchor",
    site: "export function parseMarkdownFrontmatter",
  },
  {
    id: "test:protocol.envelope-contract",
    nodeType: "Anchor",
    label: "frontmatter contract tests verify the Markdown envelope",
    type: "verifies",
    target: "spec:carrier.envelope-contract",
    file: "test/markdown-reifier.test.ts",
    constant: "envelopeContractTestAnchor",
    site: 'describe("Markdown frontmatter reifier",',
  },
  {
    id: "impl:protocol.prose-ownership",
    nodeType: "CodeNode",
    label: "reads Markdown body content through its prose owners",
    type: "satisfies",
    target: "spec:carrier.prose-ownership-rule",
    file: "src/extract/markdown.ts",
    constant: "proseOwnershipAnchor",
    site: "export function readMarkdownBody",
  },
  {
    id: "test:protocol.prose-ownership",
    nodeType: "Anchor",
    label: "Markdown reifier tests verify prose ownership",
    type: "verifies",
    target: "spec:carrier.prose-ownership-rule",
    file: "test/markdown-reifier.test.ts",
    constant: "proseOwnershipTestAnchor",
    site: 'describe("Markdown frontmatter reifier",',
  },
  {
    id: "impl:protocol.duplicate-id-exclusion",
    nodeType: "CodeNode",
    label: "excludes duplicated carrier ids from the graph",
    type: "satisfies",
    target: "spec:validation.duplicate-ids",
    file: "src/extract/index.ts",
    constant: "duplicateIdExclusionAnchor",
    site: "function findDuplicatedIds",
  },
  {
    id: "test:protocol.duplicate-ids.dual-carrier",
    nodeType: "Anchor",
    label: "dual-carrier duplicate-ID contract verifies carrier exclusion",
    type: "verifies",
    target: "spec:validation.duplicate-ids.dual-carrier",
    file: "test/self-hosting-duplicate-ids.test.ts",
    constant: "dualCarrierDuplicateTestAnchor",
    site: "bindExample(",
  },
  {
    id: "test:protocol.warn-level-signals.orphan-signal",
    nodeType: "Anchor",
    label: "the orphan point verifies the disconnected-spec warning",
    type: "verifies",
    target: "spec:validation.warn-level-signals.orphan-signal",
    file: "test/self-hosting-validators.test.ts",
    constant: "warnLevelOrphanTestAnchor",
    site: "bindExample(orphanSignalContract",
  },
  {
    id: "test:protocol.warn-level-signals.ready-gap-signal",
    nodeType: "Anchor",
    label: "the gap point verifies the unverified-ready warning",
    type: "verifies",
    target: "spec:validation.warn-level-signals.ready-gap-signal",
    file: "test/self-hosting-validators.test.ts",
    constant: "warnLevelGapTestAnchor",
    site: "bindExample(readyGapSignalContract",
  },
  {
    id: "test:protocol.readiness-floor.unrelated-scoped-spec",
    nodeType: "Anchor",
    label: "the unrelated-scoped point verifies the relation clause of the scoped rung",
    type: "verifies",
    target: "spec:validation.readiness-floor.unrelated-scoped-spec",
    file: "test/self-hosting-validators.test.ts",
    constant: "unrelatedScopedSpecTestAnchor",
    site: "bindExample(unrelatedScopedSpecContract",
  },
  {
    id: "test:protocol.readiness-floor.blocking-open-question",
    nodeType: "Anchor",
    label: "the blocked-question point verifies the open-questions clause of the defined rung",
    type: "verifies",
    target: "spec:validation.readiness-floor.blocking-open-question",
    file: "test/self-hosting-validators.test.ts",
    constant: "blockingOpenQuestionTestAnchor",
    site: "bindExample(blockingOpenQuestionContract",
  },
  {
    id: "test:protocol.kind-evidence.constraints-alone",
    nodeType: "Anchor",
    label: "the constraints-alone point verifies the behavior-family complete cell",
    type: "verifies",
    target: "spec:validation.kind-evidence.constraints-alone",
    file: "test/self-hosting-validators.test.ts",
    constant: "constraintsAloneTestAnchor",
    site: "bindExample(constraintsAloneContract",
  },
  {
    id: "test:protocol.kind-evidence.untargeted-constraint",
    nodeType: "Anchor",
    label: "the untargeted-constraint point verifies the constraint row's target requirement",
    type: "verifies",
    target: "spec:validation.kind-evidence.untargeted-constraint",
    file: "test/self-hosting-validators.test.ts",
    constant: "untargetedConstraintTestAnchor",
    site: "bindExample(untargetedConstraintContract",
  },
  {
    id: "test:protocol.kind-evidence.empty-promoted-child",
    nodeType: "Anchor",
    label: "the empty-promotion point verifies the promoted-evidence honesty bound",
    type: "verifies",
    target: "spec:validation.kind-evidence.empty-promoted-child",
    file: "test/self-hosting-validators.test.ts",
    constant: "emptyPromotedChildTestAnchor",
    site: "bindExample(emptyPromotedChildContract",
  },
  {
    id: "test:protocol.referential-integrity.dangling-target",
    nodeType: "Anchor",
    label: "the dangling-target point verifies the unresolved-reference error",
    type: "verifies",
    target: "spec:validation.referential-integrity.dangling-target",
    file: "test/self-hosting-validators.test.ts",
    constant: "danglingTargetTestAnchor",
    site: "bindExample(danglingTargetContract",
  },
  {
    id: "test:protocol.referential-integrity.did-you-mean",
    nodeType: "Anchor",
    label: "the near-miss point verifies the unique did-you-mean suggestion",
    type: "verifies",
    target: "spec:validation.referential-integrity.did-you-mean",
    file: "test/self-hosting-validators.test.ts",
    constant: "didYouMeanTestAnchor",
    site: "bindExample(didYouMeanContract",
  },
  {
    id: "test:protocol.authored-honesty.section-authored-fact",
    nodeType: "Anchor",
    label: "the section point verifies the authoring-shape refusal",
    type: "verifies",
    target: "spec:validation.authored-honesty.section-authored-fact",
    file: "test/self-hosting-validators.test.ts",
    constant: "sectionAuthoredFactTestAnchor",
    site: "bindExample(sectionAuthoredFactContract",
  },
  {
    id: "test:protocol.authored-honesty.unearned-stated-fact",
    nodeType: "Anchor",
    label: "the stated-fact point verifies the delivery-fact refusal",
    type: "verifies",
    target: "spec:validation.authored-honesty.unearned-stated-fact",
    file: "test/self-hosting-validators.test.ts",
    constant: "unearnedStatedFactTestAnchor",
    site: "bindExample(unearnedStatedFactContract",
  },
  {
    id: "test:protocol.claim-separation.collapsed-edge-claim",
    nodeType: "Anchor",
    label: "the collapsed-claim point verifies the binding-edge contract row",
    type: "verifies",
    target: "spec:validation.claim-separation.collapsed-edge-claim",
    file: "test/self-hosting-validators.test.ts",
    constant: "collapsedEdgeClaimTestAnchor",
    site: "bindExample(collapsedEdgeClaimContract",
  },
  {
    id: "test:protocol.claim-separation.unratified-descriptor",
    nodeType: "Anchor",
    label: "the unratified-kind point verifies the fail-closed descriptor law",
    type: "verifies",
    target: "spec:validation.claim-separation.unratified-descriptor",
    file: "test/self-hosting-validators.test.ts",
    constant: "unratifiedDescriptorTestAnchor",
    site: "bindExample(unratifiedDescriptorContract",
  },
  {
    id: "test:protocol.verification-linkage.unbound-example",
    nodeType: "Anchor",
    label: "the unbound-example point verifies the incomplete spec-to-test trace",
    type: "verifies",
    target: "spec:validation.verification-linkage.unbound-example",
    file: "test/self-hosting-validators.test.ts",
    constant: "unboundExampleTestAnchor",
    site: "bindExample(unboundExampleContract",
  },
  {
    id: "test:protocol.verification-linkage.unresolved-oracle",
    nodeType: "Anchor",
    label: "the unresolved-oracle point verifies the oracle binding refusal",
    type: "verifies",
    target: "spec:validation.verification-linkage.unresolved-oracle",
    file: "test/self-hosting-validators.test.ts",
    constant: "unresolvedOracleTestAnchor",
    site: "bindExample(unresolvedOracleContract",
  },
  {
    id: "test:protocol.pack-coherence.incoherent-aggregate",
    nodeType: "Anchor",
    label: "the incoherent-aggregate point verifies both halves of the pack law",
    type: "verifies",
    target: "spec:validation.pack-coherence.incoherent-aggregate",
    file: "test/self-hosting-validators.test.ts",
    constant: "incoherentAggregateTestAnchor",
    site: "bindExample(incoherentAggregateContract",
  },
  {
    id: "test:protocol.excludes.segment-boundary",
    nodeType: "Anchor",
    label: "the segment-boundary point verifies the exact-prefix exclusion rule",
    type: "verifies",
    target: "spec:extraction.excludes.segment-boundary",
    file: "test/self-hosting-extraction.test.ts",
    constant: "excludesSegmentBoundaryTestAnchor",
    site: "bindExample(segmentBoundaryContract",
  },
  {
    id: "test:protocol.excludes.refused-path",
    nodeType: "Anchor",
    label: "the refused-path point verifies the malformed-exclusion refusal",
    type: "verifies",
    target: "spec:extraction.excludes.refused-path",
    file: "test/self-hosting-extraction.test.ts",
    constant: "excludesRefusedPathTestAnchor",
    site: "bindExample(refusedPathContract",
  },
  {
    id: "test:protocol.schema-versioning.declared-version",
    nodeType: "Anchor",
    label: "the declared-version point verifies the readable payload version",
    type: "verifies",
    target: "spec:extraction.schema-versioning.declared-version",
    file: "test/self-hosting-extraction.test.ts",
    constant: "schemaVersioningTestAnchor",
    site: "bindExample(declaredVersionContract",
  },
  {
    id: "test:protocol.stable-ids.namespaced-round-trip",
    nodeType: "Anchor",
    label: "the round-trip point verifies the namespaced dotted-path grammar",
    type: "verifies",
    target: "spec:model.stable-ids.namespaced-round-trip",
    file: "test/self-hosting-model.test.ts",
    constant: "namespacedRoundTripTestAnchor",
    site: "bindExample(namespacedRoundTripContract",
  },
  {
    id: "test:protocol.stable-ids.malformed-refusal",
    nodeType: "Anchor",
    label: "the malformed point verifies the lowercase-namespace refusal",
    type: "verifies",
    target: "spec:model.stable-ids.malformed-refusal",
    file: "test/self-hosting-model.test.ts",
    constant: "malformedRefusalTestAnchor",
    site: "bindExample(malformedRefusalContract",
  },
  {
    id: "test:protocol.markdown-parser.bounded-parity",
    nodeType: "Anchor",
    label: "the bounded-parity point verifies one shared finding class and its split outcomes",
    type: "verifies",
    target: "spec:carrier.markdown-parser.bounded-parity",
    file: "test/self-hosting-carrier.test.ts",
    constant: "boundedParityTestAnchor",
    site: "bindExample(boundedParityContract",
  },
  {
    id: "test:protocol.gherkin-authoring.authored-fact-refused",
    nodeType: "Anchor",
    label: "the authored-fact-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.authored-fact-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "authoredFactRefusedAnchor",
    site: "bindExample(authoredFactRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.contract-parity",
    nodeType: "Anchor",
    label: "the contract-parity point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.contract-parity",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "contractParityAnchor",
    site: "bindExample(contractParityContract",
  },
  {
    id: "test:protocol.gherkin-authoring.duplicate-surface-refused",
    nodeType: "Anchor",
    label: "the duplicate-surface-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.duplicate-surface-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "duplicateSurfaceRefusedAnchor",
    site: "bindExample(duplicateSurfaceRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.example-space-extraction",
    nodeType: "Anchor",
    label: "the example-space-extraction point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.example-space-extraction",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "exampleSpaceExtractionAnchor",
    site: "bindExample(exampleSpaceExtractionContract",
  },
  {
    id: "test:protocol.gherkin-authoring.malformed-relation-refused",
    nodeType: "Anchor",
    label: "the malformed-relation-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.malformed-relation-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "malformedRelationRefusedAnchor",
    site: "bindExample(malformedRelationRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.missing-id-refused",
    nodeType: "Anchor",
    label: "the missing-id-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.missing-id-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "missingIdRefusedAnchor",
    site: "bindExample(missingIdRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.parent-child-extraction",
    nodeType: "Anchor",
    label: "the parent-child-extraction point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.parent-child-extraction",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "parentChildExtractionAnchor",
    site: "bindExample(parentChildExtractionContract",
  },
  {
    id: "test:protocol.gherkin-authoring.unbound-ready-refused",
    nodeType: "Anchor",
    label: "the unbound-ready-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.unbound-ready-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "unboundReadyRefusedAnchor",
    site: "bindExample(unboundReadyRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.unknown-tag-refused",
    nodeType: "Anchor",
    label: "the unknown-tag-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.unknown-tag-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "unknownTagRefusedAnchor",
    site: "bindExample(unknownTagRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.unsupported-construct-refused",
    nodeType: "Anchor",
    label: "the unsupported-construct-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.unsupported-construct-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "unsupportedConstructRefusedAnchor",
    site: "bindExample(unsupportedConstructRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.description-location-refused",
    nodeType: "Anchor",
    label: "the description-location-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.description-location-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "descriptionLocationRefusedAnchor",
    site: "bindExample(descriptionLocationRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.step-less-scenario-refused",
    nodeType: "Anchor",
    label: "the step-less-scenario-refused point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.step-less-scenario-refused",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "stepLessScenarioRefusedAnchor",
    site: "bindExample(stepLessScenarioRefusedContract",
  },
  {
    id: "test:protocol.gherkin-authoring.multi-finding-bounded",
    nodeType: "Anchor",
    label: "the multi-finding-bounded point verifies the Gherkin carrier contract",
    type: "verifies",
    target: "spec:carrier.gherkin-authoring.multi-finding-bounded",
    file: "test/self-hosting-carrier-gherkin.test.ts",
    constant: "multiFindingBoundedAnchor",
    site: "bindExample(multiFindingBoundedContract",
  },
  {
    id: "test:protocol.sdp-import.round-trip",
    nodeType: "Anchor",
    label: "TypeScript import round-trip contract preserves authored data",
    type: "verifies",
    target: "spec:carrier.sdp-import.round-trip",
    file: "test/self-hosting-sdp-import.test.ts",
    constant: "sdpImportRoundTripTestAnchor",
    site: "bindExample(",
  },
  {
    id: "impl:protocol.anchor-extraction",
    nodeType: "CodeNode",
    label: "anchor-constant reification seam",
    type: "satisfies",
    target: "spec:model.anchors",
    file: "src/extract/anchors.ts",
    constant: "anchorExtractionAnchor",
    site: "const ANCHOR_BUILDER_TARGET_FIELDS",
  },
  {
    id: "impl:protocol.anchor-model",
    nodeType: "CodeNode",
    label: "binding-only anchor model builders",
    type: "satisfies",
    target: "spec:model.anchors",
    file: "src/model/anchors.ts",
    constant: "anchorModelAnchor",
    site: "export function specTest",
  },
  {
    id: "impl:protocol.pack-aggregate",
    nodeType: "CodeNode",
    label: "Pack aggregate and model references",
    type: "satisfies",
    target: "spec:model.pack-aggregate",
    file: "src/model/pack.ts",
    constant: "packAggregateAnchor",
    site: "export function pack",
  },
  {
    id: "impl:protocol.spec-descriptors",
    nodeType: "CodeNode",
    label: "Spec kind, altitude, and readiness coordinates",
    type: "satisfies",
    target: "spec:model.core-model",
    file: "src/model/descriptors.ts",
    constant: "specDescriptorsAnchor",
    site: "export const SPEC_KIND_DISPLAY_LABELS",
  },
  {
    id: "impl:protocol.spec-primitive",
    nodeType: "CodeNode",
    label: "Spec envelope and enrich-in-place shape",
    type: "satisfies",
    target: "spec:model.core-model",
    file: "src/model/spec.ts",
    constant: "specPrimitiveAnchor",
    site: "export function spec",
  },
  {
    id: "impl:protocol.spec-relations",
    nodeType: "CodeNode",
    label: "declared Spec relation builders",
    type: "satisfies",
    target: "spec:model.relations",
    file: "src/model/relations.ts",
    constant: "specRelationsAnchor",
    site: "export function supersedes",
  },
  {
    id: "impl:protocol.spec-sections",
    nodeType: "CodeNode",
    label: "typed Spec section shapes",
    type: "satisfies",
    target: "spec:model.spec-sections",
    file: "src/model/sections.ts",
    constant: "specSectionsAnchor",
    site: "export interface SpecSections",
  },
  {
    id: "impl:protocol.stable-ids",
    nodeType: "CodeNode",
    label: "stable ID grammar parser",
    type: "satisfies",
    target: "spec:model.stable-ids",
    file: "src/ids.ts",
    constant: "stableIdsAnchor",
    site: "export function parseId",
  },
  {
    id: "impl:protocol.verifier-semantics",
    nodeType: "CodeNode",
    label: "readiness clauses over direct verification bindings",
    type: "satisfies",
    target: "spec:model.spec-sections",
    file: "src/validate/readiness-floor.ts",
    constant: "verifierSemanticsAnchor",
    site: "export function evaluateReadinessFloor",
  },
  {
    id: "impl:protocol.validation-families",
    nodeType: "CodeNode",
    label: "conformance and honesty validator registry",
    type: "satisfies",
    target: "spec:validation.two-check-families",
    file: "src/validate/validators.ts",
    constant: "validationFamiliesAnchor",
    site: "export const graphValidatorIds",
  },
  {
    id: "impl:protocol.projections-model",
    nodeType: "CodeNode",
    label: "pure generated projection page contract",
    type: "satisfies",
    target: "spec:consumers.projections-model",
    file: "src/projections/design-review.ts",
    constant: "projectionModelAnchor",
    site: "export interface DesignReviewPage",
  },
  {
    id: "impl:protocol.agent-surface",
    nodeType: "CodeNode",
    label: "typed graph reader and agent entry adapters",
    type: "satisfies",
    target: "spec:consumers.agent-surface",
    file: "src/reader/reader.ts",
    constant: "agentSurfaceAnchor",
    site: "export function createReader",
  },
  {
    id: "impl:protocol.reader-impact",
    nodeType: "CodeNode",
    label: "file-level reader blast-radius contract",
    type: "satisfies",
    target: "spec:consumers.reader",
    file: "src/reader/reader.ts",
    constant: "readerImpactAnchor",
    site: "export interface BlastRadius",
  },
  {
    id: "impl:protocol.reader",
    nodeType: "CodeNode",
    label: "thin typed graph reader construction",
    type: "satisfies",
    target: "spec:consumers.reader",
    file: "src/reader/reader.ts",
    constant: "readerAnchor",
    site: "export function createReader",
  },
  {
    id: "impl:protocol.design-review",
    nodeType: "CodeNode",
    label: "renders the contextual Design Review projection",
    type: "satisfies",
    target: "spec:consumers.design-review",
    file: "src/projections/design-review.ts",
    constant: "designReviewAnchor",
    site: "export function renderDesignReview",
  },
  {
    id: "impl:protocol.census-page",
    nodeType: "CodeNode",
    label: "renders the derived census and runtime taxonomy projection",
    type: "satisfies",
    target: "spec:consumers.census-page",
    file: "src/projections/census.ts",
    constant: "censusAnchor",
    site: "function compareCodeUnits",
  },
  {
    id: "impl:protocol.mermaid-view",
    nodeType: "CodeNode",
    label: "renders bounded Spec one-hop and Pack membership diagrams",
    type: "satisfies",
    target: "spec:consumers.mermaid-view",
    file: "src/projections/mermaid.ts",
    constant: "mermaidViewAnchor",
    site: "function compareCodeUnits",
  },
  {
    id: "impl:protocol.gherkin-view",
    nodeType: "CodeNode",
    label: "renders a generated Gherkin-shaped READ projection of any Spec",
    type: "satisfies",
    target: "spec:consumers.gherkin-view",
    file: "src/projections/gherkin-view.ts",
    constant: "gherkinViewAnchor",
    site: "const CANONICAL_KINDS",
  },
  {
    id: "test:protocol.gherkin-view",
    nodeType: "Anchor",
    label: "verifies the generated Gherkin-shaped READ projection",
    type: "verifies",
    target: "spec:consumers.gherkin-view",
    file: "test/gherkin-view.test.ts",
    constant: "gherkinViewTestAnchor",
    site: "const checkoutRoot",
  },
  {
    id: "impl:protocol.exclusion-surface",
    nodeType: "CodeNode",
    label: "strict root-relative exclusion input for both extraction surfaces",
    type: "satisfies",
    target: "spec:extraction.excludes",
    file: "src/extract/index.ts",
    constant: "exclusionSurfaceAnchor",
    site: "export interface ExtractOptions",
  },
  {
    id: "impl:protocol.graph-claims",
    nodeType: "CodeNode",
    label: "declares the graph claim taxonomy",
    type: "satisfies",
    target: "spec:extraction.claim-taxonomy",
    file: "src/graph/schema.ts",
    constant: "graphClaimsAnchor",
    site: "export const graphClaims",
  },
  {
    id: "impl:protocol.regenerability",
    nodeType: "CodeNode",
    label: "repeats graph and contract producers for deterministic regeneration",
    type: "satisfies",
    target: "spec:extraction.regenerability",
    file: "src/cli/build-command.ts",
    constant: "regenerabilityAnchor",
    site: "export function runBuild",
  },
  {
    id: "impl:protocol.schema-version",
    nodeType: "CodeNode",
    label: "declares the graph schema version",
    type: "satisfies",
    target: "spec:extraction.schema-versioning",
    file: "src/graph/schema.ts",
    constant: "schemaVersionAnchor",
    site: "export const schemaVersion",
  },
  {
    id: "impl:protocol.executable-contracts",
    nodeType: "CodeNode",
    label: "derives step and example-space contracts from the graph",
    type: "satisfies",
    target: "spec:extraction.executable-contracts",
    file: "src/codegen/contracts.ts",
    constant: "executableContractsAnchor",
    site: "export function generateContracts",
  },
  {
    id: "impl:protocol.example-runner",
    nodeType: "CodeNode",
    label: "plans and executes a bound example against the caller's world",
    type: "satisfies",
    target: "spec:extraction.example-runner",
    file: "src/runner/index.ts",
    constant: "exampleRunnerAnchor",
    site: "export function planExample",
  },
  {
    id: "impl:protocol.slot-notation",
    nodeType: "CodeNode",
    label: "parses slot groups and normalizes a step to its skeleton",
    type: "satisfies",
    target: "spec:carrier.slot-notation",
    file: "src/notation/slots.ts",
    constant: "slotNotationAnchor",
    site: "export function parseSlots",
  },
  {
    id: "test:protocol.executable-contracts.concreteness-refusal",
    nodeType: "Anchor",
    label: "the concreteness point verifies the unbound-slot refusal",
    type: "verifies",
    target: "spec:extraction.executable-contracts.concreteness-refusal",
    file: "test/self-hosting-extraction.test.ts",
    constant: "concretenessRefusalTestAnchor",
    site: "bindExample(concretenessRefusalContract",
  },
  {
    id: "test:protocol.executable-contracts.multi-entry-example",
    nodeType: "Anchor",
    label: "the multi-entry point verifies the named second entry",
    type: "verifies",
    target: "spec:extraction.executable-contracts.multi-entry-example",
    file: "test/self-hosting-extraction.test.ts",
    constant: "multiEntryExampleTestAnchor",
    site: "bindExample(multiEntryExampleContract",
  },
  {
    id: "test:protocol.executable-contracts.case-colliding-path",
    nodeType: "Anchor",
    label: "the collision point verifies the all-or-nothing withholding",
    type: "verifies",
    target: "spec:extraction.executable-contracts.case-colliding-path",
    file: "test/self-hosting-extraction.test.ts",
    constant: "caseCollidingPathTestAnchor",
    site: "bindExample(caseCollidingPathContract",
  },
  {
    id: "test:protocol.example-runner.step-order",
    nodeType: "Anchor",
    label: "the step-order point verifies contract order and the one handler per step",
    type: "verifies",
    target: "spec:extraction.example-runner.step-order",
    file: "test/self-hosting-extraction.test.ts",
    constant: "exampleRunnerStepOrderTestAnchor",
    site: "bindExample(stepOrderContract",
  },
  {
    id: "test:protocol.example-runner.red-step-naming",
    nodeType: "Anchor",
    label: "the red-step point verifies the self-naming failure law",
    type: "verifies",
    target: "spec:extraction.example-runner.red-step-naming",
    file: "test/self-hosting-extraction.test.ts",
    constant: "exampleRunnerRedStepTestAnchor",
    site: "bindExample(redStepNamingContract",
  },
  {
    id: "test:protocol.slot-notation.typed-declaration",
    nodeType: "Anchor",
    label: "the declaration point verifies the typed form and its skeleton",
    type: "verifies",
    target: "spec:carrier.slot-notation.typed-declaration",
    file: "test/self-hosting-carrier.test.ts",
    constant: "slotNotationTypedTestAnchor",
    site: "bindExample(typedDeclarationContract",
  },
  {
    id: "test:protocol.slot-notation.refused-guess",
    nodeType: "Anchor",
    label: "the refusal point verifies prose braces and the unusable slot",
    type: "verifies",
    target: "spec:carrier.slot-notation.refused-guess",
    file: "test/self-hosting-carrier.test.ts",
    constant: "slotNotationRefusedTestAnchor",
    site: "bindExample(refusedGuessContract",
  },
  {
    id: "test:protocol.anchors.lookalike-refusal",
    nodeType: "Anchor",
    label: "the lookalike point verifies that a consumer-local builder mints nothing",
    type: "verifies",
    target: "spec:model.anchors.lookalike-refusal",
    file: "test/self-hosting-model.test.ts",
    constant: "lookalikeRefusalTestAnchor",
    site: "bindExample(lookalikeRefusalContract",
  },
  {
    id: "test:protocol.anchors.physical-identity",
    nodeType: "Anchor",
    label: "the physical-identity point verifies the resolved relative builder import",
    type: "verifies",
    target: "spec:model.anchors.physical-identity",
    file: "test/self-hosting-model.test.ts",
    constant: "physicalIdentityTestAnchor",
    site: "bindExample(physicalIdentityContract",
  },
  {
    id: "test:protocol.two-check-families.split-report",
    nodeType: "Anchor",
    label: "the split-report point verifies both families in one aggregate report",
    type: "verifies",
    target: "spec:validation.two-check-families.split-report",
    file: "test/self-hosting-validators.test.ts",
    constant: "splitReportTestAnchor",
    site: "bindExample(splitReportContract",
  },
  {
    id: "test:protocol.derived-readiness-banner.dishonest-divergence",
    nodeType: "Anchor",
    label: "the overstated-rung point verifies the banner and its first unmet clause",
    type: "verifies",
    target: "spec:consumers.derived-readiness-banner.dishonest-divergence",
    file: "test/self-hosting-projections.test.ts",
    constant: "dishonestDivergenceTestAnchor",
    site: "bindExample(dishonestDivergenceContract",
  },
  {
    id: "test:protocol.derived-readiness-banner.honest-headroom",
    nodeType: "Anchor",
    label: "the understated-rung point verifies the one-direction bound on the banner",
    type: "verifies",
    target: "spec:consumers.derived-readiness-banner.honest-headroom",
    file: "test/self-hosting-projections.test.ts",
    constant: "honestHeadroomTestAnchor",
    site: "bindExample(honestHeadroomContract",
  },
  {
    id: "test:protocol.binding-language-views.bound-spec-page",
    nodeType: "Anchor",
    label: "the bound-surface point verifies the rendered binding vocabulary",
    type: "verifies",
    target: "spec:consumers.binding-language-views.bound-spec-page",
    file: "test/self-hosting-projections.test.ts",
    constant: "boundSpecPageTestAnchor",
    site: "bindExample(boundSpecPageContract",
  },
  {
    id: "test:protocol.binding-language-views.pack-member-table",
    nodeType: "Anchor",
    label: "the pack-member point verifies the aggregate half of the rendered binding vocabulary",
    type: "verifies",
    target: "spec:consumers.binding-language-views.pack-member-table",
    file: "test/self-hosting-projections.test.ts",
    constant: "packMemberTableTestAnchor",
    site: "bindExample(packMemberTableContract",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.stale-page-removed",
    nodeType: "Anchor",
    label: "the stale-page point verifies the wholesale rewrite of the view directory",
    type: "verifies",
    target: "spec:consumers.wholesale-view-rewrite.stale-page-removed",
    file: "test/self-hosting-projections.test.ts",
    constant: "stalePageRemovedTestAnchor",
    site: "bindExample(stalePageRemovedContract",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.late-stale-page",
    nodeType: "Anchor",
    label: "the late-page point verifies that the swap itself evicts what invalidation missed",
    type: "verifies",
    target: "spec:consumers.wholesale-view-rewrite.late-stale-page",
    file: "test/self-hosting-projections.test.ts",
    constant: "lateStalePageTestAnchor",
    site: "bindExample(lateStalePageContract",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.failed-run-view-removed",
    nodeType: "Anchor",
    label: "the failed-run point verifies that an uncertifiable view is removed, not left readable",
    type: "verifies",
    target: "spec:consumers.wholesale-view-rewrite.failed-run-view-removed",
    file: "test/self-hosting-projections.test.ts",
    constant: "failedRunViewRemovedTestAnchor",
    site: "bindExample(failedRunViewRemovedContract",
  },
  {
    id: "test:protocol.wholesale-view-rewrite.build-invalidates-view",
    nodeType: "Anchor",
    label: "the build point verifies the up-front invalidation on a command that renders no view",
    type: "verifies",
    target: "spec:consumers.wholesale-view-rewrite.build-invalidates-view",
    file: "test/self-hosting-projections.test.ts",
    constant: "buildInvalidatesViewTestAnchor",
    site: "bindExample(buildInvalidatesViewContract",
  },
  {
    id: "test:protocol.diagnostic-rendering.composed-location",
    nodeType: "Anchor",
    label: "the composed-location point verifies the one rendering rule and both degradations",
    type: "verifies",
    target: "spec:validation.diagnostic-rendering.composed-location",
    file: "test/self-hosting-projections.test.ts",
    constant: "composedLocationTestAnchor",
    site: "bindExample(composedLocationContract",
  },
  {
    id: "test:protocol.diagnostic-rendering.table-cell-location",
    nodeType: "Anchor",
    label: "the table-cell point verifies the same composition rule on the Design Review's twin",
    type: "verifies",
    target: "spec:validation.diagnostic-rendering.table-cell-location",
    file: "test/self-hosting-projections.test.ts",
    constant: "tableCellLocationTestAnchor",
    site: "bindExample(tableCellLocationContract",
  },
  {
    id: "test:protocol.design-review.pure-projection",
    nodeType: "Anchor",
    label: "the pure-projection point verifies the view's own law over a whole-pipeline root",
    type: "verifies",
    target: "spec:consumers.design-review.pure-projection",
    file: "test/self-hosting-projections.test.ts",
    constant: "pureProjectionTestAnchor",
    site: "bindExample(pureProjectionContract",
  },
  {
    id: "test:protocol.agent-surface.scripted-context-body",
    nodeType: "Anchor",
    label: "the scripted-body point verifies the front door's claim-decoded, pre-shaped return",
    type: "verifies",
    target: "spec:consumers.agent-surface.scripted-context-body",
    file: "test/self-hosting-consumers.test.ts",
    constant: "scriptedContextBodyTestAnchor",
    site: "bindExample(scriptedContextBodyContract",
  },
  {
    id: "test:protocol.agent-surface.demand-map-entries",
    nodeType: "Anchor",
    label: "the demand-map point verifies the three entry points and the absent symbol entry",
    type: "verifies",
    target: "spec:consumers.agent-surface.demand-map-entries",
    file: "test/self-hosting-consumers.test.ts",
    constant: "demandMapEntriesTestAnchor",
    site: "bindExample(demandMapEntriesContract",
  },
  {
    id: "test:protocol.reader.concept-entry",
    nodeType: "Anchor",
    label: "the concept-entry point verifies the string bridge and the field it names",
    type: "verifies",
    target: "spec:consumers.reader.concept-entry",
    file: "test/self-hosting-consumers.test.ts",
    constant: "conceptEntryTestAnchor",
    site: "bindExample(conceptEntryContract",
  },
  {
    id: "test:protocol.reader.file-entry",
    nodeType: "Anchor",
    label: "the file-entry point verifies both halves of the file bridge",
    type: "verifies",
    target: "spec:consumers.reader.file-entry",
    file: "test/self-hosting-consumers.test.ts",
    constant: "fileEntryTestAnchor",
    site: "bindExample(fileEntryContract",
  },
  {
    id: "test:protocol.reader.changeset-entry",
    nodeType: "Anchor",
    label: "the changeset-entry point verifies impact reasons, at-risk edges, and coverage-unknown",
    type: "verifies",
    target: "spec:consumers.reader.changeset-entry",
    file: "test/self-hosting-consumers.test.ts",
    constant: "changesetEntryTestAnchor",
    site: "bindExample(changesetEntryContract",
  },
  {
    id: "impl:protocol.sdp-import",
    nodeType: "CodeNode",
    label: "plans, refuses, and publishes TypeScript-to-Markdown Spec imports",
    type: "satisfies",
    target: "spec:carrier.sdp-import",
    file: "src/cli/import-command.ts",
    constant: "sdpImportAnchor",
    site: "export function runImport",
  },
  {
    id: "impl:protocol.extraction-determinism",
    nodeType: "CodeNode",
    label: "repeats and byte-compares graph and contract generation under --check-clean",
    type: "satisfies",
    target: "spec:extraction.determinism",
    file: "src/cli/build-command.ts",
    constant: "determinismAnchor",
    site: "export function runBuild",
  },
  {
    id: "impl:protocol.wholesale-view-build-invalidation",
    nodeType: "CodeNode",
    label: "invalidates the prior Design Review before every build attempt",
    type: "satisfies",
    target: "spec:consumers.wholesale-view-rewrite",
    file: "src/cli/build-command.ts",
    constant: "wholesaleViewBuildInvalidationAnchor",
    site: "export function runBuild",
  },
  {
    id: "impl:protocol.wholesale-view-rewrite",
    nodeType: "CodeNode",
    label: "publishes each Design Review as one wholesale temporary-directory replacement",
    type: "satisfies",
    target: "spec:consumers.wholesale-view-rewrite",
    file: "src/cli/validate-view-command.ts",
    constant: "wholesaleViewRewriteAnchor",
    site: "export function runView",
  },
  {
    id: "impl:protocol.derived-readiness-banner",
    nodeType: "CodeNode",
    label: "renders stated readiness beside the structural floor and dishonest divergence",
    type: "satisfies",
    target: "spec:consumers.derived-readiness-banner",
    file: "src/projections/design-review-context.ts",
    constant: "derivedReadinessBannerAnchor",
    site: "export function renderReadiness",
  },
  {
    id: "impl:protocol.binding-language-spec-page",
    nodeType: "CodeNode",
    label: "renders implementation, verifier, oracle, and observation binding language",
    type: "satisfies",
    target: "spec:consumers.binding-language-views",
    file: "src/projections/design-review-context.ts",
    constant: "bindingLanguageSpecPageAnchor",
    site: "export function renderBindings",
  },
  {
    id: "impl:protocol.diagnostic-rendering-design-review",
    nodeType: "CodeNode",
    label: "renders structured finding locations in the Design Review table",
    type: "satisfies",
    target: "spec:validation.diagnostic-rendering",
    file: "src/projections/design-review-context.ts",
    constant: "diagnosticDesignReviewAnchor",
    site: "export function renderFindings",
  },
  {
    id: "impl:protocol.binding-language-pack-table",
    nodeType: "CodeNode",
    label: "renders Pack member implementation and verifier bindings as present or none",
    type: "satisfies",
    target: "spec:consumers.binding-language-views",
    file: "src/projections/design-review-pages.ts",
    constant: "bindingLanguagePackTableAnchor",
    site: "export function renderPackPage",
  },
  {
    id: "impl:protocol.binding-language-index-table",
    nodeType: "CodeNode",
    label: "renders index implementation and verifier bindings as present or none",
    type: "satisfies",
    target: "spec:consumers.binding-language-views",
    file: "src/projections/design-review-pages.ts",
    constant: "bindingLanguageIndexTableAnchor",
    site: "export function renderIndexPage",
  },
  {
    id: "impl:protocol.diagnostic-rendering-cli",
    nodeType: "CodeNode",
    label: "composes structured finding fields into the one command-line diagnostic form",
    type: "satisfies",
    target: "spec:validation.diagnostic-rendering",
    file: "src/cli/output.ts",
    constant: "diagnosticCliAnchor",
    site: "export function formatFinding",
  },
  {
    id: "impl:protocol.kind-evidence",
    nodeType: "CodeNode",
    label: "defines the code-level per-kind evidence rows for readiness floors",
    type: "satisfies",
    target: "spec:validation.kind-evidence",
    file: "src/validate/readiness-floor.ts",
    constant: "kindEvidenceAnchor",
    site: "export const kindEvidence",
  },
  {
    id: "impl:protocol.referential-integrity",
    nodeType: "CodeNode",
    label: "checks every graph edge endpoint and Pack model reference resolves",
    type: "satisfies",
    target: "spec:validation.referential-integrity",
    file: "src/validate/validators.ts",
    constant: "referentialIntegrityAnchor",
    site: "function checkEdgeReferentialIntegrity",
  },
  {
    id: "impl:protocol.claim-separation",
    nodeType: "CodeNode",
    label: "checks graph claims, descriptors, node shapes, and relation endpoint contracts",
    type: "satisfies",
    target: "spec:validation.claim-separation",
    file: "src/validate/validators.ts",
    constant: "claimSeparationAnchor",
    site: "function checkClaimSeparation",
  },
  {
    id: "impl:protocol.verifies-linkage",
    nodeType: "CodeNode",
    label: "resolves declared example verification through enabled test bindings",
    type: "satisfies",
    target: "spec:validation.verification-linkage",
    file: "src/validate/validators.ts",
    constant: "verifiesLinkageAnchor",
    site: "function checkVerifiesLinkage",
  },
  {
    id: "impl:protocol.oracle-linkage",
    nodeType: "CodeNode",
    label: "resolves and de-duplicates expected-outcome oracle bindings",
    type: "satisfies",
    target: "spec:validation.verification-linkage",
    file: "src/validate/validators.ts",
    constant: "oracleLinkageAnchor",
    site: "function checkOracleLinkage",
  },
  {
    id: "impl:protocol.pack-coherence",
    nodeType: "CodeNode",
    label: "checks Pack membership uniqueness and model-reference kinds",
    type: "satisfies",
    target: "spec:validation.pack-coherence",
    file: "src/validate/validators.ts",
    constant: "packCoherenceAnchor",
    site: "function checkPackCoherence",
  },
  {
    id: "impl:protocol.orphan-signal",
    nodeType: "CodeNode",
    label: "surfaces relationless Specs as informative orphan warnings",
    type: "satisfies",
    target: "spec:validation.warn-level-signals",
    file: "src/validate/validators.ts",
    constant: "orphanSignalAnchor",
    site: "function checkOrphans",
  },
  {
    id: "impl:protocol.authored-honesty-shape",
    nodeType: "CodeNode",
    label: "refuses delivery facts smuggled through authored section carriers",
    type: "satisfies",
    target: "spec:validation.authored-honesty",
    file: "src/validate/validators.ts",
    constant: "authoringShapeAnchor",
    site: "function checkAuthoringShape",
  },
  {
    id: "impl:protocol.authored-honesty-delivery-facts",
    nodeType: "CodeNode",
    label: "checks stated delivery facts equal the one recomputed derivation",
    type: "satisfies",
    target: "spec:validation.authored-honesty",
    file: "src/validate/validators.ts",
    constant: "deliveryFactsHonestyAnchor",
    site: "function checkDeliveryFacts",
  },
  {
    id: "impl:protocol.verifier-gap-signal",
    nodeType: "CodeNode",
    label: "surfaces ready Specs without recomputed verifier bindings as informative gaps",
    type: "satisfies",
    target: "spec:validation.warn-level-signals",
    file: "src/validate/validators.ts",
    constant: "gapSignalAnchor",
    site: "function checkGaps",
  },
  {
    id: "oracle:protocol.reader-entry-map",
    nodeType: "Anchor",
    label: "expected reader outcome for each graph entry mode",
    type: "models",
    target: "spec:consumers.reader",
    file: "test/self-hosting-consumers.oracle.ts",
    constant: "readerEntryMapOracle",
    site: "export function expectedReaderOutcome",
  },
  {
    id: "impl:protocol.oracle-target-eligibility",
    nodeType: "CodeNode",
    label: "resolves oracle targets by example-space ownership across Spec kinds",
    type: "satisfies",
    target: "spec:validation.oracle-target-eligibility",
    file: "src/graph/oracle-bindings.ts",
    constant: "oracleTargetEligibilityAnchor",
    site: "export function isResolvingOracleModel",
  },
  {
    id: "test:protocol.oracle-target-eligibility.rule-space-accepted",
    nodeType: "Anchor",
    label: "the rule-space point verifies kind-neutral oracle resolution",
    type: "verifies",
    target: "spec:validation.oracle-target-eligibility.rule-space-accepted",
    file: "test/self-hosting-validators.test.ts",
    constant: "ruleSpaceAcceptedTestAnchor",
    site: "bindExample(ruleSpaceAcceptedContract",
  },
  {
    id: "test:protocol.mermaid-view",
    nodeType: "Anchor",
    label: "verifies bounded deterministic Mermaid projection and publication",
    type: "verifies",
    target: "spec:consumers.mermaid-view",
    file: "test/mermaid-render.test.ts",
    constant: "mermaidTestAnchor",
    site: "const checkoutRoot",
  },
  {
    id: "test:protocol.oracle-target-eligibility.missing-space-refused",
    nodeType: "Anchor",
    label: "the missing-space point verifies fail-closed oracle resolution",
    type: "verifies",
    target: "spec:validation.oracle-target-eligibility.missing-space-refused",
    file: "test/self-hosting-validators.test.ts",
    constant: "missingSpaceRefusedTestAnchor",
    site: "bindExample(missingSpaceRefusedContract",
  },
  {
    id: "oracle:protocol.oracle-target-eligibility",
    nodeType: "Anchor",
    label: "expected oracle-linkage result by example-space ownership",
    type: "models",
    target: "spec:validation.oracle-target-eligibility",
    file: "test/self-hosting-validators.oracle.ts",
    constant: "oracleTargetEligibilityOracle",
    site: "export function expectedOracleTargetEligibilityOutcome",
  },
  {
    id: "impl:protocol.markdown-pack-authoring",
    nodeType: "CodeNode",
    label: "reifies the Markdown Pack manifest into the one carrier path",
    type: "satisfies",
    target: "spec:carrier.markdown-pack-authoring",
    file: "src/extract/markdown-pack.ts",
    constant: "markdownPackAuthoringAnchor",
    site: "export function reifyMarkdownPack(",
  },
  {
    id: "test:protocol.markdown-pack-authoring.markdown-ts-parity",
    nodeType: "Anchor",
    label: "the parity point verifies equal Markdown and TypeScript Pack derivation",
    type: "verifies",
    target: "spec:carrier.markdown-pack-authoring.markdown-ts-parity",
    file: "test/self-hosting-pack-markdown.test.ts",
    constant: "parityTestAnchor",
    site: "bindExample(markdownTsParityContract",
  },
  {
    id: "test:protocol.markdown-pack-authoring.spec-envelope-refused",
    nodeType: "Anchor",
    label: "the refusal point verifies the Markdown Pack closed envelope",
    type: "verifies",
    target: "spec:carrier.markdown-pack-authoring.spec-envelope-refused",
    file: "test/self-hosting-pack-markdown.test.ts",
    constant: "refusalTestAnchor",
    site: "bindExample(specEnvelopeRefusedContract",
  },
  {
    id: "impl:protocol.build-pipeline-query",
    nodeType: "CodeNode",
    label:
      "one query invocation derives the graph once and serves reader, raw graph, and report from that one derivation",
    type: "satisfies",
    target: "spec:extraction.build-pipeline",
    file: "src/cli/q-command.ts",
    constant: "buildPipelineQueryAnchor",
    site: "export async function runQuery",
  },
  {
    id: "impl:protocol.build-pipeline-emit",
    nodeType: "CodeNode",
    label: "the build command owns the ordered flow through artifact emission",
    type: "satisfies",
    target: "spec:extraction.build-pipeline",
    file: "src/cli/build-command.ts",
    constant: "buildPipelineEmitAnchor",
    site: "export function runBuild",
  },
  {
    id: "impl:protocol.example-runner-adapter",
    nodeType: "CodeNode",
    label: "registers one test per example and owns the fresh world lifecycle",
    type: "satisfies",
    target: "spec:extraction.example-runner",
    file: "src/adapters/vitest.ts",
    constant: "exampleRunnerAdapterAnchor",
    site: "export function bindExample",
  },
  {
    id: "impl:protocol.runnable-modules",
    nodeType: "CodeNode",
    label: "derives and publishes runnable registrar modules from the graph",
    type: "satisfies",
    target: "spec:extraction.runnable-modules",
    file: "src/codegen/contracts.ts",
    constant: "runnableModulesAnchor",
    site: "export function generateContracts",
  },
  {
    id: "test:protocol.census-page",
    nodeType: "Anchor",
    label: "verifies census taxonomy, findings, and structural-binding projection",
    type: "verifies",
    target: "spec:consumers.census-page",
    file: "test/census.test.ts",
    constant: "censusTestAnchor",
    site: 'describe("the derived census/taxonomy projection"',
  },
  {
    id: "test:protocol.runnable-modules",
    nodeType: "Anchor",
    label: "verifies generated runnable-module registration and runtime semantics",
    type: "verifies",
    target: "spec:extraction.runnable-modules",
    file: "test/testing.test.ts",
    constant: "runnableModulesTestAnchor",
    site: 'describe("generated registrar testing runtime"',
  },
] as const;
