// The authored `declared`-claim relations of the self-hosting corpus, excluding the `belongsTo`
// edges derived from the Pack manifest. Authored transcription: the relation set is intent, and
// the extractor may neither add to it nor drop from it.

export const expectedDeclaredRelations = [
  ["spec:carrier.markdown-authoring", "dependsOn", "spec:carrier.markdown-parser"],
  ["spec:carrier.markdown-authoring", "decidedBy", "spec:decisions.sdp-ts-extension"],
  ["spec:carrier.markdown-authoring", "decidedBy", "spec:decisions.carrier-ruling"],
  ["spec:carrier.envelope-contract", "refines", "spec:carrier.markdown-authoring"],
  ["spec:carrier.envelope-contract", "decidedBy", "spec:decisions.envelope-grammar-posture"],
  ["spec:carrier.markdown-parser", "refines", "spec:carrier.markdown-authoring"],
  ["spec:carrier.markdown-parser", "dependsOn", "spec:carrier.envelope-contract"],
  ["spec:carrier.markdown-parser.bounded-parity", "refines", "spec:carrier.markdown-parser"],
  ["spec:carrier.markdown-parser.bounded-parity", "verifies", "spec:carrier.markdown-parser"],
  ["spec:carrier.sdp-import", "refines", "spec:carrier.markdown-authoring"],
  ["spec:carrier.sdp-import.round-trip", "refines", "spec:carrier.sdp-import"],
  ["spec:carrier.sdp-import.round-trip", "verifies", "spec:carrier.sdp-import"],
  ["spec:carrier.prose-ownership-rule", "refines", "spec:carrier.markdown-authoring"],
  ["spec:carrier.prose-ownership-rule", "decidedBy", "spec:decisions.prose-ownership"],
  ["spec:protocol.self-hosting", "dependsOn", "spec:carrier.markdown-authoring"],
  ["spec:protocol.self-hosting", "dependsOn", "spec:model.protocol-domain"],
  ["spec:protocol.self-hosting", "decidedBy", "spec:decisions.concept-docs-dissolve"],
  ["spec:protocol.self-hosting", "decidedBy", "spec:decisions.executable-meta-model"],
  ["spec:protocol.self-hosting", "decidedBy", "spec:decisions.adopt-the-nouns"],
  ["spec:protocol.self-hosting", "decidedBy", "spec:decisions.protocol-naming"],
  ["spec:extraction.derive-graph", "refines", "spec:protocol.self-hosting"],
  ["spec:extraction.derive-graph", "constrainedBy", "spec:extraction.determinism"],
  ["spec:extraction.determinism", "refines", "spec:protocol.self-hosting"],
  ["spec:extraction.build-pipeline", "refines", "spec:protocol.self-hosting"],
  ["spec:extraction.build-pipeline", "dependsOn", "spec:extraction.derive-graph"],
  ["spec:extraction.excludes", "refines", "spec:extraction.derive-graph"],
  ["spec:extraction.excludes", "decidedBy", "spec:decisions.exclusion-contract"],
  ["spec:extraction.excludes.segment-boundary", "refines", "spec:extraction.excludes"],
  ["spec:extraction.excludes.segment-boundary", "verifies", "spec:extraction.excludes"],
  ["spec:extraction.excludes.refused-path", "refines", "spec:extraction.excludes"],
  ["spec:extraction.excludes.refused-path", "verifies", "spec:extraction.excludes"],
  ["spec:extraction.claim-taxonomy", "refines", "spec:extraction.derive-graph"],
  ["spec:extraction.regenerability", "refines", "spec:extraction.determinism"],
  ["spec:extraction.schema-versioning", "refines", "spec:extraction.derive-graph"],
  [
    "spec:extraction.schema-versioning.declared-version",
    "refines",
    "spec:extraction.schema-versioning",
  ],
  [
    "spec:extraction.schema-versioning.declared-version",
    "verifies",
    "spec:extraction.schema-versioning",
  ],
  ["spec:extraction.executable-contracts", "refines", "spec:extraction.build-pipeline"],
  [
    "spec:extraction.executable-contracts.concreteness-refusal",
    "refines",
    "spec:extraction.executable-contracts",
  ],
  [
    "spec:extraction.executable-contracts.concreteness-refusal",
    "verifies",
    "spec:extraction.executable-contracts",
  ],
  [
    "spec:extraction.executable-contracts.multi-entry-example",
    "refines",
    "spec:extraction.executable-contracts",
  ],
  [
    "spec:extraction.executable-contracts.multi-entry-example",
    "verifies",
    "spec:extraction.executable-contracts",
  ],
  [
    "spec:extraction.executable-contracts.case-colliding-path",
    "refines",
    "spec:extraction.executable-contracts",
  ],
  [
    "spec:extraction.executable-contracts.case-colliding-path",
    "verifies",
    "spec:extraction.executable-contracts",
  ],
  ["spec:extraction.example-runner", "refines", "spec:extraction.executable-contracts"],
  ["spec:extraction.example-runner.step-order", "refines", "spec:extraction.example-runner"],
  ["spec:extraction.example-runner.step-order", "verifies", "spec:extraction.example-runner"],
  ["spec:extraction.example-runner.red-step-naming", "refines", "spec:extraction.example-runner"],
  ["spec:extraction.example-runner.red-step-naming", "verifies", "spec:extraction.example-runner"],
  ["spec:carrier.slot-notation", "refines", "spec:carrier.markdown-authoring"],
  ["spec:carrier.slot-notation.typed-declaration", "refines", "spec:carrier.slot-notation"],
  ["spec:carrier.slot-notation.typed-declaration", "verifies", "spec:carrier.slot-notation"],
  ["spec:carrier.slot-notation.refused-guess", "refines", "spec:carrier.slot-notation"],
  ["spec:carrier.slot-notation.refused-guess", "verifies", "spec:carrier.slot-notation"],
  ["spec:validation.readiness-floor", "refines", "spec:protocol.self-hosting"],
  ["spec:validation.readiness-floor", "dependsOn", "spec:model.protocol-domain"],
  ["spec:validation.readiness-floor", "decidedBy", "spec:decisions.kind-conditional-floor"],
  ["spec:validation.readiness-floor", "decidedBy", "spec:decisions.carried-evidence"],
  [
    "spec:validation.readiness-floor.unrelated-scoped-spec",
    "refines",
    "spec:validation.readiness-floor",
  ],
  [
    "spec:validation.readiness-floor.unrelated-scoped-spec",
    "verifies",
    "spec:validation.readiness-floor",
  ],
  [
    "spec:validation.readiness-floor.blocking-open-question",
    "refines",
    "spec:validation.readiness-floor",
  ],
  [
    "spec:validation.readiness-floor.blocking-open-question",
    "verifies",
    "spec:validation.readiness-floor",
  ],
  ["spec:validation.kind-evidence", "refines", "spec:validation.readiness-floor"],
  ["spec:validation.kind-evidence", "decidedBy", "spec:decisions.kind-conditional-floor"],
  ["spec:validation.kind-evidence.constraints-alone", "refines", "spec:validation.kind-evidence"],
  ["spec:validation.kind-evidence.constraints-alone", "verifies", "spec:validation.kind-evidence"],
  [
    "spec:validation.kind-evidence.untargeted-constraint",
    "refines",
    "spec:validation.kind-evidence",
  ],
  [
    "spec:validation.kind-evidence.untargeted-constraint",
    "verifies",
    "spec:validation.kind-evidence",
  ],
  [
    "spec:validation.kind-evidence.empty-promoted-child",
    "refines",
    "spec:validation.kind-evidence",
  ],
  [
    "spec:validation.kind-evidence.empty-promoted-child",
    "verifies",
    "spec:validation.kind-evidence",
  ],
  ["spec:validation.duplicate-ids", "refines", "spec:protocol.self-hosting"],
  ["spec:validation.duplicate-ids", "dependsOn", "spec:carrier.markdown-parser"],
  ["spec:validation.duplicate-ids.dual-carrier", "refines", "spec:validation.duplicate-ids"],
  ["spec:validation.duplicate-ids.dual-carrier", "verifies", "spec:validation.duplicate-ids"],
  ["spec:validation.two-check-families", "refines", "spec:protocol.self-hosting"],
  ["spec:validation.two-check-families", "decidedBy", "spec:decisions.one-validation-path"],
  ["spec:validation.referential-integrity", "refines", "spec:validation.two-check-families"],
  [
    "spec:validation.referential-integrity.dangling-target",
    "refines",
    "spec:validation.referential-integrity",
  ],
  [
    "spec:validation.referential-integrity.dangling-target",
    "verifies",
    "spec:validation.referential-integrity",
  ],
  [
    "spec:validation.referential-integrity.did-you-mean",
    "refines",
    "spec:validation.referential-integrity",
  ],
  [
    "spec:validation.referential-integrity.did-you-mean",
    "verifies",
    "spec:validation.referential-integrity",
  ],
  ["spec:validation.claim-separation", "refines", "spec:validation.two-check-families"],
  [
    "spec:validation.claim-separation.collapsed-edge-claim",
    "refines",
    "spec:validation.claim-separation",
  ],
  [
    "spec:validation.claim-separation.collapsed-edge-claim",
    "verifies",
    "spec:validation.claim-separation",
  ],
  [
    "spec:validation.claim-separation.unratified-descriptor",
    "refines",
    "spec:validation.claim-separation",
  ],
  [
    "spec:validation.claim-separation.unratified-descriptor",
    "verifies",
    "spec:validation.claim-separation",
  ],
  ["spec:validation.verification-linkage", "refines", "spec:validation.two-check-families"],
  [
    "spec:validation.verification-linkage.unbound-example",
    "refines",
    "spec:validation.verification-linkage",
  ],
  [
    "spec:validation.verification-linkage.unbound-example",
    "verifies",
    "spec:validation.verification-linkage",
  ],
  [
    "spec:validation.verification-linkage.unresolved-oracle",
    "refines",
    "spec:validation.verification-linkage",
  ],
  [
    "spec:validation.verification-linkage.unresolved-oracle",
    "verifies",
    "spec:validation.verification-linkage",
  ],
  ["spec:validation.pack-coherence", "refines", "spec:validation.two-check-families"],
  [
    "spec:validation.pack-coherence.incoherent-aggregate",
    "refines",
    "spec:validation.pack-coherence",
  ],
  [
    "spec:validation.pack-coherence.incoherent-aggregate",
    "verifies",
    "spec:validation.pack-coherence",
  ],
  ["spec:validation.authored-honesty", "refines", "spec:validation.two-check-families"],
  [
    "spec:validation.authored-honesty.section-authored-fact",
    "refines",
    "spec:validation.authored-honesty",
  ],
  [
    "spec:validation.authored-honesty.section-authored-fact",
    "verifies",
    "spec:validation.authored-honesty",
  ],
  [
    "spec:validation.authored-honesty.unearned-stated-fact",
    "refines",
    "spec:validation.authored-honesty",
  ],
  [
    "spec:validation.authored-honesty.unearned-stated-fact",
    "verifies",
    "spec:validation.authored-honesty",
  ],
  ["spec:validation.warn-level-signals", "refines", "spec:validation.two-check-families"],
  [
    "spec:validation.warn-level-signals.orphan-signal",
    "refines",
    "spec:validation.warn-level-signals",
  ],
  [
    "spec:validation.warn-level-signals.orphan-signal",
    "verifies",
    "spec:validation.warn-level-signals",
  ],
  [
    "spec:validation.warn-level-signals.ready-gap-signal",
    "refines",
    "spec:validation.warn-level-signals",
  ],
  [
    "spec:validation.warn-level-signals.ready-gap-signal",
    "verifies",
    "spec:validation.warn-level-signals",
  ],
  ["spec:consumers.projections-model", "refines", "spec:protocol.self-hosting"],
  ["spec:consumers.projections-model", "decidedBy", "spec:decisions.mcp-deferred"],
  ["spec:consumers.agent-surface", "refines", "spec:consumers.projections-model"],
  ["spec:consumers.agent-surface", "decidedBy", "spec:decisions.agent-surface-scripts-graph"],
  ["spec:consumers.design-review", "refines", "spec:consumers.projections-model"],
  ["spec:consumers.reader", "refines", "spec:consumers.agent-surface"],
  ["spec:consumers.edit-model", "refines", "spec:consumers.projections-model"],
  ["spec:model.protocol-domain", "refines", "spec:protocol.self-hosting"],
  ["spec:model.core-model", "refines", "spec:protocol.self-hosting"],
  ["spec:model.core-model", "decidedBy", "spec:decisions.one-primitive"],
  ["spec:model.spec-sections", "refines", "spec:model.core-model"],
  ["spec:model.spec-sections", "decidedBy", "spec:decisions.point-per-example"],
  ["spec:model.spec-sections", "decidedBy", "spec:decisions.content-only-sections"],
  ["spec:model.spec-sections", "decidedBy", "spec:decisions.typing-law"],
  ["spec:model.relations", "refines", "spec:model.core-model"],
  ["spec:model.stable-ids", "refines", "spec:model.core-model"],
  ["spec:model.stable-ids.namespaced-round-trip", "refines", "spec:model.stable-ids"],
  ["spec:model.stable-ids.namespaced-round-trip", "verifies", "spec:model.stable-ids"],
  ["spec:model.stable-ids.malformed-refusal", "refines", "spec:model.stable-ids"],
  ["spec:model.stable-ids.malformed-refusal", "verifies", "spec:model.stable-ids"],
  ["spec:model.pack-aggregate", "refines", "spec:model.core-model"],
  ["spec:model.pack-aggregate", "decidedBy", "spec:decisions.pack-reified"],
  ["spec:model.anchors", "refines", "spec:model.core-model"],
  ["spec:model.anchors", "decidedBy", "spec:decisions.binding-not-liveness"],
  ["spec:decisions.plain-language-references", "refines", "spec:protocol.self-hosting"],
  ["spec:decisions.concept-docs-dissolve", "refines", "spec:protocol.self-hosting"],
  ["spec:decisions.one-validation-path", "refines", "spec:validation.two-check-families"],
  ["spec:decisions.sdp-ts-extension", "refines", "spec:carrier.markdown-authoring"],
  ["spec:decisions.point-per-example", "refines", "spec:model.spec-sections"],
  ["spec:decisions.carrier-ruling", "refines", "spec:carrier.markdown-authoring"],
  ["spec:decisions.prose-ownership", "refines", "spec:carrier.prose-ownership-rule"],
  ["spec:decisions.envelope-grammar-posture", "refines", "spec:carrier.envelope-contract"],
  ["spec:decisions.exclusion-contract", "refines", "spec:extraction.excludes"],
  ["spec:decisions.executable-meta-model", "refines", "spec:protocol.self-hosting"],
  ["spec:decisions.adopt-the-nouns", "refines", "spec:protocol.self-hosting"],
  ["spec:decisions.one-primitive", "refines", "spec:model.core-model"],
  ["spec:decisions.protocol-naming", "refines", "spec:protocol.self-hosting"],
  ["spec:decisions.binding-not-liveness", "refines", "spec:model.anchors"],
  ["spec:decisions.content-only-sections", "refines", "spec:model.spec-sections"],
  ["spec:decisions.typing-law", "refines", "spec:model.spec-sections"],
  ["spec:decisions.kind-conditional-floor", "refines", "spec:validation.readiness-floor"],
  ["spec:decisions.carried-evidence", "refines", "spec:validation.readiness-floor"],
  ["spec:decisions.pack-reified", "refines", "spec:model.pack-aggregate"],
  ["spec:decisions.agent-surface-scripts-graph", "refines", "spec:consumers.agent-surface"],
  ["spec:decisions.mcp-deferred", "refines", "spec:consumers.projections-model"],
  ["spec:decisions.agent-front-door", "refines", "spec:consumers.agent-surface"],
  ["spec:model.anchors.lookalike-refusal", "refines", "spec:model.anchors"],
  ["spec:model.anchors.lookalike-refusal", "verifies", "spec:model.anchors"],
  ["spec:model.anchors.physical-identity", "refines", "spec:model.anchors"],
  ["spec:model.anchors.physical-identity", "verifies", "spec:model.anchors"],
  [
    "spec:validation.two-check-families.split-report",
    "refines",
    "spec:validation.two-check-families",
  ],
  [
    "spec:validation.two-check-families.split-report",
    "verifies",
    "spec:validation.two-check-families",
  ],
  ["spec:consumers.derived-readiness-banner", "refines", "spec:consumers.design-review"],
  ["spec:consumers.derived-readiness-banner", "dependsOn", "spec:validation.readiness-floor"],
  [
    "spec:consumers.derived-readiness-banner.dishonest-divergence",
    "refines",
    "spec:consumers.derived-readiness-banner",
  ],
  [
    "spec:consumers.derived-readiness-banner.dishonest-divergence",
    "verifies",
    "spec:consumers.derived-readiness-banner",
  ],
  [
    "spec:consumers.derived-readiness-banner.honest-headroom",
    "refines",
    "spec:consumers.derived-readiness-banner",
  ],
  [
    "spec:consumers.derived-readiness-banner.honest-headroom",
    "verifies",
    "spec:consumers.derived-readiness-banner",
  ],
  ["spec:consumers.binding-language-views", "refines", "spec:consumers.design-review"],
  ["spec:consumers.binding-language-views", "decidedBy", "spec:decisions.binding-not-liveness"],
  [
    "spec:consumers.binding-language-views.bound-spec-page",
    "refines",
    "spec:consumers.binding-language-views",
  ],
  [
    "spec:consumers.binding-language-views.bound-spec-page",
    "verifies",
    "spec:consumers.binding-language-views",
  ],
  [
    "spec:consumers.binding-language-views.pack-member-table",
    "refines",
    "spec:consumers.binding-language-views",
  ],
  [
    "spec:consumers.binding-language-views.pack-member-table",
    "verifies",
    "spec:consumers.binding-language-views",
  ],
  ["spec:consumers.wholesale-view-rewrite", "refines", "spec:consumers.design-review"],
  ["spec:consumers.wholesale-view-rewrite", "dependsOn", "spec:extraction.determinism"],
  [
    "spec:consumers.wholesale-view-rewrite.stale-page-removed",
    "refines",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.stale-page-removed",
    "verifies",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.late-stale-page",
    "refines",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.late-stale-page",
    "verifies",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.failed-run-view-removed",
    "refines",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.failed-run-view-removed",
    "verifies",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.build-invalidates-view",
    "refines",
    "spec:consumers.wholesale-view-rewrite",
  ],
  [
    "spec:consumers.wholesale-view-rewrite.build-invalidates-view",
    "verifies",
    "spec:consumers.wholesale-view-rewrite",
  ],
  ["spec:validation.diagnostic-rendering", "refines", "spec:validation.two-check-families"],
  ["spec:validation.diagnostic-rendering", "dependsOn", "spec:consumers.design-review"],
  [
    "spec:validation.diagnostic-rendering.composed-location",
    "refines",
    "spec:validation.diagnostic-rendering",
  ],
  [
    "spec:validation.diagnostic-rendering.composed-location",
    "verifies",
    "spec:validation.diagnostic-rendering",
  ],
  [
    "spec:validation.diagnostic-rendering.table-cell-location",
    "refines",
    "spec:validation.diagnostic-rendering",
  ],
  [
    "spec:validation.diagnostic-rendering.table-cell-location",
    "verifies",
    "spec:validation.diagnostic-rendering",
  ],
  ["spec:validation.validator-self-testing", "refines", "spec:validation.two-check-families"],
] as const;
