// The accepted engine components and their authored structural edges. This is a committed oracle:
// tests compare the independently extracted graph with these reviewed declarations rather than
// deriving expected ownership or uses from source paths or imports.

export const expectedComponentIds = [
  "component:protocol.adapters",
  "component:protocol.cli",
  "component:protocol.codegen",
  "component:protocol.extract",
  "component:protocol.graph",
  "component:protocol.import",
  "component:protocol.model",
  "component:protocol.notation",
  "component:protocol.projections",
  "component:protocol.reader",
  "component:protocol.runner",
  "component:protocol.testing",
  "component:protocol.validate",
] as const;

// These impl anchors deliberately have no component. The skill/document realization anchors live
// outside the engine source seams and therefore have no truthful owner among the accepted
// component set.
export const structuralMembershipExceptions = [
  "impl:protocol.authoring-on-ramp",
  "impl:protocol.authoring-recipes",
  "impl:protocol.delivery-session-on-ramp",
] as const;

export const expectedMemberOfEdges = [
  ["impl:protocol.example-runner-adapter", "component:protocol.adapters"],
  ["impl:protocol.regenerability", "component:protocol.cli"],
  ["impl:protocol.wholesale-view-build-invalidation", "component:protocol.cli"],
  ["impl:protocol.build-pipeline-emit", "component:protocol.cli"],
  ["impl:protocol.extraction-determinism", "component:protocol.cli"],
  ["impl:protocol.diagnostic-rendering-cli", "component:protocol.cli"],
  ["impl:protocol.build-pipeline-query", "component:protocol.cli"],
  ["impl:protocol.wholesale-view-rewrite", "component:protocol.cli"],
  ["impl:protocol.agent-surface-cli", "component:protocol.cli"],
  ["impl:protocol.census-page-cli", "component:protocol.cli"],
  ["impl:protocol.gherkin-view-cli", "component:protocol.cli"],
  ["impl:protocol.mermaid-view-cli", "component:protocol.cli"],
  ["impl:protocol.sdp-import", "component:protocol.cli"],
  ["impl:protocol.spec-scaffolder", "component:protocol.cli"],
  ["impl:protocol.executable-contracts", "component:protocol.codegen"],
  ["impl:protocol.runnable-modules", "component:protocol.codegen"],
  ["impl:protocol.anchor-extraction", "component:protocol.extract"],
  ["impl:protocol.derive-graph", "component:protocol.extract"],
  ["impl:protocol.gherkin-authoring", "component:protocol.extract"],
  ["impl:protocol.exclusion-surface", "component:protocol.extract"],
  ["impl:protocol.duplicate-id-exclusion", "component:protocol.extract"],
  ["impl:protocol.extract", "component:protocol.extract"],
  ["impl:protocol.markdown-pack-authoring", "component:protocol.extract"],
  ["impl:protocol.envelope-contract", "component:protocol.extract"],
  ["impl:protocol.prose-ownership", "component:protocol.extract"],
  ["impl:protocol.markdown-authoring", "component:protocol.extract"],
  ["impl:protocol.markdown-parser", "component:protocol.extract"],
  ["impl:protocol.discover-files", "component:protocol.extract"],
  ["impl:protocol.protocol-bindings", "component:protocol.extract"],
  ["impl:protocol.static-reification", "component:protocol.extract"],
  ["impl:protocol.carrier-reification", "component:protocol.extract"],
  ["impl:protocol.oracle-target-eligibility", "component:protocol.graph"],
  ["impl:protocol.schema-version", "component:protocol.graph"],
  ["impl:protocol.graph-claims", "component:protocol.graph"],
  ["impl:protocol.delivery-facts", "component:protocol.graph"],
  ["impl:protocol.example-space", "component:protocol.graph"],
  ["impl:protocol.sdp-import-core", "component:protocol.import"],
  ["impl:protocol.sdp-import-markdown-emit", "component:protocol.import"],
  ["impl:protocol.stable-ids", "component:protocol.model"],
  ["impl:protocol.anchor-model", "component:protocol.model"],
  ["impl:protocol.spec-descriptors", "component:protocol.model"],
  ["impl:protocol.pack-aggregate", "component:protocol.model"],
  ["impl:protocol.spec-relations", "component:protocol.model"],
  ["impl:protocol.spec-sections", "component:protocol.model"],
  ["impl:protocol.spec-primitive", "component:protocol.model"],
  ["impl:protocol.slot-notation", "component:protocol.notation"],
  ["impl:protocol.census-page", "component:protocol.projections"],
  ["impl:protocol.derived-readiness-banner", "component:protocol.projections"],
  ["impl:protocol.binding-language-spec-page", "component:protocol.projections"],
  ["impl:protocol.diagnostic-rendering-design-review", "component:protocol.projections"],
  ["impl:protocol.binding-language-pack-table", "component:protocol.projections"],
  ["impl:protocol.binding-language-index-table", "component:protocol.projections"],
  ["impl:protocol.projections-model", "component:protocol.projections"],
  ["impl:protocol.design-review", "component:protocol.projections"],
  ["impl:protocol.gherkin-view", "component:protocol.projections"],
  ["impl:protocol.mermaid-view", "component:protocol.projections"],
  ["impl:protocol.reader-impact", "component:protocol.reader"],
  ["impl:protocol.agent-surface", "component:protocol.reader"],
  ["impl:protocol.reader", "component:protocol.reader"],
  ["impl:protocol.example-runner", "component:protocol.runner"],
  ["impl:protocol.example-testing-helpers", "component:protocol.testing"],
  ["impl:protocol.kind-evidence", "component:protocol.validate"],
  ["impl:protocol.readiness-floor", "component:protocol.validate"],
  ["impl:protocol.verifier-semantics", "component:protocol.validate"],
  ["impl:protocol.validation-families", "component:protocol.validate"],
  ["impl:protocol.referential-integrity", "component:protocol.validate"],
  ["impl:protocol.claim-separation", "component:protocol.validate"],
  ["impl:protocol.verifies-linkage", "component:protocol.validate"],
  ["impl:protocol.oracle-linkage", "component:protocol.validate"],
  ["impl:protocol.pack-coherence", "component:protocol.validate"],
  ["impl:protocol.orphan-signal", "component:protocol.validate"],
  ["impl:protocol.authored-honesty-shape", "component:protocol.validate"],
  ["impl:protocol.authored-honesty-delivery-facts", "component:protocol.validate"],
  ["impl:protocol.verifier-gap-signal", "component:protocol.validate"],
  ["impl:protocol.graph-index", "component:protocol.validate"],
  ["impl:protocol.validation-contracts", "component:protocol.validate"],
] as const;

// A uses edge tracks real imports (value or type) from another component's source files; imports
// that exist only to author the anchors themselves (the stable-id and anchor-builder modules)
// confer no edge. The convention is stated in spec:protocol.structural-self-binding.
export const expectedUsesEdges = [
  ["component:protocol.adapters", "component:protocol.runner"],
  ["component:protocol.cli", "component:protocol.codegen"],
  ["component:protocol.cli", "component:protocol.extract"],
  ["component:protocol.cli", "component:protocol.graph"],
  ["component:protocol.cli", "component:protocol.import"],
  ["component:protocol.cli", "component:protocol.model"],
  ["component:protocol.cli", "component:protocol.projections"],
  ["component:protocol.cli", "component:protocol.reader"],
  ["component:protocol.cli", "component:protocol.validate"],
  ["component:protocol.codegen", "component:protocol.graph"],
  ["component:protocol.codegen", "component:protocol.notation"],
  ["component:protocol.codegen", "component:protocol.validate"],
  ["component:protocol.extract", "component:protocol.graph"],
  ["component:protocol.extract", "component:protocol.model"],
  ["component:protocol.extract", "component:protocol.notation"],
  ["component:protocol.extract", "component:protocol.validate"],
  ["component:protocol.graph", "component:protocol.model"],
  ["component:protocol.graph", "component:protocol.notation"],
  ["component:protocol.import", "component:protocol.extract"],
  ["component:protocol.import", "component:protocol.validate"],
  ["component:protocol.projections", "component:protocol.extract"],
  ["component:protocol.projections", "component:protocol.graph"],
  ["component:protocol.projections", "component:protocol.model"],
  ["component:protocol.projections", "component:protocol.notation"],
  ["component:protocol.projections", "component:protocol.reader"],
  ["component:protocol.projections", "component:protocol.validate"],
  ["component:protocol.reader", "component:protocol.graph"],
  ["component:protocol.reader", "component:protocol.model"],
  ["component:protocol.reader", "component:protocol.validate"],
  ["component:protocol.runner", "component:protocol.notation"],
  ["component:protocol.testing", "component:protocol.adapters"],
  ["component:protocol.testing", "component:protocol.runner"],
  ["component:protocol.validate", "component:protocol.graph"],
  ["component:protocol.validate", "component:protocol.model"],
  ["component:protocol.validate", "component:protocol.notation"],
] as const;
