import { pack, packId, ref } from "@libar-dev/software-delivery-protocol";

export const selfHostingV1Pack = pack({
  id: packId("pack:self-hosting-v1"),
  title: "Self-hosting",
  framing: "The Protocol authors and validates its own delivery model.",
  specs: [
    ref("spec:carrier.markdown-authoring"),
    ref("spec:carrier.envelope-contract"),
    ref("spec:carrier.markdown-parser"),
    ref("spec:carrier.sdp-import"),
    ref("spec:carrier.sdp-import.round-trip"),
    ref("spec:carrier.prose-ownership-rule"),
    ref("spec:protocol.self-hosting"),
    ref("spec:extraction.derive-graph"),
    ref("spec:extraction.determinism"),
    ref("spec:extraction.build-pipeline"),
    ref("spec:validation.readiness-floor"),
    ref("spec:validation.duplicate-ids"),
    ref("spec:validation.two-check-families"),
    ref("spec:consumers.projections-model"),
    ref("spec:consumers.agent-surface"),
    ref("spec:consumers.design-review"),
    ref("spec:model.protocol-domain"),
    ref("spec:model.core-model"),
    ref("spec:model.spec-sections"),
    ref("spec:model.relations"),
    ref("spec:model.stable-ids"),
    ref("spec:model.pack-aggregate"),
    ref("spec:model.anchors"),
    ref("spec:validation.duplicate-ids.dual-carrier"),
    ref("spec:decisions.plain-language-references"),
    ref("spec:decisions.concept-docs-dissolve"),
  ],
  modelRefs: [ref("spec:model.protocol-domain"), ref("spec:model.core-model")],
});
