import { pack, packId, ref } from "@libar-dev/software-delivery-protocol";

export const selfHostingV1Pack = pack({
  id: packId("pack:self-hosting-v1"),
  title: "Self-hosting",
  framing: "The Protocol authors and validates its own delivery model.",
  specs: [
    ref("spec:carrier.markdown-authoring"),
    ref("spec:carrier.envelope-contract"),
    ref("spec:carrier.markdown-parser"),
    ref("spec:carrier.sdp-import"),
    ref("spec:carrier.sdp-import.round-trip"),
    ref("spec:carrier.prose-ownership-rule"),
    ref("spec:protocol.self-hosting"),
    ref("spec:extraction.derive-graph"),
    ref("spec:extraction.determinism"),
    ref("spec:extraction.build-pipeline"),
    ref("spec:extraction.excludes"),
    ref("spec:extraction.claim-taxonomy"),
    ref("spec:extraction.regenerability"),
    ref("spec:extraction.schema-versioning"),
    ref("spec:extraction.executable-contracts"),
    ref("spec:validation.readiness-floor"),
    ref("spec:validation.duplicate-ids"),
    ref("spec:validation.two-check-families"),
    ref("spec:validation.referential-integrity"),
    ref("spec:validation.claim-separation"),
    ref("spec:validation.verification-linkage"),
    ref("spec:validation.pack-coherence"),
    ref("spec:validation.authored-honesty"),
    ref("spec:validation.warn-level-signals"),
    ref("spec:consumers.projections-model"),
    ref("spec:consumers.agent-surface"),
    ref("spec:consumers.design-review"),
    ref("spec:consumers.reader"),
    ref("spec:consumers.edit-model"),
    ref("spec:model.protocol-domain"),
    ref("spec:model.core-model"),
    ref("spec:model.spec-sections"),
    ref("spec:model.relations"),
    ref("spec:model.stable-ids"),
    ref("spec:model.pack-aggregate"),
    ref("spec:model.anchors"),
    ref("spec:validation.duplicate-ids.dual-carrier"),
    ref("spec:validation.warn-level-signals.orphan-signal"),
    ref("spec:validation.warn-level-signals.ready-gap-signal"),
    ref("spec:decisions.plain-language-references"),
    ref("spec:decisions.concept-docs-dissolve"),
    ref("spec:decisions.one-validation-path"),
    ref("spec:decisions.sdp-ts-extension"),
    ref("spec:decisions.point-per-example"),
    ref("spec:decisions.carrier-ruling"),
    ref("spec:decisions.prose-ownership"),
    ref("spec:decisions.envelope-grammar-posture"),
    ref("spec:decisions.exclusion-contract"),
    ref("spec:decisions.executable-meta-model"),
    ref("spec:decisions.adopt-the-nouns"),
    ref("spec:decisions.one-primitive"),
    ref("spec:decisions.protocol-naming"),
    ref("spec:decisions.binding-not-liveness"),
    ref("spec:decisions.content-only-sections"),
    ref("spec:decisions.typing-law"),
    ref("spec:decisions.kind-conditional-floor"),
    ref("spec:decisions.carried-evidence"),
    ref("spec:decisions.pack-reified"),
    ref("spec:decisions.agent-surface-scripts-graph"),
    ref("spec:decisions.mcp-deferred"),
  ],
  modelRefs: [ref("spec:model.protocol-domain"), ref("spec:model.core-model")],
});
