// GENERATED by `sdp build` — the step contract of spec:orders.create-order.valid-cart.
// Derived from the extracted graph (the statically-reified truth, MD-14), keyed by spec ID:
// regenerable, never edited, importable because it is a projection (JS-B2.6's pattern) —
// never the authored spec module (JS-B2.3: no spec↔code import edges).

import type { ExampleContract } from "@libar-dev/software-delivery-protocol/runner";

export type Step =
  | "a customer has a cart with {n} line items"
  | "every line item has quantity {q} and unit price {price}"
  | "every cart item is {availability}"
  | "the customer submits the cart for order creation"
  | "an order is created with total {total}"
  | "the order contains the original cart lines";

export type StepParams = {
  readonly "a customer has a cart with {n} line items": { readonly n: number };
  readonly "every line item has quantity {q} and unit price {price}": { readonly q: number; readonly price: number };
  readonly "every cart item is {availability}": { readonly availability: "in stock" | "out of stock" };
  readonly "the customer submits the cart for order creation": Record<string, never>;
  readonly "an order is created with total {total}": { readonly total: number };
  readonly "the order contains the original cart lines": Record<string, never>;
};

export const validCartContract: ExampleContract<Step, StepParams> = {
  spec: "spec:orders.create-order.valid-cart",
  title: "Valid cart creates an order",
  steps: [
    { kind: "given", text: "a customer has a cart with {n} line items", params: { n: 2 } },
    { kind: "given", text: "every line item has quantity {q} and unit price {price}", params: { q: 1, price: 50 } },
    { kind: "given", text: "every cart item is {availability}", params: { availability: "in stock" } },
    { kind: "when", text: "the customer submits the cart for order creation", params: {} },
    { kind: "then", text: "an order is created with total {total}", params: { total: 150 } },
    { kind: "then", text: "the order contains the original cart lines", params: {} },
  ],
};
