// GENERATED by `sdp build` — derived, regenerable, never edited (mock emission).
// (This exhibit folder is named contracts/ only because the repo rightly
// gitignores generated/ everywhere; the real emission lands under generated/.)
// Source of truth: the graph node for spec:orders.create-order.valid-cart.
// Identical no matter which surface authored the spec (TS DSL / grammar /
// markdown document / TSX document) — the contract sees only the graph.

import type { ExampleContract } from "../protocol-runner";

export type Step =
  | "A customer has a cart with one or more line items."
  | "Every cart item is in stock."
  | "Each line item has a positive quantity and a unit price."
  | "The customer submits the cart for order creation."
  | "An order is created."
  | "The order total equals the sum of quantity multiplied by unit price for each line item."
  | "The order contains the original cart lines.";

export const validCartContract: ExampleContract<Step> = {
  spec: "spec:orders.create-order.valid-cart",
  title: "Valid cart creates an order",
  steps: [
    { kind: "given", text: "A customer has a cart with one or more line items." },
    { kind: "given", text: "Every cart item is in stock." },
    { kind: "given", text: "Each line item has a positive quantity and a unit price." },
    { kind: "when",  text: "The customer submits the cart for order creation." },
    { kind: "then",  text: "An order is created." },
    { kind: "then",  text: "The order total equals the sum of quantity multiplied by unit price for each line item." },
    { kind: "then",  text: "The order contains the original cart lines." },
  ],
};
