// GENERATED by `sdp build` (mock emission) — the 4-seam step contract,
// extended: each step now carries its typed parameter shape (StepParams) and
// the example's AUTHORED bound point (params values). Identical no matter
// which surface authored the spec; the contract sees only the graph.

import type { ExampleContract } from "../protocol-runner";

export type Step =
  | "a customer has a cart with {n} line items"
  | "every line item has quantity {q} and unit price {price}"
  | "every cart item is {availability}"
  | "the customer submits the cart for order creation"
  | "an order is created with total {total}"
  | "the order contains the original cart lines";

export type StepParams = {
  "a customer has a cart with {n} line items": { n: number };
  "every line item has quantity {q} and unit price {price}": { q: number; price: number };
  "every cart item is {availability}": { availability: "in stock" | "out of stock" };
  "the customer submits the cart for order creation": Record<string, never>;
  "an order is created with total {total}": { total: number };
  "the order contains the original cart lines": Record<string, never>;
};

export const validCartContract: ExampleContract<Step, StepParams> = {
  spec: "spec:orders.create-order.valid-cart",
  title: "Valid cart creates an order",
  steps: [
    { kind: "given", text: "a customer has a cart with {n} line items", params: { n: 2 } },
    {
      kind: "given",
      text: "every line item has quantity {q} and unit price {price}",
      params: { q: 1, price: 50 },
    },
    {
      kind: "given",
      text: "every cart item is {availability}",
      params: { availability: "in stock" },
    },
    { kind: "when", text: "the customer submits the cart for order creation", params: {} },
    { kind: "then", text: "an order is created with total {total}", params: { total: 100 } },
    { kind: "then", text: "the order contains the original cart lines", params: {} },
  ],
};
