// GENERATED by `sdp build` (mock emission) — the EXAMPLE SPACE of the parent
// behavior spec: one typed dimension per parameter slot in the parent's step
// vocabulary, plus each example child's bound point. Derived from the graph,
// regenerable, never edited — the same legal status as the step contract and
// the ids union (JS-B2.6's pattern), one level up the refines edge.
//
// Consumers: the harness (dials = dimensions; presets = points), the oracle
// (typed against Conditions — so vocabulary drift breaks the oracle at tsc
// time, see oracle-drift-demo.ts), and the coverage verdict.

/** The OUTCOME type — generated from the parent's THEN vocabulary, variant
 *  for variant ("an order is created with total {total:number}" · "the cart
 *  is rejected because {reason:…}"). `unspecified` is contributed by the
 *  runner core — the one outcome no spec ever states. Because the oracle must
 *  return THIS type, "the oracle may never claim more than the specs state"
 *  is a tsc error, not an honor-system rule: an oracle returning
 *  { kind: "backordered" } does not compile until the parent's Then
 *  vocabulary says it first. */
export type CreateOrderOutcome =
  | { kind: "order-created"; total: number }
  | { kind: "rejected"; reason: "empty cart" | "out of stock" }
  | { kind: "unspecified" };

/** One value per INPUT dimension (Given/When slots) — what the dials produce
 *  and expected() consumes. Then slots are not dimensions; they are the
 *  outcome shape above. */
export interface CreateOrderConditions {
  n: number;
  q: number;
  price: number;
  availability: "in stock" | "out of stock";
}

export interface SpaceDimension {
  readonly name: keyof CreateOrderConditions;
  readonly type: "number" | "enum";
  readonly values?: readonly string[];
  readonly label: string;
}

/** An example binds a point — possibly PARTIAL (an empty cart binds n=0 and
 *  nothing else; unbound dimensions are "any"). */
export interface ExamplePoint {
  readonly spec: string;
  readonly point: Partial<CreateOrderConditions>;
}

export const createOrderSpace = {
  spec: "spec:orders.create-order",
  dimensions: [
    { name: "n", type: "number", label: "line items in the cart" },
    { name: "q", type: "number", label: "quantity per line" },
    { name: "price", type: "number", label: "unit price per line" },
    {
      name: "availability",
      type: "enum",
      values: ["in stock", "out of stock"],
      label: "stock availability",
    },
  ] as const satisfies readonly SpaceDimension[],
  examples: [
    {
      spec: "spec:orders.create-order.valid-cart",
      point: { n: 2, q: 1, price: 50, availability: "in stock" },
    },
    {
      spec: "spec:orders.create-order.invalid-cart",
      point: { n: 0 },
    },
    {
      spec: "spec:orders.create-order.out-of-stock",
      point: { n: 1, q: 1, price: 10, availability: "out of stock" },
    },
  ] as const satisfies readonly ExamplePoint[],
};
